-- 0005: synthetic internal systems (schema synth). CEFMS, P2, CMP, EMS and BUILDER have no public
-- endpoints; these tables use the vocabulary from ER 37-1-30, ER 5-1-11 and the BUILDER SMS fact sheet
-- (docs/research/evs_public_data_report.md section 5). Every row is generated by db/seed and carries
-- source = 'synthetic'. Project names, states, districts and FY26 amounts come from the public FY26
-- O&M budget justification (J-sheet); everything else is invented.

CREATE TABLE synth.program (
    program_code     text PRIMARY KEY,                 -- e.g. LRD-NAV
    name             text NOT NULL,
    business_line    text NOT NULL,
    business_line_code text NOT NULL,                  -- NAV FRM HYD REC ENS WTR
    division         text NOT NULL,
    appropriation    text NOT NULL,
    fiscal_year      integer NOT NULL,
    funded_amount    numeric(14,2) NOT NULL,
    schedule_health  text NOT NULL CHECK (schedule_health IN ('on_track', 'at_risk', 'late')),
    story            text,                             -- demo narrative tag, e.g. over_obligated
    source           text NOT NULL DEFAULT 'synthetic'
);

CREATE TABLE synth.p2_project (
    p2_project_no    text PRIMARY KEY,                 -- 6 digits
    name             text NOT NULL,
    program_code     text NOT NULL REFERENCES synth.program (program_code),
    district         text NOT NULL,                    -- EROC symbol, e.g. LRL
    division         text NOT NULL,
    state            text,
    business_line    text NOT NULL,
    phase            text NOT NULL CHECK (phase IN ('Reconnaissance', 'Feasibility', 'PED', 'Construction', 'O&M')),
    pdt_lead         text NOT NULL,
    pmp_approved_date date,
    baseline_start   date,
    baseline_finish  date,
    current_finish   date,
    pct_complete     numeric(5,1) NOT NULL DEFAULT 0,
    funded_amount    numeric(14,2) NOT NULL,
    jsheet_amount    numeric(14,2),                    -- FY26 O&M J-sheet figure the funding is scaled from
    jsheet_source    text,                             -- citation for jsheet_amount
    schedule_health  text NOT NULL CHECK (schedule_health IN ('on_track', 'at_risk', 'late')),
    story            text,
    source           text NOT NULL DEFAULT 'synthetic'
);
CREATE INDEX p2_project_program_idx ON synth.p2_project (program_code);
CREATE INDEX p2_project_district_idx ON synth.p2_project (district);

CREATE TABLE synth.p2_milestone (
    milestone_id     bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    p2_project_no    text NOT NULL REFERENCES synth.p2_project (p2_project_no) ON DELETE CASCADE,
    seq              integer NOT NULL,
    code             text NOT NULL,                    -- FCSA CHIEF PPA AWARD BCOES
    name             text NOT NULL,
    baseline_date    date,
    forecast_date    date,                             -- "current date" in P2; current_date is reserved in SQL
    actual_date      date,
    status           text NOT NULL CHECK (status IN ('complete', 'scheduled', 'slipped')),
    owner            text,
    description      text,
    status_last_changed_on timestamptz,
    UNIQUE (p2_project_no, code)
);

CREATE TABLE synth.cefms_work_item (
    work_item_code   text PRIMARY KEY,                 -- 6 char, e.g. 001SZV
    p2_project_no    text REFERENCES synth.p2_project (p2_project_no) ON DELETE CASCADE,
    district         text NOT NULL,
    appropriation    text NOT NULL CHECK (appropriation IN ('96X3121', '96X3122', '96X3123', '96X3112', '96X4902')),
    description      text NOT NULL,
    cost_share_pct   numeric(5,2) NOT NULL DEFAULT 0,
    customer_order_no text,
    source           text NOT NULL DEFAULT 'synthetic'
);
CREATE INDEX cefms_work_item_project_idx ON synth.cefms_work_item (p2_project_no);

-- Fiscal-month execution ladder: allotment >= commitment >= obligation >= expenditure >= disbursement (cumulative).
CREATE TABLE synth.cefms_funding (
    funding_id       bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    work_item_code   text NOT NULL REFERENCES synth.cefms_work_item (work_item_code) ON DELETE CASCADE,
    appropriation    text NOT NULL CHECK (appropriation IN ('96X3121', '96X3122', '96X3123', '96X3112', '96X4902')),
    fiscal_year      integer NOT NULL,
    fiscal_month     integer NOT NULL CHECK (fiscal_month BETWEEN 1 AND 12),   -- 1 = October
    period           date NOT NULL,                    -- first calendar day of the fiscal month
    plan_obligation  numeric(14,2) NOT NULL,           -- cumulative plan curve
    allotment        numeric(14,2) NOT NULL,
    commitment       numeric(14,2) NOT NULL,
    obligation       numeric(14,2) NOT NULL,
    expenditure      numeric(14,2) NOT NULL,
    disbursement     numeric(14,2) NOT NULL,
    source           text NOT NULL DEFAULT 'synthetic',
    UNIQUE (work_item_code, fiscal_year, fiscal_month)
);
CREATE INDEX cefms_funding_period_idx ON synth.cefms_funding (fiscal_year, fiscal_month);

CREATE TABLE synth.ems_labor_plan (
    district         text NOT NULL,
    pay_period       text NOT NULL,                    -- FY-PP, e.g. 2026-14
    hours_plan       numeric(10,1) NOT NULL,
    PRIMARY KEY (district, pay_period)
);

CREATE TABLE synth.ems_labor_log (
    labor_id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    employee_id      text NOT NULL,
    district         text NOT NULL,
    pay_period       text NOT NULL,
    pay_period_end   date NOT NULL,
    work_item_code   text REFERENCES synth.cefms_work_item (work_item_code) ON DELETE SET NULL,
    hours_regular    numeric(6,2) NOT NULL,
    hours_overtime   numeric(6,2) NOT NULL DEFAULT 0,
    labor_cost       numeric(12,2) NOT NULL,
    charge_type      text NOT NULL CHECK (charge_type IN ('project', 'customer order', 'departmental overhead', 'G&A', 'leave')),
    labor_correction_flag boolean NOT NULL DEFAULT false,
    source           text NOT NULL DEFAULT 'synthetic'
);
CREATE INDEX ems_labor_log_district_pp_idx ON synth.ems_labor_log (district, pay_period);
CREATE INDEX ems_labor_log_work_item_idx ON synth.ems_labor_log (work_item_code);

CREATE TABLE synth.cmp_contract (
    contract_no      text PRIMARY KEY,                 -- W912xx-26-C-0001
    p2_project_no    text NOT NULL REFERENCES synth.p2_project (p2_project_no) ON DELETE CASCADE,
    contractor       text NOT NULL,
    award_date       date NOT NULL,
    ntp_date         date,
    contract_amount  numeric(14,2) NOT NULL,
    pct_complete     numeric(5,1) NOT NULL DEFAULT 0,
    modifications    integer NOT NULL DEFAULT 0,
    contract_status  integer NOT NULL CHECK (contract_status BETWEEN 1 AND 5),   -- 5 = complete in P2
    bcoes_review_date date,
    source           text NOT NULL DEFAULT 'synthetic'
);
CREATE INDEX cmp_contract_project_idx ON synth.cmp_contract (p2_project_no);

CREATE TABLE synth.builder_component (
    component_id     text PRIMARY KEY,
    building_id      text NOT NULL,
    installation     text NOT NULL,
    district         text NOT NULL,
    uniformat_section text NOT NULL,                   -- D30 HVAC, D50 Electrical, B30 Roofing ...
    component_type   text NOT NULL,
    install_year     integer NOT NULL,
    service_life     integer NOT NULL,
    last_inspection_date date NOT NULL,
    ci               numeric(5,1) NOT NULL CHECK (ci BETWEEN 0 AND 100),
    bci              numeric(5,1) NOT NULL CHECK (bci BETWEEN 0 AND 100),
    deficiency_cost  numeric(12,2) NOT NULL,
    work_plan_year   integer NOT NULL,
    story            text,
    source           text NOT NULL DEFAULT 'synthetic'
);
CREATE INDEX builder_component_installation_idx ON synth.builder_component (installation);
CREATE INDEX builder_component_ci_idx ON synth.builder_component (ci);

-- Roll-ups used by the API and by `evs dump-fixtures`.
CREATE VIEW synth.v_project_execution AS
SELECT w.p2_project_no,
       sum(f.obligation)  AS obligated_amount,
       sum(f.expenditure) AS expended_amount
FROM synth.cefms_work_item w
JOIN synth.cefms_funding f ON f.work_item_code = w.work_item_code
JOIN (SELECT work_item_code, max(fiscal_month) AS fm FROM synth.cefms_funding GROUP BY work_item_code) last
  ON last.work_item_code = f.work_item_code AND last.fm = f.fiscal_month
GROUP BY w.p2_project_no;

CREATE VIEW synth.v_program_summary AS
SELECT p.program_code, p.name, p.business_line, p.division, p.funded_amount,
       coalesce(sum(x.obligated_amount), 0) AS obligated_amount,
       coalesce(sum(x.expended_amount), 0)  AS expended_amount,
       round((coalesce(sum(x.obligated_amount), 0) / nullif(p.funded_amount, 0) - 0.78) * 100, 1) AS variance_pct,
       count(j.p2_project_no)::integer AS project_count,
       p.schedule_health, p.story
FROM synth.program p
LEFT JOIN synth.p2_project j ON j.program_code = p.program_code
LEFT JOIN synth.v_project_execution x ON x.p2_project_no = j.p2_project_no
GROUP BY p.program_code;

CREATE VIEW synth.v_execution_curve AS
SELECT f.fiscal_year, f.period,
       sum(f.plan_obligation) AS plan_cumulative,
       sum(f.obligation)      AS obligated_cumulative,
       sum(f.expenditure)     AS expended_cumulative
FROM synth.cefms_funding f
GROUP BY f.fiscal_year, f.period;

CREATE VIEW synth.v_appropriation_summary AS
SELECT f.fiscal_year, f.appropriation,
       sum(f.allotment)   AS allotted,
       sum(f.commitment)  AS committed,
       sum(f.obligation)  AS obligated,
       sum(f.expenditure) AS expended
FROM synth.cefms_funding f
JOIN (SELECT work_item_code, max(fiscal_month) AS fm FROM synth.cefms_funding GROUP BY work_item_code) last
  ON last.work_item_code = f.work_item_code AND last.fm = f.fiscal_month
GROUP BY f.fiscal_year, f.appropriation;

CREATE VIEW synth.v_labor_summary AS
SELECT l.district, l.pay_period, max(l.pay_period_end) AS pay_period_end,
       coalesce(max(p.hours_plan), 0) AS hours_plan,
       sum(l.hours_regular)  AS hours_regular,
       sum(l.hours_overtime) AS hours_overtime,
       sum(l.labor_cost)     AS labor_cost
FROM synth.ems_labor_log l
LEFT JOIN synth.ems_labor_plan p ON p.district = l.district AND p.pay_period = l.pay_period
GROUP BY l.district, l.pay_period;

-- Names WP3 coded against (apps/api/tests/sql/assumed_wp2_schema.sql); same columns, backed by the tables above.
CREATE VIEW synth.cefms_execution AS
SELECT fiscal_year, period, plan_cumulative, obligated_cumulative, expended_cumulative FROM synth.v_execution_curve;

CREATE VIEW synth.cefms_appropriation AS
SELECT a.fiscal_year, a.appropriation,
       CASE a.appropriation
           WHEN '96X3121' THEN 'Investigations'
           WHEN '96X3122' THEN 'Construction'
           WHEN '96X3123' THEN 'Operation and Maintenance'
           WHEN '96X3112' THEN 'Mississippi River and Tributaries'
           WHEN '96X4902' THEN 'Revolving Fund'
       END AS title,
       a.allotted, a.committed, a.obligated, a.expended,
       CASE WHEN a.appropriation = '96X3121' THEN a.fiscal_year END AS expiring_fy
FROM synth.v_appropriation_summary a;

CREATE VIEW synth.builder_facility_condition AS
SELECT building_id, installation, district, uniformat_section, component_type, ci, bci, deficiency_cost, work_plan_year
FROM synth.builder_component;
