"""Lock to gauge pairings for the status engine (rules 4 and 7).

Generated by tools/gauges/derive_gauge_pairings.py against NOAA NWPS on 2026-10-06 (UTC).
Each entry records how the pairing was derived: the NWPS gauge list inside a 0.25 degree box around the NDC GIS
lock point, filtered to gauges whose name carries the same river, preferring names that share a word with the
lock name (within 25 km), else the nearest within 10 km. `usgs_site` is the NWPS `usgsId` of that gauge. Review before relying on a pairing
for anything beyond the demo; a gauge 20 km away reports the pool, not the lock wall.
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class GaugePairing:
    lock_id: str
    lid: str | None
    usgs_site: str | None
    gauge_name: str | None
    distance_km: float | None
    method: str


PAIRINGS: tuple[GaugePairing, ...] = (
    GaugePairing("CU-21", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("CU-22", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("CU-23", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("CU-24", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("IL-01", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("IL-02", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("IL-03", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("IL-04", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("IL-05", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("IL-06", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("IL-07", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("IL-08", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("MI-01", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("MI-02", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("MI-03", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("MI-04", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("MI-05", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("MI-06", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("MI-07", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("MI-08", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("MI-09", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("MI-10", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("MI-11", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("MI-12", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("MI-13", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("MI-14", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("MI-15", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("MI-16", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("MI-17", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("MI-18", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("MI-19", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("MI-20", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("MI-21", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("MI-22", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("MI-24", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("MI-25", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("MI-26", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("MI-27", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("MI-51", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("MI-52", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("MI-55", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("OH-01", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("OH-02", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("OH-03", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("OH-04", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("OH-05", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("OH-21", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("OH-22", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("OH-24", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("OH-25", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("OH-26", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("OH-41", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("OH-42", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("OH-52", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("OH-53", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("OH-71", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("OH-72", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("OH-75", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("OH-76", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("OH-77", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("OH-78", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("OH-79", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("TN-01", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("TN-02", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("TN-03", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("TN-04", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("TN-05", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("TN-06", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("TN-07", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("TN-08", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
    GaugePairing("TN-09", None, None, None, None, "no NWPS gauge on the same river within 10 km"),
)

BY_LOCK: dict[str, GaugePairing] = {p.lock_id: p for p in PAIRINGS}
NOAA_LIDS: tuple[str, ...] = tuple(sorted({p.lid for p in PAIRINGS if p.lid}))
USGS_SITES: tuple[str, ...] = tuple(sorted({p.usgs_site for p in PAIRINGS if p.usgs_site}))
