"""Markdown and HTML renderings of the generated OpenACR (VPAT 2.5 layout: WCAG tables 1 to 3, 508 chapters
3 to 6). The HTML is self-contained, uses real tables with captions and column headers, and conveys adherence
as text so it never depends on colour."""

from __future__ import annotations

import html
from typing import Any

from .engine import CriterionResult, RunSummary
from .mapping import catalog_chapters, load_catalog
from .openacr import level_counts

LEVEL_LABEL = {
    "supports": "Supports",
    "partially-supports": "Partially Supports",
    "does-not-support": "Does Not Support",
    "not-applicable": "Not Applicable",
    "not-evaluated": "Not Evaluated",
}


def _handles() -> dict[str, str]:
    return {str(c["id"]): c.get("handle", "") for ch in load_catalog()["chapters"] for c in ch["criteria"]}


def _web_or_none(row: dict[str, Any]) -> dict[str, Any]:
    for comp in row["components"]:
        if comp["name"] in ("web", "none"):
            return comp["adherence"]
    return row["components"][0]["adherence"]


def _summary_lines(
    doc: dict[str, Any], results: list[CriterionResult], run: RunSummary
) -> list[tuple[str, str]]:
    counts = level_counts(results)
    sha = run.git_sha[:12] if run.git_sha != "unknown" else "unknown"
    lh = (
        f"{run.lighthouse_runs} runs, min accessibility score {run.lighthouse_min_score:.2f}"
        if run.lighthouse_min_score is not None
        else ("no run" if not run.lighthouse_runs else f"{run.lighthouse_runs} runs")
    )
    pa = (
        f"{run.pa11y.total} URLs, {run.pa11y.errors} errors, {run.pa11y.needs_review} needs-review items"
        if run.pa11y
        else "no run"
    )
    kb = (
        f"{sum(1 for k in run.keyboard if k.passed)}/{len(run.keyboard)} routes passed"
        if run.keyboard
        else "no run"
    )
    rf = (
        f"{sum(1 for r in run.reflow if r.passed)}/{len(run.reflow)} cells passed" if run.reflow else "no run"
    )
    return [
        ("Product", f"{doc['product']['name']} {doc['product']['version']}"),
        ("Report date", doc["report_date"]),
        ("Commit", sha),
        (
            "axe-core cells",
            f"{run.cells} ({run.routes} routes x {run.viewports} viewports x {run.themes} themes x {run.motion_settings} motion settings), {run.total_violations} gating violations, {run.total_advisories} advisories",
        ),
        ("Lighthouse CI", lh),
        ("pa11y-ci", pa),
        ("Keyboard smoke", kb),
        ("Reflow smoke (320 px)", rf),
        (
            "WCAG 2.1 A/AA rows",
            ", ".join(
                f"{counts[k]} {LEVEL_LABEL[k].lower()}"
                for k in (
                    "supports",
                    "partially-supports",
                    "does-not-support",
                    "not-applicable",
                    "not-evaluated",
                )
            ),
        ),
    ]


def render_markdown(doc: dict[str, Any], results: list[CriterionResult], run: RunSummary) -> str:
    handles = _handles()
    chapters = catalog_chapters()
    out: list[str] = [f"# {doc['title']}", ""]
    out.append(
        "Generated by evs-acr-gen. Rows marked Not Evaluated carry no conformance claim. This is a demonstration build."
    )
    out.append("")
    out.append("## Summary")
    out.append("")
    out.append("| Item | Value |")
    out.append("|---|---|")
    for k, v in _summary_lines(doc, results, run):
        out.append(f"| {k} | {v} |")
    out.append("")
    for key in ("notes", "evaluation_methods_used", "legal_disclaimer"):
        out.append(f"## {key.replace('_', ' ').capitalize()}")
        out.append("")
        out.append(str(doc[key]).strip())
        out.append("")
    out.append("## Evidence by criterion (WCAG 2.1 A and AA)")
    out.append("")
    out.append("| Criterion | Level | Method | Adherence | Automated cells | Open violations | Attestation |")
    out.append("|---|---|---|---|---|---|---|")
    for r in results:
        att = r.attestation_status or "none"
        out.append(
            f"| {r.num} {r.name} | {r.level} | {r.method.replace('_', ' ')} | {LEVEL_LABEL[r.adherence]} | {r.cells} | {len(r.violations)} | {att} |"
        )
    out.append("")
    for chapter_id, chapter in chapters.items():
        rows = doc["chapters"][chapter_id]["criteria"]
        out.append(f"## {chapter['label']}")
        out.append("")
        note = doc["chapters"][chapter_id].get("notes", "")
        if note:
            out.append(note.strip())
            out.append("")
        out.append("| Criteria | Conformance Level | Remarks and Explanations |")
        out.append("|---|---|---|")
        for row in rows:
            adherence = _web_or_none(row)
            remarks = " ".join(str(adherence.get("notes", "")).split()).replace("|", "\\|")
            out.append(
                f"| {row['num']} {handles.get(str(row['num']), '')} | {LEVEL_LABEL.get(adherence['level'], adherence['level'])} | {remarks} |"
            )
        out.append("")
    return "\n".join(out)


_CSS = """
:root { color-scheme: light; }
body { font-family: "Public Sans", "Source Sans Pro", system-ui, sans-serif; line-height: 1.5; margin: 0; color: #1b1b1b; background: #fff; }
.skip { position: absolute; left: -999px; top: 0; background: #162e51; color: #fff; padding: .5rem 1rem; }
.skip:focus { left: 0; outline: .25rem solid #ffbe2e; }
header, main, footer { max-width: 72rem; margin: 0 auto; padding: 1rem; }
header { border-bottom: .25rem solid #005ea2; }
h1 { font-size: 1.75rem; } h2 { font-size: 1.375rem; margin-top: 2rem; }
table { border-collapse: collapse; width: 100%; margin: .5rem 0 1.5rem; font-size: .95rem; }
caption { text-align: left; font-weight: 700; padding: .5rem 0; }
th, td { border: 1px solid #a9aeb1; padding: .5rem; vertical-align: top; text-align: left; }
th { background: #f0f0f0; }
.level { font-weight: 700; white-space: nowrap; }
.level::before { display: inline-block; width: 1.1em; margin-right: .35em; text-align: center; }
.level-supports::before { content: "\\2713"; } /* check */
.level-partially-supports::before { content: "\\25B3"; } /* triangle */
.level-does-not-support::before { content: "\\2716"; } /* cross */
.level-not-applicable::before { content: "\\2014"; } /* dash */
.level-not-evaluated::before { content: "\\25CB"; } /* ring */
:focus-visible { outline: .25rem solid #2491ff; outline-offset: .125rem; }
@media (max-width: 40em) { table, thead, tbody, tr, th, td { display: block; } thead { position: absolute; left: -999px; } td::before { content: attr(data-label) ": "; font-weight: 700; } }
@media (prefers-reduced-motion: reduce) { * { scroll-behavior: auto !important; } }
"""


def _esc(value: Any) -> str:
    return html.escape(" ".join(str(value).split()))


def render_html(doc: dict[str, Any], results: list[CriterionResult], run: RunSummary) -> str:
    handles = _handles()
    chapters = catalog_chapters()
    parts: list[str] = []
    parts.append(
        '<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width, initial-scale=1">'
    )
    parts.append(f"<title>{_esc(doc['title'])}</title>\n<style>{_CSS}</style>\n</head>\n<body>")
    parts.append('<a class="skip" href="#main">Skip to main content</a>')
    parts.append(
        f"<header><h1>{_esc(doc['title'])}</h1><p>Generated by evs-acr-gen. Rows marked Not Evaluated carry no conformance claim. This is a demonstration build.</p></header>"
    )
    parts.append('<main id="main" tabindex="-1">')
    parts.append(
        '<section aria-labelledby="summary"><h2 id="summary">Summary</h2><table><caption>Report summary</caption><thead><tr><th scope="col">Item</th><th scope="col">Value</th></tr></thead><tbody>'
    )
    for k, v in _summary_lines(doc, results, run):
        parts.append(f'<tr><th scope="row">{_esc(k)}</th><td data-label="Value">{_esc(v)}</td></tr>')
    parts.append("</tbody></table></section>")
    for key, label in (
        ("notes", "Notes"),
        ("evaluation_methods_used", "Evaluation methods used"),
        ("legal_disclaimer", "Legal disclaimer"),
    ):
        parts.append(
            f'<section aria-labelledby="{key}"><h2 id="{key}">{label}</h2><p>{_esc(doc[key])}</p></section>'
        )
    parts.append(
        '<section aria-labelledby="evidence"><h2 id="evidence">Evidence by criterion (WCAG 2.1 A and AA)</h2>'
    )
    parts.append(
        '<table><caption>Automated and manual evidence per success criterion</caption><thead><tr><th scope="col">Criterion</th><th scope="col">Level</th><th scope="col">Method</th><th scope="col">Adherence</th><th scope="col">Automated cells</th><th scope="col">Open violations</th><th scope="col">Attestation</th></tr></thead><tbody>'
    )
    for r in results:
        parts.append(
            f'<tr><th scope="row">{_esc(r.num)} {_esc(r.name)}</th><td data-label="Level">{_esc(r.level)}</td><td data-label="Method">{_esc(r.method.replace("_", " "))}</td>'
            f'<td data-label="Adherence"><span class="level level-{r.adherence}">{LEVEL_LABEL[r.adherence]}</span></td>'
            f'<td data-label="Automated cells">{r.cells}</td><td data-label="Open violations">{len(r.violations)}</td><td data-label="Attestation">{_esc(r.attestation_status or "none")}</td></tr>'
        )
    parts.append("</tbody></table></section>")
    for chapter_id, chapter in chapters.items():
        rows = doc["chapters"][chapter_id]["criteria"]
        parts.append(
            f'<section aria-labelledby="{chapter_id}"><h2 id="{chapter_id}">{_esc(chapter["label"])}</h2>'
        )
        note = doc["chapters"][chapter_id].get("notes", "")
        if note:
            parts.append(f"<p>{_esc(note)}</p>")
        parts.append(
            f'<table><caption>{_esc(chapter["label"])}</caption><thead><tr><th scope="col">Criteria</th><th scope="col">Conformance Level</th><th scope="col">Remarks and Explanations</th></tr></thead><tbody>'
        )
        for row in rows:
            adherence = _web_or_none(row)
            level = adherence["level"]
            parts.append(
                f'<tr><th scope="row">{_esc(row["num"])} {_esc(handles.get(str(row["num"]), ""))}</th>'
                f'<td data-label="Conformance Level"><span class="level level-{level}">{LEVEL_LABEL.get(level, level)}</span></td>'
                f'<td data-label="Remarks and Explanations">{_esc(adherence.get("notes", ""))}</td></tr>'
            )
        parts.append("</tbody></table></section>")
    parts.append("</main>")
    parts.append(
        f"<footer><p>Repository: {_esc(doc['repository'])}. Feedback: {_esc(doc['feedback'])}. License: {_esc(doc['license'])}.</p></footer>"
    )
    parts.append("</body>\n</html>\n")
    return "\n".join(parts)
