-- Oracle DDL/DML rebuilt from the APEX 24.2 Strategic Planner starter app export (f7150, MIT licence).
-- Generated by db/ora2pg/extract_apex_install_scripts.py; input to ora2pg. Do not edit by hand.

-- source: install_sequences.sql (p_sequence 10, Sequences)
create sequence SP_SEQ
;

-- source: install_sequences.sql (p_sequence 10, Sequences)
create sequence sp_kb_stack_rank_seq
start with 1
increment by 1
cache 20
nocycle;
