-- Oracle DDL/DML rebuilt from the APEX 24.2 Strategic Planner starter app export (f7150, MIT licence).
-- Generated by db/ora2pg/extract_apex_install_scripts.py; input to ora2pg. Do not edit by hand.

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (1, 'AF', 'Afghanistan', 'EMEA', 'Y', 'N', null, null, 'AFG');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (2, 'AL', 'Albania', 'EMEA', 'Y', 'N', null, null, 'ALB');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (3, 'DZ', 'Algeria', 'EMEA', 'Y', 'N', 28.0505583782702, 2.65803648781882, 'DZA');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (4, 'AS', 'American Samoa', 'Asia Pacific', 'Y', 'N', null, null, 'ASM');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (5, 'AD', 'Andorra', 'EMEA', 'Y', 'N', null, null, 'AND');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (6, 'AO', 'Angola', 'EMEA', 'Y', 'N', null, null, 'AGO');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (7, 'AG', 'Antigua and Barbuda', 'North America', 'Y', 'N', null, null, 'ATG');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (8, 'AR', 'Argentina', 'South America', 'Y', 'N', -34.749827181579, -64.7396264761603, 'ARG');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (9, 'AM', 'Armenia', 'EMEA', 'Y', 'N', 40.2860257920532, 44.9406270034667, 'ARM');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (10, 'AW', 'Aruba', 'North America', 'Y', 'N', null, null, 'ABW');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (11, 'AU', 'Australia', 'Asia Pacific', 'Y', 'N', -25.9525329514233, 134.471201485241, 'AUS');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (12, 'AT', 'Austria', 'EMEA', 'Y', 'Y', 47.5925608197967, 14.1144710431191, 'AUT');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (13, 'AZ', 'Azerbaijan', 'EMEA', 'Y', 'N', 40.2876406168275, 47.5438209362441, 'AZE');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (14, 'BS', 'Bahamas', 'North America', 'Y', 'N', null, null, 'BHS');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (15, 'BH', 'Bahrain', 'EMEA', 'Y', 'N', 26.0526927146835, 50.5466383116253, 'BHR');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (16, 'BD', 'Bangladesh', 'Asia Pacific', 'Y', 'N', null, null, 'BGD');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (17, 'BB', 'Barbados', 'North America', 'Y', 'N', null, null, 'BRB');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (18, 'BY', 'Belarus', 'EMEA', 'Y', 'N', 53.5204591224913, 28.0164077627553, 'BLR');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (19, 'BE', 'Belgium', 'EMEA', 'Y', 'N', 50.636807234233, 4.64712606207158, 'BEL');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (20, 'BZ', 'Belize', 'North America', 'Y', 'N', null, null, 'BLZ');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (21, 'BJ', 'Benin', 'EMEA', 'Y', 'N', null, null, 'BEN');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (22, 'BM', 'Bermuda', 'North America', 'Y', 'N', null, null, 'BMU');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (23, 'BT', 'Bhutan', 'Asia Pacific', 'Y', 'N', null, null, 'BTN');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (24, 'BO', 'Bolivia', 'South America', 'Y', 'N', null, null, 'BOL');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (25, 'BA', 'Bosnia and Herzegovina', 'EMEA', 'Y', 'N', 44.1687700204018, 17.7794261662736, 'BIH');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (26, 'BW', 'Botswana', 'EMEA', 'Y', 'N', null, null, 'BWA');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (27, 'BR', 'Brazil', 'South America', 'Y', 'N', -10.7897128871259, -53.0625058302629, 'BRA');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (28, 'BN', 'Brunei Darussalam', 'Asia Pacific', 'Y', 'N', null, null, 'BRN');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (29, 'BG', 'Bulgaria', 'EMEA', 'Y', 'N', 42.7710163382631, 25.2111454916013, 'BGR');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (30, 'BF', 'Burkina Faso', 'EMEA', 'Y', 'N', null, null, 'BFA');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (31, 'BI', 'Burundi', 'EMEA', 'Y', 'N', null, null, 'BDI');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (32, 'KH', 'Cambodia', 'Asia Pacific', 'Y', 'N', null, null, 'KHM');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (33, 'CM', 'Cameroon', 'EMEA', 'Y', 'N', null, null, 'CMR');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (34, 'CA', 'Canada', 'North America', 'Y', 'N', 60.545577443515, -96.2833441420418, 'CAN');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (35, 'IC', 'Canary Islands', 'EMEA', 'Y', 'N', null, null, '');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (36, 'CV', 'Cape Verde', 'North America', 'Y', 'N', null, null, 'CPV');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (37, 'KY', 'Cayman Islands', 'EMEA', 'Y', 'N', null, null, 'CYM');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (38, 'CF', 'Central African Republic', 'EMEA', 'Y', 'N', null, null, 'CAF');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (39, 'TD', 'Chad', 'EMEA', 'Y', 'N', null, null, 'TCD');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (40, 'CL', 'Chile', 'South America', 'Y', 'N', -36.3436063353845, -71.3772836093728, 'CHL');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (41, 'CN', 'China', 'Asia Pacific', 'Y', 'N', 36.6777277688864, 103.2272858186, 'CHN');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (42, 'CO', 'Colombia', 'South America', 'Y', 'N', 3.90406268648937, -73.0865398553309, 'COL');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (43, 'KM', 'Comoros', 'EMEA', 'Y', 'N', null, null, 'COM');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (44, 'CG', 'Congo', 'EMEA', 'Y', 'N', null, null, 'COG');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (45, 'CR', 'Costa Rica', 'South America', 'Y', 'N', 9.97274931092909, -84.1915245024165, 'CRI');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (46, 'HR', 'Croatia', 'EMEA', 'Y', 'N', 45.0629969941661, 16.3952369947082, 'HRV');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (47, 'CY', 'Cyprus', 'EMEA', 'Y', 'N', 34.9156521226288, 32.9898847263562, 'CYP');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (48, 'CZ', 'Czech Republic', 'EMEA', 'Y', 'N', 49.7371317390253, 15.3210867930983, 'CZE');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (49, 'CD', 'Democratic Republic of the Congo', 'EMEA', 'Y', 'N', null, null, 'COD');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (50, 'DK', 'Denmark', 'EMEA', 'Y', 'N', 55.9589501119306, 10.0681059452285, 'DNK');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (51, 'DJ', 'Djibouti', 'EMEA', 'Y', 'N', null, null, 'DJI');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (52, 'DM', 'Dominica', 'North America', 'Y', 'N', null, null, 'DMA');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (53, 'DO', 'Dominican Republic', 'South America', 'Y', 'N', null, null, 'DOM');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (54, 'EC', 'Ecuador', 'South America', 'Y', 'N', null, null, 'ECU');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (55, 'EG', 'Egypt', 'EMEA', 'Y', 'N', 26.459388687411, 29.8800800216717, 'EGY');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (56, 'SV', 'El Salvador', 'North America', 'Y', 'N', null, null, 'SLV');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (57, 'GQ', 'Equatorial Guinea', 'EMEA', 'Y', 'N', null, null, 'GNQ');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (58, 'EE', 'Estonia', 'EMEA', 'Y', 'N', 58.6720576799641, 25.5383130586335, 'EST');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (59, 'ET', 'Ethiopia', 'EMEA', 'Y', 'N', null, null, 'ETH');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (60, 'FO', 'Faroe Islands', 'EMEA', 'Y', 'N', null, null, 'FRO');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (61, 'FJ', 'Fiji', 'Asia Pacific', 'Y', 'N', null, null, 'FJI');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (62, 'FI', 'Finland', 'EMEA', 'Y', 'N', 64.2542670593351, 26.1908156200691, 'FIN');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (63, 'FR', 'France', 'EMEA', 'Y', 'N', 46.3, 2.35, 'FRA');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (64, 'GF', 'French Guiana', 'South America', 'Y', 'N', null, null, 'GUF');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (65, 'PF', 'French Polynesia', 'Asia Pacific', 'Y', 'N', null, null, 'PYF');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (66, 'GA', 'Gabon', 'EMEA', 'Y', 'N', null, null, 'GAB');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (67, 'GM', 'Gambia', 'EMEA', 'Y', 'N', null, null, 'GMB');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (68, 'GE', 'Georgia', 'EMEA', 'Y', 'N', null, null, 'GEO');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (69, 'DE', 'Germany', 'EMEA', 'Y', 'Y', 51.0515299009581, 10.3623688098981, 'DEU');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (70, 'GH', 'Ghana', 'EMEA', 'Y', 'N', 7.9484206013734, -1.21654631168427, 'GHA');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (71, 'GI', 'Gibraltar', 'EMEA', 'Y', 'N', null, null, 'GIB');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (72, 'GR', 'Greece', 'EMEA', 'Y', 'N', 39.0249771332278, 22.9853392654736, 'GRC');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (73, 'GL', 'Greenland', 'EMEA', 'Y', 'N', null, null, 'GRL');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (74, 'GD', 'Grenada', 'North America', 'Y', 'N', null, null, 'GRD');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (75, 'GP', 'Guadeloupe', 'North America', 'Y', 'N', null, null, 'GLP');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (76, 'GT', 'Guatemala', 'North America', 'Y', 'N', null, null, 'GTM');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (77, 'GG', 'Guernsey', 'EMEA', 'Y', 'N', null, null, 'GGY');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (78, 'GN', 'Guinea', 'EMEA', 'Y', 'N', null, null, 'GIN');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (79, 'GW', 'Guinea Bissau', 'EMEA', 'Y', 'N', null, null, 'GNB');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (80, 'GY', 'Guyana', 'South America', 'Y', 'N', null, null, 'GUY');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (81, 'HT', 'Haiti', 'North America', 'Y', 'N', null, null, 'HTI');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (82, 'HN', 'Honduras', 'North America', 'Y', 'N', null, null, 'HND');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (83, 'HK', 'Hong Kong', 'Asia Pacific', 'Y', 'N', 22.3840226008677, 114.131830902761, 'HKG');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (84, 'HU', 'Hungary', 'EMEA', 'Y', 'N', 47.1665440842287, 19.3805755323318, 'HUN');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (85, 'IS', 'Iceland', 'EMEA', 'Y', 'N', null, null, 'ISL');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (86, 'IN', 'India', 'Asia Pacific', 'Y', 'Y', 22.7617383835867, 79.6047525485952, 'IND');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (87, 'ID', 'Indonesia', 'Asia Pacific', 'Y', 'N', -2.28016763022542, 117.159522844253, 'IDN');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (88, 'IQ', 'Iraq', 'EMEA', 'Y', 'N', null, null, 'IRQ');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (89, 'IE', 'Ireland', 'EMEA', 'Y', 'Y', 53.1655400036239, -8.15269941873606, 'IRL');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (90, 'IM', 'Isle of Man', 'EMEA', 'Y', 'N', null, null, 'IMN');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (91, 'IL', 'Israel', 'EMEA', 'Y', 'N', 31.4345676456433, 34.9919400131368, 'ISR');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (92, 'IT', 'Italy', 'EMEA', 'Y', 'N', 42.7035691994324, 12.2036276805693, 'ITA');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (93, 'CI', 'Ivory Coast', 'EMEA', 'Y', 'N', 7.62550282092241, -5.56889039182287, 'CIV');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (94, 'JM', 'Jamaica', 'North America', 'Y', 'N', null, null, 'JAM');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (95, 'JP', 'Japan', 'Japan', 'Y', 'N', 37.3854017876606, 137.598609181384, 'JPN');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (96, 'JE', 'Jersey', 'EMEA', 'Y', 'N', null, null, 'JEY');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (97, 'JO', 'Jordan', 'EMEA', 'Y', 'N', 31.2387907978558, 36.757422903456, 'JOR');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (98, 'KZ', 'Kazakhstan', 'EMEA', 'Y', 'N', 48.3741037629595, 67.2739888798585, 'KAZ');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (99, 'KE', 'Kenya', 'EMEA', 'Y', 'N', .549356244899326, 37.8228067783801, 'KEN');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (100, 'KR', 'Korea', 'Asia Pacific', 'Y', 'N', 36.3615090498173, 127.814668142768, 'KOR');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (101, 'KW', 'Kuwait', 'EMEA', 'Y', 'N', 29.3390585728182, 47.5953428640136, 'KWT');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (102, 'KG', 'Kyrgyzstan', 'EMEA', 'Y', 'N', null, null, 'KGZ');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (103, 'LA', 'Laos', 'Asia Pacific', 'Y', 'N', null, null, 'LAO');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (104, 'LV', 'Latvia', 'EMEA', 'Y', 'N', 56.8605748612679, 24.9167110690882, 'LVA');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (105, 'LB', 'Lebanon', 'EMEA', 'Y', 'N', 33.9189311218277, 35.8775083865965, 'LBN');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (106, 'LS', 'Lesotho', 'EMEA', 'Y', 'N', null, null, 'LSO');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (107, 'LR', 'Liberia', 'EMEA', 'Y', 'N', null, null, 'LBR');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (108, 'LY', 'Libyan Arab Jamahiriya', 'EMEA', 'Y', 'N', 27.0173636214085, 18.0652845251555, 'LBY');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (109, 'LI', 'Liechtenstein', 'EMEA', 'Y', 'N', null, null, 'LIE');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (110, 'LT', 'Lithuania', 'EMEA', 'Y', 'N', 55.3247451169032, 23.8980884988308, 'LTU');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (111, 'LU', 'Luxembourg', 'EMEA', 'Y', 'N', 49.7663570584619, 6.0720991960439, 'LUX');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (112, 'MO', 'Macau', 'Asia Pacific', 'Y', 'N', 22.1604025427249, 113.555599557989, 'MAC');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (113, 'MK', 'Macedonia', 'EMEA', 'Y', 'N', null, null, 'MKD');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (114, 'MG', 'Madagascar', 'EMEA', 'Y', 'N', null, null, 'MDG');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (115, 'MW', 'Malawi', 'EMEA', 'Y', 'N', null, null, 'MWI');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (116, 'MY', 'Malaysia', 'Asia Pacific', 'Y', 'N', 3.81262745268228, 109.704476286832, 'MYS');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (117, 'MV', 'Maldives', 'Asia Pacific', 'Y', 'N', null, null, 'MDV');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (118, 'ML', 'Mali', 'EMEA', 'Y', 'N', null, null, 'MLI');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (119, 'MT', 'Malta', 'EMEA', 'Y', 'N', null, null, 'MLT');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (120, 'MQ', 'Martinique', 'North America', 'Y', 'N', null, null, 'MTQ');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (121, 'MR', 'Mauritania', 'EMEA', 'Y', 'N', null, null, 'MRT');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (122, 'MU', 'Mauritius', 'EMEA', 'Y', 'N', -20.1857973956282, 57.850751797212, 'MUS');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (123, 'MX', 'Mexico', 'North America', 'Y', 'Y', 23.934601892696, -102.188323856767, 'MEX');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (124, 'MC', 'Monaco', 'EMEA', 'Y', 'N', null, null, 'MCO');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (125, 'MN', 'Mongolia', 'Asia Pacific', 'Y', 'N', null, null, 'MNG');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (126, 'ME', 'Montenegro', 'EMEA', 'Y', 'N', null, null, 'MNE');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (127, 'MA', 'Morocco', 'EMEA', 'Y', 'N', 29.7737368231434, -8.66420532956332, 'MAR');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (128, 'MZ', 'Mozambique', 'EMEA', 'Y', 'N', null, null, 'MOZ');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (129, 'MM', 'Myanmar', 'Asia Pacific', 'Y', 'N', null, null, 'MMR');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (130, 'NA', 'Namibia', 'EMEA', 'Y', 'N', null, null, 'NAM');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (131, 'NP', 'Nepal', 'Asia Pacific', 'Y', 'N', null, null, 'NPL');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (132, 'NL', 'Netherlands', 'EMEA', 'Y', 'N', 52.199145001095, 4.5803419830938, 'NLD');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (133, 'AN', 'Netherlands Antilles', 'North America', 'Y', 'N', null, null, '');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (134, 'NC', 'New Caledonia', 'Asia Pacific', 'Y', 'N', null, null, 'NCL');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (135, 'NZ', 'New Zealand', 'Asia Pacific', 'Y', 'N', -41.6542404444822, 172.961752075767, 'NZL');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (136, 'NI', 'Nicaragua', 'North America', 'Y', 'N', null, null, 'NIC');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (137, 'NE', 'Niger', 'EMEA', 'Y', 'N', null, null, 'NER');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (138, 'NG', 'Nigeria', 'EMEA', 'Y', 'N', 9.59100569493586, 8.08315743469892, 'NGA');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (139, 'KP', 'North Korea', 'Asia Pacific', 'Y', 'N', null, null, 'PRK');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (140, 'NO', 'Norway', 'EMEA', 'Y', 'N', 64.7745889670849, 12.1397373014976, 'NOR');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (141, 'OM', 'Oman', 'EMEA', 'Y', 'N', 20.585156386594, 56.0643275591226, 'OMN');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (142, 'PK', 'Pakistan', 'Asia Pacific', 'Y', 'N', 29.8848480415832, 69.1722252971392, 'PAK');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (143, 'PS', 'Palestine', 'EMEA', 'Y', 'N', null, null, 'PSE');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (144, 'PA', 'Panama', 'North America', 'Y', 'N', null, null, 'PAN');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (145, 'PG', 'Papua New Guinea', 'Asia Pacific', 'Y', 'N', null, null, 'PNG');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (146, 'PY', 'Paraguay', 'South America', 'Y', 'N', null, null, 'PRY');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (147, 'PE', 'Peru', 'South America', 'Y', 'N', -9.10985299364425, -74.4211662037691, 'PER');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (148, 'PH', 'Philippines', 'Asia Pacific', 'Y', 'N', 11.7253180109993, 122.903980724002, 'PHL');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (149, 'PL', 'Poland', 'EMEA', 'Y', 'N', 52.1100009466317, 19.4252217465339, 'POL');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (150, 'PT', 'Portugal', 'EMEA', 'Y', 'N', 39.5996085377487, -8.63556904373474, 'PRT');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (151, 'PR', 'Puerto Rico', 'North America', 'Y', 'N', 18.2242458704844, -66.4676018452658, 'PRI');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (152, 'QA', 'Qatar', 'EMEA', 'Y', 'N', 25.3119459175758, 51.1866764830129, 'QAT');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (153, 'RE', 'Reunion', 'EMEA', 'Y', 'N', null, null, 'REU');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (154, 'RO', 'Romania', 'EMEA', 'Y', 'N', 45.849980567324, 24.9831513397535, 'ROU');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (155, 'RU', 'Russia', 'EMEA', 'Y', 'N', 66.296506322509, 95.8772843432938, 'RUS');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (156, 'RW', 'Rwanda', 'EMEA', 'Y', 'N', null, null, 'RWA');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (157, 'ST', 'Sao Tome and Principe', 'EMEA', 'Y', 'N', null, null, 'STP');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (158, 'SA', 'Saudi Arabia', 'EMEA', 'Y', 'N', 24.0911030338015, 44.666975315864, 'SAU');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (159, 'SN', 'Senegal', 'EMEA', 'Y', 'N', 14.3667239515782, -14.4673427052342, 'SEN');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (160, 'RS', 'Serbia', 'EMEA', 'Y', 'N', 44.2114387597226, 20.8073008517722, 'SRB');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (161, 'SC', 'Seychelles', 'EMEA', 'Y', 'N', null, null, 'SYC');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (162, 'SL', 'Sierra Leone', 'EMEA', 'Y', 'N', null, null, 'SLE');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (163, 'SG', 'Singapore', 'Asia Pacific', 'Y', 'N', 1.35892187535271, 103.81346764985, 'SGP');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (164, 'SK', 'Slovakia', 'EMEA', 'Y', 'N', 48.7108056163336, 19.4703672420141, 'SVK');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (165, 'SI', 'Slovenia', 'EMEA', 'Y', 'N', 46.1164702078935, 14.8041784046189, 'SVN');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (166, 'SO', 'Somalia', 'EMEA', 'Y', 'N', null, null, 'SOM');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (167, 'ZA', 'South Africa', 'EMEA', 'Y', 'N', -29.0109136114449, 25.1997255202127, 'ZAF');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (168, 'ES', 'Spain', 'EMEA', 'Y', 'N', 40.1816336827982, -3.72112968155382, 'ESP');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (169, 'LK', 'Sri Lanka', 'Asia Pacific', 'Y', 'N', 7.61439796471554, 80.7037303531036, 'LKA');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (170, 'SR', 'Suriname', 'South America', 'Y', 'N', null, null, 'SUR');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (171, 'SZ', 'Swaziland', 'EMEA', 'Y', 'N', null, null, 'SWZ');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (172, 'SE', 'Sweden', 'EMEA', 'Y', 'N', 62.3829414476636, 16.2787691655521, 'SWE');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (173, 'CH', 'Switzerland', 'EMEA', 'Y', 'N', 46.7999696363917, 8.21287295709836, 'CHE');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (174, 'TW', 'Taiwan', 'Asia Pacific', 'Y', 'N', 23.7492728197723, 120.947106156346, 'TWN');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (175, 'TJ', 'Tajikistan', 'EMEA', 'Y', 'N', null, null, 'TJK');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (176, 'TZ', 'Tanzania', 'EMEA', 'Y', 'N', null, null, 'TZA');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (177, 'TH', 'Thailand', 'Asia Pacific', 'Y', 'N', 15.0746782265949, 101.002713288589, 'THA');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (178, 'TL', 'Timor Leste', 'Asia Pacific', 'Y', 'N', null, null, 'TLS');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (179, 'TG', 'Togo', 'EMEA', 'Y', 'N', null, null, 'TGO');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (180, 'TT', 'Trinidad and Tobago', 'North America', 'Y', 'N', null, null, 'TTO');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (181, 'TN', 'Tunisia', 'EMEA', 'Y', 'N', null, null, 'TUN');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (182, 'TR', 'Turkey', 'EMEA', 'Y', 'N', 39.137265788256, 35.1717503083775, 'TUR');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (183, 'UG', 'Uganda', 'EMEA', 'Y', 'N', null, null, 'UGA');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (184, 'UA', 'Ukraine', 'EMEA', 'Y', 'N', 49.0232495291592, 31.4648092208537, 'UKR');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (185, 'AE', 'United Arab Emirates', 'EMEA', 'Y', 'N', 23.9060109963645, 54.2933528390184, 'ARE');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (186, 'GB', 'United Kingdom', 'EMEA', 'Y', 'Y', 54.0387673071189, -2.78272189148275, 'GBR');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (187, 'US', 'United States', 'North America', 'Y', 'Y', 37.1, -95.7, 'USA');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (188, 'UY', 'Uruguay', 'South America', 'Y', 'N', null, null, 'URY');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (189, 'UZ', 'Uzbekistan', 'EMEA', 'Y', 'N', null, null, 'UZB');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (190, 'VE', 'Venezuela', 'South America', 'Y', 'N', 7.13090263242316, -66.1594861155562, 'VEN');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (191, 'VN', 'Vietnam', 'Asia Pacific', 'Y', 'N', 16.5394021305517, 106.347176042478, 'VNM');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (192, 'VG', 'Virgin Islands, British', 'North America', 'Y', 'N', null, null, 'VGB');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (193, 'VI', 'Virgin Islands, U.S.', 'North America', 'Y', 'N', null, null, 'VIR');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (194, 'EH', 'Western Sahara', 'EMEA', 'Y', 'N', null, null, 'ESH');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (195, 'YE', 'Yemen', 'EMEA', 'Y', 'N', null, null, 'YEM');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (196, 'ZR', 'Zaire', 'EMEA', 'Y', 'N', null, null, '');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (197, 'ZM', 'Zambia', 'EMEA', 'Y', 'N', null, null, 'ZMB');

-- source: install_seed_countries.sql (p_sequence 770, seed countries)
insert into SP_COUNTRIES (ID, COUNTRY_CODE, COUNTRY_NAME, REGION, DISPLAY_YN, QUICK_PICK_YN, LAT, LON, COUNTRY_CODE3) values (198, 'ZW', 'Zimbabwe', 'EMEA', 'Y', 'N', null, null, 'ZWE');

-- source: install_seed_nomenclature.sql (p_sequence 780, seed nomenclature)
insert into SP_APP_NOMENCLATURE (static_ID, default_order, default_value) values ('STRATEGIC_PLANNER', 1, 'Our Strategic Planner');

-- source: install_seed_nomenclature.sql (p_sequence 780, seed nomenclature)
insert into SP_APP_NOMENCLATURE (static_ID, default_order, default_value) values ('AREA', 2, 'Area');

-- source: install_seed_nomenclature.sql (p_sequence 780, seed nomenclature)
insert into SP_APP_NOMENCLATURE (static_ID, default_order, default_value) values ('AREAS', 3, 'Areas');

-- source: install_seed_nomenclature.sql (p_sequence 780, seed nomenclature)
insert into SP_APP_NOMENCLATURE (static_ID, default_order, default_value) values ('INITIATIVE', 4, 'Initiative');

-- source: install_seed_nomenclature.sql (p_sequence 780, seed nomenclature)
insert into SP_APP_NOMENCLATURE (static_ID, default_order, default_value) values ('INITIATIVES', 5, 'Initiatives');

-- source: install_seed_nomenclature.sql (p_sequence 780, seed nomenclature)
insert into SP_APP_NOMENCLATURE (static_ID, default_order, default_value) values ('PROJECT', 6, 'Project');

-- source: install_seed_nomenclature.sql (p_sequence 780, seed nomenclature)
insert into SP_APP_NOMENCLATURE (static_ID, default_order, default_value) values ('PROJECTS', 7, 'Projects');

-- source: install_seed_nomenclature.sql (p_sequence 780, seed nomenclature)
insert into SP_APP_NOMENCLATURE (static_ID, default_order, default_value) values ('USER', 10, 'Person');

-- source: install_seed_nomenclature.sql (p_sequence 780, seed nomenclature)
insert into SP_APP_NOMENCLATURE (static_ID, default_order, default_value) values ('USERS', 11, 'People');

-- source: install_seed_external_ticketing_systems.sql (p_sequence 790, seed external_ticketing_systems)
insert into SP_EXTERNAL_TICKETING_SYSTEMS 
    ( ID, EVAULATION_SEQUENCE, EXTERNAL_SYSTEM_NAME, IS_ACTIVE_YN, LINK_PATTERN, description, TICKET_ID_REGEX) 
    values 
    (1, 10, 'Jira', 'Y', 'https://jira.myorg.com/jira/browse/#TICKET#', 'Our Jira', '[Jj][Ii][Rr][Aa][-: ]\d{3,5}');

-- source: install_seed_resource_types.sql (p_sequence 800, seed resource types)
insert into SP_RESOURCE_TYPES (ID, RESOURCE_TYPE, RESOURCE_DESCRIPTION, IS_DEFAULT_YN) values (1, 'Main Developer', 'Developer most responsible for the implementation, actual coding, of the project. The main developer typically contributes the most code and coordinates other developer contributions.', 'N');

-- source: install_seed_resource_types.sql (p_sequence 800, seed resource types)
insert into SP_RESOURCE_TYPES (ID, RESOURCE_TYPE, RESOURCE_DESCRIPTION, IS_DEFAULT_YN) values (3, 'Project Manager', 'Develops, maintains, and revises proposals for assigned projects including project objectives, technologies, systems, information specifications, timelines, funding, and staffing. Sets and tracks project milestones; manages and accounts for unforeseen delays, then realigns schedules and expectations as needed.', 'N');

-- source: install_seed_resource_types.sql (p_sequence 800, seed resource types)
insert into SP_RESOURCE_TYPES (ID, RESOURCE_TYPE, RESOURCE_DESCRIPTION, IS_DEFAULT_YN) values (4, 'Requestor', 'The customer or the person who is asking for the feature or capability. The project is being performed at the request of this person.', 'N');

-- source: install_seed_resource_types.sql (p_sequence 800, seed resource types)
insert into SP_RESOURCE_TYPES (ID, RESOURCE_TYPE, RESOURCE_DESCRIPTION, IS_DEFAULT_YN) values (2, 'Architect', 'A software architect is a computer programmer who makes project-specific software design choices, coordinates technical teams and selects and enforces technical coding standards when creating new programs or software to fulfill business goals.', 'N');

-- source: install_seed_resource_types.sql (p_sequence 800, seed resource types)
insert into SP_RESOURCE_TYPES (ID, RESOURCE_TYPE, RESOURCE_DESCRIPTION, IS_DEFAULT_YN) values (5, 'Functional Tester', 'A functional tester is someone who measures and monitors progress during each test to ensure that the application is tested, validated, and piloted on time and within budget, and that it meets or exceeds expectations. Review test, validation, and pilot results to ensure that they meet the entry and exit criteria.', 'N');

-- source: install_seed_resource_types.sql (p_sequence 800, seed resource types)
insert into SP_RESOURCE_TYPES (ID, RESOURCE_TYPE, RESOURCE_DESCRIPTION, IS_DEFAULT_YN) values (6, 'Contributing Developer', 'A developer who is not the main developer but is contributing to the development process for a specific project.', 'N');

-- source: install_seed_resource_types.sql (p_sequence 800, seed resource types)
insert into SP_RESOURCE_TYPES (ID, RESOURCE_TYPE, RESOURCE_DESCRIPTION, IS_DEFAULT_YN) values (7, 'Researcher', 'The Research Software Engineer works with researchers to gain an understanding of the problems they face, and then develops, maintains and extends software to provide the answers.', 'N');

-- source: install_seed_resource_types.sql (p_sequence 800, seed resource types)
insert into SP_RESOURCE_TYPES (ID, RESOURCE_TYPE, RESOURCE_DESCRIPTION, IS_DEFAULT_YN) values (8, 'UI Designer', 'A user interface designer, UI designer, is someone who designs the graphical user interface of an app, website, or device that a human interacts with. For example, when you access a website or an app on your phone, there''s usually a graphical interface that allows you to navigate and achieve your goal.', 'N');

-- source: install_seed_project_scales.sql (p_sequence 810, seed project scales)
insert into sp_project_scales (scale_letter, scale_name, is_active_yn, min_pc_for_status,
                               pc0_label, pc0_desc, pc10_label, pc10_desc,
                               pc20_label, pc20_desc, pc30_label, pc30_desc,
                               pc40_label, pc40_desc, pc50_label, pc50_desc,
                               pc60_label, pc60_desc, pc70_label, pc70_desc,
                               pc80_label, pc80_desc, pc90_label, pc90_desc,
                               pc100_label, pc100_desc) 
                       values ('A', 'Product Dev','Y', 30,
                               'Not Feasible', 'Project is not possible or not desirable or is a duplicate',
                               'Identified', 'A new project has been identified and formally proposed',
                               'Desirable', 'Project is determined to be worthy of consideration and is perceived as desirable',
                               'Architecting', 'The implementation specification is under development',
                               'Specification Approved', 'The specification is sufficiently complete to begin development and has been formally reviewed',
                               'Active Development', 'Project is assigned and currently in active development',
                               'Demonstrable', 'Project is partially functioning',
                               'In Review', 'Project is merged into the mainline',
                               'Merging', 'Merging to the mainline',
                               'Verification', 'Project has passed all testing and reviews and is ready for distribution',
                               'Complete', 'Project is complete and made generally available');

-- source: install_seed_project_scales.sql (p_sequence 810, seed project scales)
insert into sp_project_scales (scale_letter, scale_name, is_active_yn, min_pc_for_status,
                               pc0_label, pc0_desc, pc10_label, pc10_desc,
                               pc20_label, pc20_desc, pc30_label, pc30_desc,
                               pc40_label, pc40_desc, pc50_label, pc50_desc,
                               pc60_label, pc60_desc, pc70_label, pc70_desc,
                               pc80_label, pc80_desc, pc90_label, pc90_desc,
                               pc100_label, pc100_desc) 
                       values ('B', 'Generic','Y', 30,
                               'Canceled', 'Canceled and or abandoned',
                               'Identified', 'A new project has been identified',
                               'Desirable', 'Determined to be worthy of consideration and is perceived as desirable',
                               'Planning has started', 'Planning has started. Most of the variables required for planning are known',
                               'Planning mostly complete', 'Planning is mostly complete',
                               'Progressing - half done', 'Progressing and about half complete',
                               'Progressing', 'Progressing',
                               'Progressing', 'Progressing',
                               'Progressing', 'Progressing well and getting close to complete',
                               'Substantially Complete', 'Project is virtually complete with only small inconsequential issues outstanding.',
                               'Complete', 'Project is complete');

-- source: install_seed_project_scales.sql (p_sequence 810, seed project scales)
insert into sp_project_scales (scale_letter, scale_name, is_active_yn, min_pc_for_status,
                               pc0_label, pc0_desc, pc10_label, pc10_desc,
                               pc20_label, pc20_desc, pc30_label, pc30_desc,
                               pc40_label, pc40_desc, pc50_label, pc50_desc,
                               pc60_label, pc60_desc, pc70_label, pc70_desc,
                               pc80_label, pc80_desc, pc90_label, pc90_desc,
                               pc100_label, pc100_desc) 
                       values ('C', 'Sales Engagement','Y', 20,
                               'Lost Opportunity', 'This opportunity has been lost',
                               'Lead Identified', 'A lead with a customer has been identified',
                               'Connected with Lead', 'A connection has been made with customer',
                               'Qualifying Opportunity', 'The opportunity is being qualified to see if it is a good fit',
                               'Presented to Customer', 'A presentation has been performed for the customer',
                               'Requirements Understood', 'Customer requirements are well understood',
                               'Solution Proposed', 'A solution has been proposed',
                               'Objections Addressed', 'Any objections to the proposed implementation have been addressed',
                               'Proposal Drafted', 'A solution proposal has been drafted for internal review',
                               'Proposal Delivered', 'The proposal has been delivered to the customer',
                               'Win', 'Opportunity has been won and the customer has formally accepted the proposal');

-- source: install_seed_project_scales.sql (p_sequence 810, seed project scales)
insert into sp_project_scales (scale_letter, scale_name, is_active_yn, min_pc_for_status,
                               pc0_label, pc0_desc, pc10_label, pc10_desc,
                               pc20_label, pc20_desc, pc30_label, pc30_desc,
                               pc40_label, pc40_desc, pc50_label, pc50_desc,
                               pc60_label, pc60_desc, pc70_label, pc70_desc,
                               pc80_label, pc80_desc, pc90_label, pc90_desc,
                               pc100_label, pc100_desc) 
                       values ('D', 'Project Mgt','Y', 30,
                               'Not Feasible', 'Project is not possible or not desirable or is a duplicate',
                               'Identified', 'A new project has been identified and formally proposed',
                               'Desirable', 'Project is determined to be worthy of consideration and is perceived as desirable',
                               'Architecting', 'The implementation specification is under development',
                               'Specification Approved', 'The specification is sufficiently complete to begin development and has been formally reviewed',
                               'Active Development', 'Project is assigned and currently in active development',
                               'Demonstrable', 'Project is partially functioning',
                               'In Review', 'Project is merged into the mainline',
                               'Merging', 'Merging to the mainline',
                               'Verification', 'Project has passed all testing and reviews and is ready for distribution',
                               'Complete', 'Project is complete and made generally available');

-- source: install_seed_project_scales.sql (p_sequence 810, seed project scales)
insert into sp_project_scales (scale_letter, scale_name, is_active_yn, min_pc_for_status,
                               pc0_label, pc0_desc, pc10_label, pc10_desc,
                               pc20_label, pc20_desc, pc30_label, pc30_desc,
                               pc40_label, pc40_desc, pc50_label, pc50_desc,
                               pc60_label, pc60_desc, pc70_label, pc70_desc,
                               pc80_label, pc80_desc, pc90_label, pc90_desc,
                               pc100_label, pc100_desc) 
                       values ('E', 'Sample App','Y', 30,
                               'Not Feasible', 'Project is not possible or not desirable or is a duplicate',
                               'Identified', 'A new project has been identified and formally proposed',
                               'Desirable', 'Project is determined to be worthy of consideration and is perceived as desirable',
                               'Architecting', 'The implementation specification is under development',
                               'Specification Approved', 'The specification is sufficiently complete to begin development and has been formally reviewed',
                               'Active Development', 'Project is assigned and currently in active development',
                               'Demonstrable', 'Project is partially functioning',
                               'In Review', 'Project is being reviewed',
                               'Documented', 'Sample App or Code has been documented',
                               'Verification', 'Project has passed all testing and reviews and is ready for distribution',
                               'Hosted', 'Sample App or Code is hosted and available for download');

-- source: install_seed_project_statuses.sql (p_sequence 815, seed project statuses)
insert into sp_project_statuses (ID, STATUS, STATIC_ID, INCLUDE_YN, DISPLAY_SEQ) 
    values (1, 'On Track', 'ON-TRACK', 'Y', 1);

-- source: install_seed_project_statuses.sql (p_sequence 815, seed project statuses)
insert into sp_project_statuses (ID, STATUS, STATIC_ID, INCLUDE_YN, DISPLAY_SEQ) 
    values (2, 'At Risk', 'AT-RISK', 'Y', 2);

-- source: install_seed_project_statuses.sql (p_sequence 815, seed project statuses)
insert into sp_project_statuses (ID, STATUS, STATIC_ID, INCLUDE_YN, DISPLAY_SEQ) 
    values (4, 'Paused', 'PAUSED', 'Y', 4);

-- source: install_seed_project_statuses.sql (p_sequence 815, seed project statuses)
insert into sp_project_statuses (ID, STATUS, STATIC_ID, INCLUDE_YN, DISPLAY_SEQ) 
    values (5, 'Blocked', 'BLOCKED', 'Y', 5);

-- source: install_seed_default_tags.sql (p_sequence 820, seed default tags)
insert into SP_DEFAULT_TAGS (ID, DISPLAY_SEQUENCE, TAG) values (1, 10, 'COMMITTED');

-- source: install_seed_default_tags.sql (p_sequence 820, seed default tags)
insert into SP_DEFAULT_TAGS (ID, DISPLAY_SEQUENCE, TAG) values (2, 20, 'MVP');

-- source: install_seed_default_tags.sql (p_sequence 820, seed default tags)
insert into SP_DEFAULT_TAGS (ID, DISPLAY_SEQUENCE, TAG) values (3, 30, 'URGENT');

-- source: install_seed_default_tags.sql (p_sequence 820, seed default tags)
insert into SP_DEFAULT_TAGS (ID, DISPLAY_SEQUENCE, TAG) values (4, 40, 'CUSTOMER FACING');

-- source: install_seed_default_tags.sql (p_sequence 820, seed default tags)
insert into SP_DEFAULT_TAGS (ID, DISPLAY_SEQUENCE, TAG) values (5, 50, 'NEEDS REVIEW');

-- source: install_seed_default_tags.sql (p_sequence 820, seed default tags)
insert into SP_DEFAULT_TAGS (ID, DISPLAY_SEQUENCE, TAG) values (6, 60, 'IMPORTANT');

-- source: install_seed_project_priorities.sql (p_sequence 830, seed project priorities)
insert into sp_project_priorities (id, priority, description, IS_DEFAULT_YN) values (1,1, 'P1 - Highest','N');

-- source: install_seed_project_priorities.sql (p_sequence 830, seed project priorities)
insert into sp_project_priorities (id, priority, description, IS_DEFAULT_YN) values (2,2, 'P2 - High (Critical)','N');

-- source: install_seed_project_priorities.sql (p_sequence 830, seed project priorities)
insert into sp_project_priorities (id, priority, description, IS_DEFAULT_YN) values (3,3, 'P3 - Medium','N');

-- source: install_seed_project_priorities.sql (p_sequence 830, seed project priorities)
insert into sp_project_priorities (id, priority, description, IS_DEFAULT_YN) values (4,4, 'P4 - Low','N');

-- source: install_seed_project_priorities.sql (p_sequence 830, seed project priorities)
insert into sp_project_priorities (id, priority, description, IS_DEFAULT_YN) values (5,5, 'P5 - Not Prioritized','Y');

-- source: install_seed_activity_types.sql (p_sequence 850, seed activity_types)
insert into SP_ACTIVITY_TYPES (ID, DISPLAY_SEQUENCE, ACTIVITY_TYPE, ACTIVITY_TYPE_DESCRIPTION, is_default_yn, static_id ) values ( 1, 1, 'Development', '', 'Y', 'DEV');

-- source: install_seed_activity_types.sql (p_sequence 850, seed activity_types)
insert into SP_ACTIVITY_TYPES (ID, DISPLAY_SEQUENCE, ACTIVITY_TYPE, ACTIVITY_TYPE_DESCRIPTION, is_default_yn, static_id ) values ( 2, 2, 'Prod Mgt', 'Product Management', 'N', 'PM');

-- source: install_seed_activity_types.sql (p_sequence 850, seed activity_types)
insert into SP_ACTIVITY_TYPES (ID, DISPLAY_SEQUENCE, ACTIVITY_TYPE, ACTIVITY_TYPE_DESCRIPTION, is_default_yn, static_id ) values ( 3, 3, 'Review', '', 'N', 'REVIEW');

-- source: install_seed_activity_types.sql (p_sequence 850, seed activity_types)
insert into SP_ACTIVITY_TYPES (ID, DISPLAY_SEQUENCE, ACTIVITY_TYPE, ACTIVITY_TYPE_DESCRIPTION, is_default_yn, static_id ) values ( 4, 4, 'Conference', 'Conference preparation, travel, attendance or other related work', 'N', 'CONF');

-- source: install_seed_activity_types.sql (p_sequence 850, seed activity_types)
insert into SP_ACTIVITY_TYPES (ID, DISPLAY_SEQUENCE, ACTIVITY_TYPE, ACTIVITY_TYPE_DESCRIPTION, is_default_yn, static_id ) values ( 5, 5, 'Customer Engagement', '', 'N', 'CUSTOMER');

-- source: install_seed_activity_types.sql (p_sequence 850, seed activity_types)
insert into SP_ACTIVITY_TYPES (ID, DISPLAY_SEQUENCE, ACTIVITY_TYPE, ACTIVITY_TYPE_DESCRIPTION, is_default_yn, static_id ) values ( 6, 6, 'Out of Office', '', 'N', 'OOO');

-- source: install_seed_release_milestone_types.sql (p_sequence 855, seed release_milestone_types)
insert into sp_release_milestone_types (id, milestone_type, display_seq)
    values (1, 'Build', 1);

-- source: install_seed_release_milestone_types.sql (p_sequence 855, seed release_milestone_types)
insert into sp_release_milestone_types (id, milestone_type, display_seq)
    values (2, 'Doc', 2);

-- source: install_seed_release_milestone_types.sql (p_sequence 855, seed release_milestone_types)
insert into sp_release_milestone_types (id, milestone_type, display_seq)
    values (3, 'Merge', 3);

-- source: install_seed_release_milestone_types.sql (p_sequence 855, seed release_milestone_types)
insert into sp_release_milestone_types (id, milestone_type, display_seq)
    values (4, 'Milestone', 4);

-- source: install_seed_release_milestone_types.sql (p_sequence 855, seed release_milestone_types)
insert into sp_release_milestone_types (id, milestone_type, display_seq)
    values (6, 'Translation Drop', 6);

-- source: install_seed_release_milestone_types.sql (p_sequence 855, seed release_milestone_types)
insert into sp_release_milestone_types (id, milestone_type, display_seq)
    values (7, 'Upgrade', 7);

-- source: install_seed_notifications.sql (p_sequence 870, seed notifications)
insert into SP_NOTIFICATIONS ( ID, name, static_id, description, is_active_YN ) 
    values (1, 'My Weekly Summary', 'WEEKLY_SUMMARY', 'Weekly user projects and activities summary.','Y');

-- source: install_seed_notifications.sql (p_sequence 870, seed notifications)
insert into SP_NOTIFICATIONS ( ID, name, static_id, description, is_active_YN ) 
    values (2, 'Release Exceptions', 'RELEASE_EXCEPTIONS', 'Weekly review of exceptions for a selected release.','Y');

-- source: install_seed_notifications.sql (p_sequence 870, seed notifications)
insert into SP_NOTIFICATIONS ( ID, name, static_id, description, is_active_YN ) 
    values (3, 'My Project Exceptions', 'PROJECT_EXCEPTIONS', 'Weekly report of exceptions within projects the user is associated with.','Y');

-- source: install_seed_notifications.sql (p_sequence 870, seed notifications)
insert into SP_NOTIFICATIONS ( ID, name, static_id, description, is_active_YN ) 
    values (4, 'My Project Changes', 'PROJECT_CHANGES', 'Report of changes to projects you own or have favorited.','Y');

-- source: install_seed_competencies.sql (p_sequence 880, seed competencies)
insert into SP_COMPETENCIES
    (ID, COMPETENCY, DESCRIPTION) 
    values 
    (1, 'JavaScript (Advanced)', '');

-- source: install_seed_competencies.sql (p_sequence 880, seed competencies)
insert into SP_COMPETENCIES
    (ID, COMPETENCY, DESCRIPTION) 
    values 
    (2, 'JavaScript (Intermediate)', '');

-- source: install_seed_competencies.sql (p_sequence 880, seed competencies)
insert into SP_COMPETENCIES
    (ID, COMPETENCY, DESCRIPTION) 
    values 
    (3, 'CSS (Advanced)', '');

-- source: install_seed_competencies.sql (p_sequence 880, seed competencies)
insert into SP_COMPETENCIES
    (ID, COMPETENCY, DESCRIPTION) 
    values 
    (4, 'PL/SQL (Advanced)', 'Demonstrated expertise in writing and optimizing advanced PL/SQL code, including complex stored procedures, functions, packages, and triggers. Strong performance tuning. Strong debugging skills.');

-- source: install_seed_competencies.sql (p_sequence 880, seed competencies)
insert into SP_COMPETENCIES
    (ID, COMPETENCY, DESCRIPTION) 
    values 
    (5, 'PL/SQL (Intermediate)', 'Ability to write efficient, complex queries and stored procedures. Demonstrates a solid understanding of PL/SQL programming constructs. Someone who is a profesional PL/SQL programmer whose code is used by others.');

-- source: install_seed_competencies.sql (p_sequence 880, seed competencies)
insert into SP_COMPETENCIES
    (ID, COMPETENCY, DESCRIPTION) 
    values 
    (6, 'APEX App Development (Advanced)', 'Comfortable building and deploying applications used by hundreds or thousands of people.');

-- source: install_seed_competencies.sql (p_sequence 880, seed competencies)
insert into SP_COMPETENCIES
    (ID, COMPETENCY, DESCRIPTION) 
    values 
    (7, 'Graphics Design', '');

-- source: install_seed_competencies.sql (p_sequence 880, seed competencies)
insert into SP_COMPETENCIES
    (ID, COMPETENCY, DESCRIPTION) 
    values 
    (8, 'Accessibility', '');

-- source: install_seed_competencies.sql (p_sequence 880, seed competencies)
insert into SP_COMPETENCIES
    (ID, COMPETENCY, DESCRIPTION) 
    values 
    (9, 'UI Design', '');

-- source: install_seed_competencies.sql (p_sequence 880, seed competencies)
insert into SP_COMPETENCIES
    (ID, COMPETENCY, DESCRIPTION) 
    values 
    (10, 'CSS (Intermediate)', 'A high level of proficiency and experience in front-end development. Ability to create responsive and adaptive designs that work across various devices and screen sizes.');

-- source: install_seed_competencies.sql (p_sequence 880, seed competencies)
insert into SP_COMPETENCIES
    (ID, COMPETENCY, DESCRIPTION) 
    values 
    (11, 'Database Design', '');

-- source: install_seed_competencies.sql (p_sequence 880, seed competencies)
insert into SP_COMPETENCIES
    (ID, COMPETENCY, DESCRIPTION) 
    values 
    (12, 'DevOps', 'Build tools, automations, etc.');

-- source: install_seed_competencies.sql (p_sequence 880, seed competencies)
insert into SP_COMPETENCIES
    (ID, COMPETENCY, DESCRIPTION) 
    values 
    (13, 'Performance Tuning', 'Comfortable performance tuning SQL and PL/SQL. Can get to the root of a performance problem.');

-- source: install_seed_competencies.sql (p_sequence 880, seed competencies)
insert into SP_COMPETENCIES
    (ID, COMPETENCY, DESCRIPTION) 
    values 
    (14, 'APEX App Development (Intermediate)', 'Comfortable building APEX applications with moderate complexity and quality UI and usability.');

-- source: install_seed_competencies.sql (p_sequence 880, seed competencies)
insert into SP_COMPETENCIES
    (ID, COMPETENCY, DESCRIPTION) 
    values 
    (15, 'Multimedia Production', 'Video, motion, and other multimedia production');

-- source: install_seed_competencies.sql (p_sequence 880, seed competencies)
insert into SP_COMPETENCIES
    (ID, COMPETENCY, DESCRIPTION) 
    values 
    (16, 'Product Management', '');

-- source: install_seed_competencies.sql (p_sequence 880, seed competencies)
insert into SP_COMPETENCIES
    (ID, COMPETENCY, DESCRIPTION) 
    values 
    (17, 'Testing', '');

-- source: install_seed_competencies.sql (p_sequence 880, seed competencies)
insert into SP_COMPETENCIES
    (ID, COMPETENCY, DESCRIPTION) 
    values 
    (18, 'Security', '');

-- source: install_seed_competencies.sql (p_sequence 880, seed competencies)
insert into SP_COMPETENCIES
    (ID, COMPETENCY, DESCRIPTION) 
    values 
    (19, 'SQL (Advanced)', 'Advanced SQL skills including strong understanding of performance and syntax. Goto person for SQL.');

-- source: install_seed_competencies.sql (p_sequence 880, seed competencies)
insert into SP_COMPETENCIES
    (ID, COMPETENCY, DESCRIPTION) 
    values 
    (20, 'Program Management', '');

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_types (ID, STATIC_ID, TASK_TYPE, DESCRIPTION, DISPLAY_SEQ) values (1, 'REVIEW', 'Review', 'Reviews', 10);

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_types (ID, STATIC_ID, TASK_TYPE, DESCRIPTION, DISPLAY_SEQ, PARENT_TYPE_ID) values (2, 'REVIEW-FUNCSPEC', 'Functional Spec Review', 'A review of the functional specification document', 11, 1);

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_types (ID, STATIC_ID, TASK_TYPE, DESCRIPTION, DISPLAY_SEQ, PARENT_TYPE_ID) values (3, 'REVIEW-SPEC', 'Spec Review', 'A review of the implementation designed to implement a functional specification document', 12, 1);

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_types (ID, STATIC_ID, TASK_TYPE, DESCRIPTION, DISPLAY_SEQ, PARENT_TYPE_ID) values (4, 'REVIEW-PEER', 'Peer Review', 'Review of the implementation by your fellow developer', 13, 1);

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_types (ID, STATIC_ID, TASK_TYPE, DESCRIPTION, DISPLAY_SEQ, PARENT_TYPE_ID) values (5, 'REVIEW-SECURITY', 'Security Review', 'Review of the security exposure, remediations, and risk of this implementation', 14, 1);

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_types (ID, STATIC_ID, TASK_TYPE, DESCRIPTION, DISPLAY_SEQ, PARENT_TYPE_ID) values (6, 'REVIEW-ACCESSIBILITY', 'Accessibility Review', 'Review web accessibility', 15, 1);

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_types (ID, STATIC_ID, TASK_TYPE, DESCRIPTION, DISPLAY_SEQ, PARENT_TYPE_ID) values (7, 'REVIEW-PM', 'Product Management Review', 'Project Management (PM) team review', 16, 1);

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_types (ID, STATIC_ID, TASK_TYPE, DESCRIPTION, DISPLAY_SEQ, PARENT_TYPE_ID) values (8, 'REVIEW-DOC', 'Documentation Review', 'Review of the documentation', 17, 1);

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_types (ID, STATIC_ID, TASK_TYPE, DESCRIPTION, DISPLAY_SEQ, PARENT_TYPE_ID) values (9, 'REVIEW-TESTING', 'Functional Testing Review', 'Review of the testing plan', 18, 1);

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_types (ID, STATIC_ID, TASK_TYPE, DESCRIPTION, DISPLAY_SEQ, PARENT_TYPE_ID) values (10, 'REVIEW-UX', 'User Experience Review', 'Review of end-user experience', 19, 1);

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_types (ID, STATIC_ID, TASK_TYPE, DESCRIPTION, DISPLAY_SEQ, PARENT_TYPE_ID) values (11, 'REVIEW-IMPLEMENTATION', 'Implementation Review', 'An implementation review is typically performed before merge', 20, 1);

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_types (ID, STATIC_ID, TASK_TYPE, DESCRIPTION, DISPLAY_SEQ, PARENT_TYPE_ID) values (12, 'REVIEW-OTHER', 'Other Review', 'A review that does not fall into any other category', 21, 1);

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_types (ID, STATIC_ID, TASK_TYPE, DESCRIPTION, DISPLAY_SEQ) values (20, 'MILESTONE', 'Milestone', 'Milestones', 1);

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_types (ID, STATIC_ID, TASK_TYPE, DESCRIPTION, DISPLAY_SEQ, PARENT_TYPE_ID) values (21, 'MILESTONE-SPEC', 'Spec', 'Specification is complete and ready for review', 2, 20);

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_types (ID, STATIC_ID, TASK_TYPE, DESCRIPTION, DISPLAY_SEQ, PARENT_TYPE_ID) values (22, 'MILESTONE-DEMO', 'Demonstration', 'Code has been successfully demonstrated', 3, 20);

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_types (ID, STATIC_ID, TASK_TYPE, DESCRIPTION, DISPLAY_SEQ, PARENT_TYPE_ID) values (23, 'MILESTONE-CODE', 'Code Complete', 'Code is complete', 4, 20);

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_types (ID, STATIC_ID, TASK_TYPE, DESCRIPTION, DISPLAY_SEQ, PARENT_TYPE_ID) values (24, 'MILESTONE-MERGED', 'Merged', 'Code has been merged', 5, 20);

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_types (ID, STATIC_ID, TASK_TYPE, DESCRIPTION, DISPLAY_SEQ, PARENT_TYPE_ID) values (25, 'MILESTONE-HOSTED', 'Hosted', 'Code has been hosted', 6, 20);

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_types (ID, STATIC_ID, TASK_TYPE, DESCRIPTION, DISPLAY_SEQ, PARENT_TYPE_ID) values (26, 'MILESTONE-COMPLETE', 'Fully Completed', 'The task is now fully complete', 7, 20);

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_types (ID, STATIC_ID, TASK_TYPE, DESCRIPTION, DISPLAY_SEQ) values (30, 'PM', 'PM', 'Project Management', 30);

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_types (ID, STATIC_ID, TASK_TYPE, DESCRIPTION, DISPLAY_SEQ, PARENT_TYPE_ID) values (31, 'PM-CUST-ISSUE', 'Customer Issue Identified', 'Customer Issue has been identified', 31, 30);

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_types (ID, STATIC_ID, TASK_TYPE, DESCRIPTION, DISPLAY_SEQ, PARENT_TYPE_ID) values (32, 'PM-RES-IDENTIFIED', 'Resolution Identified', 'Resolution has been identified', 32, 30);

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_types (ID, STATIC_ID, TASK_TYPE, DESCRIPTION, DISPLAY_SEQ, PARENT_TYPE_ID) values (33, 'PM-PROVIDED', 'Provided to Customer', 'Resolution Provided to Customer', 33, 30);

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_types (ID, STATIC_ID, TASK_TYPE, DESCRIPTION, DISPLAY_SEQ, PARENT_TYPE_ID) values (34, 'PM-IMPLEMENTED', 'Implemented by Customer', 'Resolution implemented by Customer', 44, 30);

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_types (ID, STATIC_ID, TASK_TYPE, DESCRIPTION, DISPLAY_SEQ) values (40, 'SALES', 'Sales', 'Sales Engagement', 40);

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_types (ID, STATIC_ID, TASK_TYPE, DESCRIPTION, DISPLAY_SEQ, PARENT_TYPE_ID) values (41, 'SALES-OPP-QUALIFIED', 'Opportunity Qualified', 'Opportunity has been qualified', 41, 40);

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_types (ID, STATIC_ID, TASK_TYPE, DESCRIPTION, DISPLAY_SEQ, PARENT_TYPE_ID) values (42, 'SALES-PRESENT', 'Presented to Customer', 'Presented to Customer', 42, 40);

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_types (ID, STATIC_ID, TASK_TYPE, DESCRIPTION, DISPLAY_SEQ, PARENT_TYPE_ID) values (43, 'SALES-PROPOSAL-DRAFT', 'Proposal Drafted', 'Proposal Drafted', 43, 40);

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_types (ID, STATIC_ID, TASK_TYPE, DESCRIPTION, DISPLAY_SEQ, PARENT_TYPE_ID) values (44, 'SALES-PROPOSAL-DEL', 'Proposal Delivered', 'Proposal Delivered', 44, 40);

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_types (ID, STATIC_ID, TASK_TYPE, DESCRIPTION, DISPLAY_SEQ, TASK_NAME_REQ_YN) values (50, 'DEVELOPMENT', 'Development', 'Development Activities', 50, 'Y');

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_statuses (id, task_type_id, status, static_id, display_seq, include_yn, is_default_yn, indicates_complete_yn) values (1, 1, 'Identified', 'IDENTIFIED', 1, 'Y', 'Y', 'N');

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_statuses (id, task_type_id, status, static_id, display_seq, include_yn, is_default_yn, indicates_complete_yn) values (2, 1, 'Assigned', 'ASSIGNED', 2, 'Y', 'N', 'N');

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_statuses (id, task_type_id, status, static_id, display_seq, include_yn, is_default_yn, indicates_complete_yn) values (4, 1, 'In Progress', 'IN-PROGRESS', 4, 'Y', 'N', 'N');

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_statuses (id, task_type_id, status, static_id, display_seq, include_yn, is_default_yn, indicates_complete_yn) values (5, 1, 'More Information Requested', 'MORE-INFO', 5, 'Y', 'N', 'N');

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_statuses (id, task_type_id, status, static_id, display_seq, include_yn, is_default_yn, indicates_complete_yn) values (6, 1, 'Paused', 'PAUSED', 6, 'Y', 'N', 'N');

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_statuses (id, task_type_id, status, static_id, display_seq, include_yn, is_default_yn, indicates_complete_yn) values (7, 1, 'Blocked', 'BLOCKED', 7, 'Y', 'N', 'N');

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_statuses (id, task_type_id, status, static_id, display_seq, include_yn, is_default_yn, indicates_complete_yn) values (8, 1, 'Completed', 'COMPLETED', 8, 'Y', 'N', 'Y');

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_statuses (id, task_type_id, status, static_id, display_seq, include_yn, is_default_yn, indicates_complete_yn) values (10, 20, 'Identified', 'IDENTIFIED', 1, 'Y', 'Y', 'N');

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_statuses (id, task_type_id, status, static_id, display_seq, include_yn, is_default_yn, indicates_complete_yn) values (11, 20, 'In Progress', 'IN-PROGRESS', 4, 'Y', 'N', 'N');

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_statuses (id, task_type_id, status, static_id, display_seq, include_yn, is_default_yn, indicates_complete_yn) values (12, 20, 'Paused', 'PAUSED', 6, 'Y', 'N', 'N');

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_statuses (id, task_type_id, status, static_id, display_seq, include_yn, is_default_yn, indicates_complete_yn) values (13, 20, 'Blocked', 'BLOCKED', 7, 'Y', 'N', 'N');

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_statuses (id, task_type_id, status, static_id, display_seq, include_yn, is_default_yn, indicates_complete_yn) values (14, 20, 'Completed', 'COMPLETED', 8, 'Y', 'N', 'Y');

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_statuses (id, task_type_id, status, static_id, display_seq, include_yn, is_default_yn, indicates_complete_yn) values (21, 30, 'Identified', 'IDENTIFIED', 1, 'Y', 'Y', 'N');

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_statuses (id, task_type_id, status, static_id, display_seq, include_yn, is_default_yn, indicates_complete_yn) values (22, 30, 'Assigned', 'ASSIGNED', 2, 'Y', 'N', 'N');

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_statuses (id, task_type_id, status, static_id, display_seq, include_yn, is_default_yn, indicates_complete_yn) values (23, 30, 'In Progress', 'IN-PROGRESS', 4, 'Y', 'N', 'N');

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_statuses (id, task_type_id, status, static_id, display_seq, include_yn, is_default_yn, indicates_complete_yn) values (24, 30, 'More Information Requested', 'MORE-INFO', 5, 'Y', 'N', 'N');

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_statuses (id, task_type_id, status, static_id, display_seq, include_yn, is_default_yn, indicates_complete_yn) values (25, 30, 'Paused', 'PAUSED', 6, 'Y', 'N', 'N');

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_statuses (id, task_type_id, status, static_id, display_seq, include_yn, is_default_yn, indicates_complete_yn) values (26, 30, 'Blocked', 'BLOCKED', 7, 'Y', 'N', 'N');

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_statuses (id, task_type_id, status, static_id, display_seq, include_yn, is_default_yn, indicates_complete_yn) values (27, 30, 'Completed', 'COMPLETED', 8, 'Y', 'N', 'Y');

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_statuses (id, task_type_id, status, static_id, display_seq, include_yn, is_default_yn, indicates_complete_yn) values (31, 40, 'Identified', 'IDENTIFIED', 1, 'Y', 'Y', 'N');

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_statuses (id, task_type_id, status, static_id, display_seq, include_yn, is_default_yn, indicates_complete_yn) values (32, 40, 'Assigned', 'ASSIGNED', 2, 'Y', 'N', 'N');

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_statuses (id, task_type_id, status, static_id, display_seq, include_yn, is_default_yn, indicates_complete_yn) values (33, 40, 'In Progress', 'IN-PROGRESS', 4, 'Y', 'N', 'N');

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_statuses (id, task_type_id, status, static_id, display_seq, include_yn, is_default_yn, indicates_complete_yn) values (34, 40, 'Completed', 'COMPLETED', 8, 'Y', 'N', 'Y');

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_statuses (id, task_type_id, status, static_id, display_seq, include_yn, is_default_yn, indicates_complete_yn) values (41, 50, 'Identified', 'IDENTIFIED', 1, 'Y', 'Y', 'N');

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_statuses (id, task_type_id, status, static_id, display_seq, include_yn, is_default_yn, indicates_complete_yn) values (42, 50, 'Assigned', 'ASSIGNED', 2, 'Y', 'N', 'N');

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_statuses (id, task_type_id, status, static_id, display_seq, include_yn, is_default_yn, indicates_complete_yn) values (43, 50, 'In Progress', 'IN-PROGRESS', 4, 'Y', 'N', 'N');

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_statuses (id, task_type_id, status, static_id, display_seq, include_yn, is_default_yn, indicates_complete_yn) values (44, 50, 'More Information Requested', 'MORE-INFO', 5, 'Y', 'N', 'N');

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_statuses (id, task_type_id, status, static_id, display_seq, include_yn, is_default_yn, indicates_complete_yn) values (45, 50, 'Paused', 'PAUSED', 6, 'Y', 'N', 'N');

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_statuses (id, task_type_id, status, static_id, display_seq, include_yn, is_default_yn, indicates_complete_yn) values (46, 50, 'Blocked', 'BLOCKED', 7, 'Y', 'N', 'N');

-- source: install_seed_task_types_and_statuses.sql (p_sequence 890, Seed Task Types and Statuses)
insert into sp_task_statuses (id, task_type_id, status, static_id, display_seq, include_yn, is_default_yn, indicates_complete_yn) values (47, 50, 'Completed', 'COMPLETED', 8, 'Y', 'N', 'Y');
