-- Oracle DDL/DML rebuilt from the APEX 24.2 Strategic Planner starter app export (f7150, MIT licence).
-- Generated by db/ora2pg/extract_apex_install_scripts.py; input to ora2pg. Do not edit by hand.

-- source: install_sp_projects_tables.sql (p_sequence 240, sp_projects tables)
comment on table sp_project_contributors is 'Identifies resources working on a given project';
/

-- source: install_configurable_text_table.sql (p_sequence 630, configurable_text table)
begin
insert into SP_CONFIGURABLE_TEXT (id, config_ID, description) values (1, 'ABOUT-PRIMARY-TEXT','Primary text displayed on application about page.');
end;
/

-- source: install_seed_project_sizes.sql (p_sequence 840, seed project sizes)
begin
insert into sp_project_sizes (Project_size, size_description, effort_days) values ('S','Small',2);   -- 2 days
insert into sp_project_sizes (Project_size, size_description, effort_days) values ('M','Medium',10); -- 2 weeks
insert into sp_project_sizes (Project_size, size_description, effort_days) values ('L','Large',40);  -- 2 months
insert into sp_project_sizes (Project_size, size_description, effort_days) values ('XL','Extra Large',120); -- 6 months
insert into sp_project_sizes (Project_size, size_description, effort_days) values ('2XL','2 Times Extra Large',240);  -- 12 months, 1 year
insert into sp_project_sizes (Project_size, size_description, effort_days, include_yn) values ('3XL','3 Times Extra Large',360,'N');  -- 18 months, 1.5 years
insert into sp_project_sizes (Project_size, size_description, effort_days, include_yn) values ('4XL','4 Times Extra Large',640,'N');  -- 24 months, 2 years
insert into sp_project_sizes (Project_size, size_description, effort_days, include_yn) values ('8XL','8 Times Extra Large',960,'N');  -- 48 months, 4 years
end;
/

-- source: install_seed_settings_and_prompts.sql (p_sequence 860, seed settings and prompts)
begin
    sp_util.add_setting (  
        p_static_id     => 'APP_ID',   
        p_description   => 'Application ID of the application.  Used by summary jobs.', 
        p_setting_value => null, 
        p_is_numeric_yn => 'Y', 
        p_is_yn         => 'N' );
    sp_util.add_setting (  
        p_static_id     => 'APP_PREFIX_URL',   
        p_description   => 'Prefix URL of the application.  Used for link creation in summary jobs.', 
        p_setting_value => null, 
        p_is_numeric_yn => 'N', 
        p_is_yn         => 'N' );
    sp_util.add_setting (  
        p_static_id     => 'APP_HOME_URL',   
        p_description   => 'Full URL to the home page of the application.  Used for home link in summary emails.', 
        p_setting_value => null, 
        p_is_numeric_yn => 'N', 
        p_is_yn         => 'N' );
    sp_util.add_setting (  
        p_static_id     => 'GET_COMMENT_IMAGE_PREFIX',   
        p_description   => 'Path to displacy images within comments, set by process, do not edit', 
        p_setting_value => null, 
        p_is_numeric_yn => 'N', 
        p_is_yn         => 'N');
    sp_util.add_setting (  
        p_static_id     => 'SUMMARY_AI_SERVICE',   
        p_description   => 'Name of AI Service used for generating summaries. Must be configured under Generative AI Services of the application.', 
        p_setting_value => null, 
        p_is_numeric_yn => 'N', 
        p_is_yn         => 'N' );

    -- most recent install of Strategic Planner
    --
    for a in (
        select application_id
          from apex_applications
         where application_name = 'Strategic Planner'
         order by last_updated_on desc
    ) loop
        sp_util.set_setting (p_static_id     => 'APP_ID',   
                             p_setting_value => a.application_id); 
    end loop;

    sp_util.set_setting (p_static_id     => 'APP_PREFIX_URL',   
                         p_setting_value => APEX_UTIL.HOST_URL); 
end;
/

-- source: install_seed_settings_and_prompts.sql (p_sequence 860, seed settings and prompts)
begin
    sp_util.add_ai_prompt (  
        p_static_id     => 'FULL_PROJECT_SUMMARY',   
        p_description   => 'Used for generating a full project summary.', 
        p_prompt        => 'You are given details for a software development project, in markdown format, including the most recent comments from the last 90 days. Please return the following:

Concise Summary: Extract key points to create a brief but accurate summary of the overall progress, tasks completed, any issues or blockers, and any milestones achieved or reviews completed.  Also include any concerns, such as having no Contributors or Milestones defined or dates being past due.  This can be 1 or 2 paragraphs depending on the size of the input.

Risk Assessment: Analyze for signs of potential project risks (e.g., delays, unaddressed issues, lack of progress, etc.). Based on this analysis, assign a risk level to the project as follows:

None: No risk, assign to all projects with percent complete of 100% (and only those).

Low: No immediate concerns; project is progressing smoothly with no major issues.

Moderate: Some concerns or blockers are present but can be addressed; risk to the timeline or scope is possible.

High: Major issues or blockers that significantly affect the progress; there is a real danger to the timeline, scope, or quality.

Additionally, list any project highlight achievements, percent complete or status changes, completed reviews, approvals received, or anything significant about the project in the highlights section of the JSON.  Always include them in a JSON array.  If there are no highlights, simply add a single element called "No Highlights".

Return using a JSON document with the following structure:

{
  "summary": "Concise summary of the project progress and key highlights.",
  "highlights" : "List project highlights",
  "risk": "None | Low | Moderate | High"
}

Make sure to accurately assess the project risk and provide a clear, easy-to-understand summary.  Do not include any prefix or suffix characters - only a JSON document.' );
end;
/

-- source: install_seed_settings_and_prompts.sql (p_sequence 860, seed settings and prompts)
begin
    sp_util.add_ai_prompt (  
        p_static_id     => 'UPDATE_PROJECT_SUMMARY',   
        p_description   => 'Used for generating an updated project summary.', 
        p_prompt        => 'You are given details for a software development project, in markdown format, and the last summary generated along with any data that has changed since the last summary. Please return the following:

Concise Summary: Extract key points to create a brief but accurate summary of the overall progress since the last summary, tasks completed, any issues or blockers, and any milestones achieved or reviews completed.  Also include any concerns, such as having no Contributors or Milestones defined or dates being past due.  This can be 1 or 2 paragraphs depending on the size of the input.

Risk Assessment: Analyze for signs of potential project risks (e.g., delays, unaddressed issues, lack of progress, etc.). Based on this analysis, assign a risk level to the project as follows:

None: No risk, assign to all projects with percent complete of 100% (and only those).

Low: No immediate concerns; project is progressing smoothly with no major issues.

Moderate: Some concerns or blockers are present but can be addressed; risk to the timeline or scope is possible.

High: Major issues or blockers that significantly affect the progress; there is a real danger to the timeline, scope, or quality.

Additionally, list any project highlight achievements, percent complete or status changes, completed reviews, approvals received, or anything significant about the project in the highlights section of the JSON.  Always include them in a JSON array.  If there are no highlights, simply add a single element called "No Highlights".

Return using a JSON document with the following structure:

{
  "summary": "Concise summary of the project progress and key highlights.",
  "highlights" : "List project highlights",
  "risk": "None | Low | Moderate | High"
}

Make sure to accurately assess the project risk and provide a clear, easy-to-understand summary.  Do not include any prefix or suffix characters - only a JSON document.' );
end;
/

-- source: install_seed_settings_and_prompts.sql (p_sequence 860, seed settings and prompts)
begin
    sp_util.add_ai_prompt (  
        p_static_id     => 'RELEASE_SUMMARY',   
        p_description   => 'Used for generating a release summary.', 
        p_prompt        => 'You are given details for a software development product release, in markdown format.  This includes basic release details along with all the features included in the release, grouped by focus area. Please return a JSON document with the following structure:

{
  "summary": "Concise summary of the release",
  "highlights": "List release highlights"
}

Make sure to provide a clear, easy-to-understand summary.  Do not include any prefix or suffix characters - only a JSON document.

Summary: Extract key points to create a brief but accurate summary of the release.  This can be 1 or 2 paragraphs depending on the size of the input.

Highlights: List any release highlights, such as important features in the highlights section of the JSON.  Always include them in a JSON array.  If there are no highlights, simply add a single element called "No Highlights".' );
end;
/

-- source: install_notifications_job.sql (p_sequence 910, Notifications job)
begin
    sys.dbms_scheduler.create_job    
     (job_name        => 'SP_NOTIF_SUBSCRIPTIONS',
      job_type        => 'STORED_PROCEDURE',
      job_action      => 'SP_UTIL.SEND_NOTIF_SUBSCRIPTIONS',
      start_date      => systimestamp,
      repeat_interval => 'FREQ=DAILY; BYDAY=MON,TUE,WED,THU,FRI; BYHOUR=8; BYMINUTE=0;',
      enabled         => true,
      auto_drop       => false);
end;
/

-- source: install_sp_generate_ai_project_summaries_job.sql (p_sequence 915, SP_GENERATE_AI_PROJECT_SUMMARIES_JOB)
begin
    dbms_scheduler.create_job (
        job_name   => 'SP_GENERATE_AI_PROJECT_SUMMARIES_JOB',
        job_type   => 'STORED_PROCEDURE',
        job_action => 'sp_summary_util.generate_project_summaries',
        start_date => null,
        repeat_interval => 'FREQ=WEEKLY; BYTIME=050000; BYDAY=SUN',
        enabled    => TRUE,
        auto_drop  => FALSE,
        comments   => 'Creates AI Summaries of active projects once a week' );
end;
/

-- source: install_seed_first_user.sql (p_sequence 920, seed first user)
declare
    l_app_user  varchar2(255) := apex_custom_auth.get_username;
begin
    --
    -- get email of developer installing the app
    -- if no email, see if app_user is an email
    -- (first autonomous user may not have an email)
    --
    for u in (
        select first_name, last_name,
               case when email is null and regexp_like(l_app_user,'[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}')
                    then l_app_user
                    else email
                    end email
          from apex_workspace_apex_users
         where user_name = l_app_user
    ) loop
      if u.email is not null then
        --
        -- most recent install of Strategic Planner
        --
        for a in (
            select application_id
              from apex_applications
             where application_name = 'Strategic Planner'
             order by last_updated_on desc
        ) loop
            --
            -- determine admin app role id
            --
            for r in (
                select role_id
                  from apex_appl_acl_roles
                 where application_id = a.application_id 
                   and role_static_id = 'ADMINISTRATOR'
            ) loop
                --
                -- make installer an app admin
                --
                apex_acl.add_user_role (
            	    p_application_id => a.application_id,
            	    p_user_name      => u.email,
           	    p_role_id        => r.role_id );
                commit;
                --
                -- also add this first user as a Team Member
                --
                insert into SP_TEAM_MEMBERS 
                    (email, first_name, last_name) 
                values 
                    (u.email, u.first_name, u.last_name);
                commit;
                exit;
            end loop;
            exit;
        end loop;
      end if;
    end loop;
end;
/
