-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=localhost;sid=NONE

SET client_encoding TO 'UTF8';

SET search_path = legacy,public;
\set ON_ERROR_STOP ON

SET check_function_bodies = false;


-- Oracle DDL/DML rebuilt from the APEX 24.2 Strategic Planner starter app export (f7150, MIT licence).
-- Generated by db/ora2pg/extract_apex_install_scripts.py; input to ora2pg. Do not edit by hand.
-- source: install_sp_date_range_pct_comp_function.sql (p_sequence 590, sp_date_range_pct_comp function)
CREATE OR REPLACE FUNCTION sp_date_range_pct_comp ( p_start_date timestamp(0), p_end_date timestamp(0)) RETURNS numeric AS $body$
DECLARE

    l_pct_complete numeric := 0;
    l_days         numeric := null;
    l_days_elapsed numeric := null;
    l_sysdate      timestamp(0)   := date_trunc('day', clock_timestamp());

BEGIN
    --
    -- this function return 0, 10, 20 .. 100 based days elapsed between two dates
    --
    if coalesce(p_start_date::text, '') = '' or coalesce(p_end_date::text, '') = '' then
       l_pct_complete := 0; -- required both dates be not null
    else
       if p_start_date > p_end_date then
           l_pct_complete := 0; -- invalid condition
       elsif p_start_date > l_sysdate then
           l_pct_complete := 0;
       elsif p_start_date = p_end_date then 
           l_pct_complete := 100;
       elsif l_sysdate > p_end_date then
           l_pct_complete := 100;
       else
           l_days := p_end_date - p_start_date;
           if l_days > 0 then 
               l_days_elapsed := p_end_date - l_sysdate;
               l_pct_complete := 100 * l_days_elapsed / l_days;
               l_pct_complete := round(l_pct_complete,-1);
               l_pct_complete := 100 - l_pct_complete;
           end if;
       end if;
    end if;
    return l_pct_complete;
end;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION sp_date_range_pct_comp ( p_start_date timestamp(0), p_end_date timestamp(0)) FROM PUBLIC;

-- Function sp_date_range_pct_comp estimated cost: 4
	-- TEST => 2
	-- SIZE => 1




CREATE OR REPLACE PROCEDURE sp_favorite_toggle ( p_project_id numeric, p_app_user_id numeric) AS $body$
DECLARE

   is_favorite  boolean := false;
   l_count      numeric;
  c1 RECORD;

BEGIN
    if coalesce(p_project_id::text, '') = '' then
        RAISE EXCEPTION '%', 'p_project_id is null' USING ERRCODE = '45001';
    elsif coalesce(p_app_user_id::text, '') = '' then
        RAISE EXCEPTION '%', 'p_app_user_id is null' USING ERRCODE = '45001';
    else
        select count(*) into STRICT l_count from sp_projects where id = p_project_id;
        if l_count = 0 then
           RAISE EXCEPTION '%', 'p_project_id '||p_project_id||' not found' USING ERRCODE = '45001';
        end if;
    end if;
    --
    -- If a row is returned then this project is a favorate of the user identified
    --
    for c1 in (SELECT 1 from SP_FAVORITES where team_member_id = p_app_user_id and project_id = p_project_id) loop
        is_favorite := true;
    end loop;
    --
    -- toggle current setting
    -- if is currently favorite then unfavorite by deleting row
    -- if not currently a favorite then favorate by inserting a row
    --
    if is_favorite then
        delete from SP_FAVORITES where team_member_id = p_app_user_id and project_id = p_project_id;
    else
        insert into SP_FAVORITES(team_member_id, PROJECT_ID) values (p_app_user_id, p_project_id);
    end if;
end;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE sp_favorite_toggle ( p_project_id numeric, p_app_user_id numeric) FROM PUBLIC;

-- Function sp_favorite_toggle estimated cost: 4.2
	-- CONCAT => 2 (cost: 0.1)
	-- TEST => 2
	-- SIZE => 1

-- source: install_sp_tag_diff_function.sql (p_sequence 600, sp_tag_diff function)
CREATE OR REPLACE FUNCTION sp_tag_diff ( p_old_tags varchar, p_new_tags varchar) RETURNS varchar AS $body$
DECLARE

    --
    -- Example:
    --
    -- begin dbms_output.put_line(sp_tag_diff (p_old_tags => 'A,C',p_new_tags => 'B,C,D')); end;
    --
    l_return        varchar(32767);
    l_vc_arr_old    APEX_APPLICATION_GLOBAL.VC_ARR2;
    l_vc_arr_new    APEX_APPLICATION_GLOBAL.VC_ARR2;
    l_plus_string   varchar(32767);
    l_minus_string  varchar(32767);
    l_old_tags      varchar(32767) := upper(','||replace(p_old_tags,' ','')||',');
    l_new_tags      varchar(32767) := upper(','||replace(p_new_tags,' ','')||',');
BEGIN
    l_vc_arr_old := APEX_UTIL.STRING_TO_TABLE(upper(replace(p_old_tags,' ',null)),',');
    l_vc_arr_new := APEX_UTIL.STRING_TO_TABLE(upper(replace(p_new_tags,' ',null)),',');
    --
    -- look for removed tags
    --
    for i in 1..l_vc_arr_old.count loop
        if position(','||l_vc_arr_old(i)||',' in l_new_tags) = 0 then
            l_return := l_return||'<span class="t-Badge u-danger">'||apex_escape.html(l_vc_arr_old(i))||'</span> ';
        end if;
    end loop;
    --
    -- look for new tags
    --
    for i in 1..l_vc_arr_new.count loop
        if position(','||l_vc_arr_new(i)||',' in l_old_tags) = 0 then
            l_return := l_return||'<span class="t-Badge u-success">'||apex_escape.html(l_vc_arr_new(i))||'</span> ';
        end if;
    end loop;
    --
    --
    --
    return l_return;
end;
-- source: install_favorite_toggle_procedure.sql (p_sequence 620, favorite_toggle procedure)
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION sp_tag_diff ( p_old_tags varchar, p_new_tags varchar) FROM PUBLIC;

-- Function sp_tag_diff estimated cost: 5.4
	-- CONCAT => 14 (cost: 0.1)
	-- TEST => 2
	-- SIZE => 1

-- Total number of procedures: 3.
-- Total size of procedures code: 1473 bytes.
-- Total estimated cost: 13.6 units, 1 person-day(s).
