-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=localhost;sid=NONE

SET client_encoding TO 'UTF8';

SET search_path = legacy,public;
\set ON_ERROR_STOP ON

SET check_function_bodies = false;

CREATE SCHEMA IF NOT EXISTS legacy;
CREATE SEQUENCE sp_seq INCREMENT 1 NO MINVALUE NO MAXVALUE START ;
CREATE SEQUENCE sp_kb_stack_rank_seq INCREMENT 1 NO MINVALUE NO MAXVALUE START 1 CACHE 20;
