-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=localhost;sid=NONE

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET check_function_bodies = false;

CREATE SCHEMA IF NOT EXISTS legacy;
ALTER SCHEMA legacy OWNER TO sp;

SET search_path = legacy,public;


CREATE TABLE sp_app_log (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                           constraint sp_app_log_pk,
	activity varchar(255) NOT NULL,
	details varchar(4000),
	created timestamp(0) NOT NULL,
	created_trunc timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_app_log_i1 ON sp_app_log (created_trunc);
ALTER TABLE sp_app_log ADD UNIQUE (id);


CREATE TABLE sp_error_log (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                              constraint sp_error_log_pk,
	package_name varchar(255),
	procedure_name varchar(500),
	error varchar(4000) NOT NULL,
	arg1_name varchar(255),
	arg1_val varchar(4000),
	arg2_name varchar(255),
	arg2_val varchar(4000),
	arg3_name varchar(255),
	arg3_val varchar(4000),
	arg4_name varchar(255),
	arg4_val varchar(4000),
	arg5_name varchar(255),
	arg5_val varchar(4000),
	created timestamp(0),
	created_trunc timestamp(0),
	created_by varchar(255)
) ;
CREATE INDEX sp_error_log_i1 ON sp_error_log (created_trunc);
ALTER TABLE sp_error_log ADD UNIQUE (id);


CREATE TABLE sp_app_settings (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                      constraint sp_app_settings_pk,
	static_id varchar(255) NOT NULL,
	description varchar(4000) NOT NULL,
	setting_value varchar(4000),
	is_numeric_yn varchar(1) NOT NULL,
	is_yn varchar(1) NOT NULL,
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
ALTER TABLE sp_app_settings ADD UNIQUE (id);
ALTER TABLE sp_app_settings ADD UNIQUE (static_id);
ALTER TABLE sp_app_settings ADD CONSTRAINT o2pc_is_numeric_yn_is_numeric_yn CHECK (is_numeric_yn in ('Y','N');
ALTER TABLE sp_app_settings ADD CONSTRAINT o2pc_is_yn_is_yn CHECK (is_yn in ('Y','N');


CREATE TABLE sp_ai_prompts (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                      constraint sp_ai_prompts_pk,
	static_id varchar(255) NOT NULL,
	description varchar(4000) NOT NULL,
	prompt text,
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
ALTER TABLE sp_ai_prompts ADD UNIQUE (static_id);
ALTER TABLE sp_ai_prompts ADD UNIQUE (id);


CREATE TABLE sp_report_questions (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                      constraint sp_report_questions_pk,
	page_id numeric NOT NULL,
	question varchar(4000) NOT NULL,
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
ALTER TABLE sp_report_questions ADD UNIQUE (id);


CREATE TABLE sp_default_tags (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint SP_DEFAULT_TAGS_pk,
	display_sequence numeric NOT NULL,
	tag varchar(30) NOT NULL,
	description varchar(512),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_default_tags_u1 ON sp_default_tags (tag);
ALTER TABLE sp_default_tags ADD UNIQUE (id);


CREATE TABLE sp_app_nomenclature (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint SP_APP_NOMENCLATURE_pk,
	static_id varchar(50),
	default_order numeric,
	custom_value varchar(50),
	default_value varchar(50),
	description varchar(4000),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_app_nomenclature_u1 ON sp_app_nomenclature (static_id);
ALTER TABLE sp_app_nomenclature ADD UNIQUE (id);


CREATE TABLE sp_resource_types (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_resource_types_id_pk,
	resource_type varchar(50) NOT NULL,
	upper_resource_type varchar(50) NOT NULL,
	resource_description varchar(4000),
	is_default_yn varchar(1),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_resource_types_u1 ON sp_resource_types (resource_type);
CREATE INDEX sp_resource_types_u2 ON sp_resource_types (upper_resource_type);
ALTER TABLE sp_resource_types ADD UNIQUE (id);
ALTER TABLE sp_resource_types ADD CONSTRAINT o2pc_is_default_yn_is_default_yn CHECK (is_default_yn in ('Y','N');


CREATE TABLE sp_competencies (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_competencies_pk,
	competency varchar(100) NOT NULL,
	description varchar(4000),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_competencies_i1 ON sp_competencies (competency);
ALTER TABLE sp_competencies ADD UNIQUE (id);


CREATE TABLE sp_groups (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint SP_GROUPS_pk,
	group_name varchar(100) NOT NULL,
	group_name_upper varchar(100) NOT NULL,
	description varchar(4000),
	group_tag varchar(100),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_groups_i1 ON sp_groups (group_name_upper);
ALTER TABLE sp_groups ADD UNIQUE (id);


CREATE TABLE sp_team_members (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_team_members_id_pk,
	first_name varchar(255) NOT NULL,
	last_name varchar(255) NOT NULL,
	initials varchar(3) NOT NULL,
	screen_name varchar(50),
	email varchar(255) NOT NULL,
	email_domain varchar(255),
	notification_pref varchar(255),
	comment_notif_pref varchar(255),
	tags varchar(4000),
	hash_tag_reference varchar(30),
	photo bytea,
	photo_filename varchar(512),
	photo_mimetype varchar(512),
	photo_charset varchar(512),
	photo_lastupd timestamp(0),
	is_current_yn varchar(1),
	auto_created_yn varchar(1),
	location varchar(500),
	country_id numeric,
	app_role varchar(255),
	competencies varchar(4000),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_team_members_i1 ON sp_team_members (country_id);
CREATE INDEX sp_team_members_u1 ON sp_team_members (email);
CREATE INDEX sp_team_members_u2 ON sp_team_members (hash_tag_reference);
CREATE INDEX sp_team_members_u4 ON sp_team_members (screen_name);
ALTER TABLE sp_team_members ADD UNIQUE (id);
ALTER TABLE sp_team_members ADD CONSTRAINT o2pc_auto_created_yn_auto_created_yn CHECK (auto_created_yn in ('Y','N');
ALTER TABLE sp_team_members ADD CONSTRAINT o2pc_is_current_yn_is_current_yn CHECK (is_current_yn in ('Y','N');


CREATE TABLE sp_group_members (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint SP_GROUP_MEMBERS_pk,
	group_id numeric NOT NULL,
	team_member_id numeric NOT NULL,
	assignment varchar(255),
	full_time_yn varchar(1),
	group_leader_yn varchar(1),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_group_members_i1 ON sp_group_members (group_id);
CREATE INDEX sp_group_members_u1 ON sp_group_members (team_member_id, group_id);
ALTER TABLE sp_group_members ADD UNIQUE (id);


CREATE TABLE sp_release_trains (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_release_trains_id_pk,
	release_train varchar(50) NOT NULL,
	release_owner_id numeric,
	release varchar(30) NOT NULL,
	release_target_date timestamp(0),
	release_open_date timestamp(0),
	release_distribution_url varchar(4000),
	release_management_url varchar(4000),
	description text,
	release_open_completed varchar(1) DEFAULT on null 'N'
                                   constraint sp_release_trains_open_ck
                                   ),
	release_completed varchar(1) DEFAULT on null 'N'
                                   constraint sp_release_trains_completed_ck
                                   ),
	release_type varchar(50),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_release_trains_u1 ON sp_release_trains (release_owner_id);
ALTER TABLE sp_release_trains ADD UNIQUE (id);
ALTER TABLE sp_release_trains ADD CONSTRAINT o2pc_release_completed_release_completed CHECK (release_completed in ('Y','N');
ALTER TABLE sp_release_trains ADD CONSTRAINT o2pc_release_open_completed_release_open_completed CHECK (release_open_completed in ('Y','N');
ALTER TABLE sp_release_trains ADD CONSTRAINT o2pc_release_type_release_type CHECK (release_type in ('FULL','PATCH');


CREATE TABLE sp_release_history (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_release_history_pk,
	release_id numeric,
	attribute_column varchar(255) NOT NULL,
	change_type varchar(30) NOT NULL,
	old_value varchar(4000),
	new_value varchar(4000),
	old_value_clob text,
	new_value_clob text,
	changed_on timestamp(0) NOT NULL,
	changed_by varchar(255)
) ;
CREATE INDEX sp_release_history_i1 ON sp_release_history (release_id);
CREATE INDEX sp_release_history_i2 ON sp_release_history (changed_by);
ALTER TABLE sp_release_history ADD UNIQUE (id);
ALTER TABLE sp_release_history ADD CONSTRAINT o2pc_change_type_change_type CHECK (change_type in ('CREATE','UPDATE','DELETE');


CREATE TABLE sp_areas (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_areas_id_pk,
	area varchar(50) NOT NULL,
	description varchar(4000),
	owner_id numeric,
	status_scale varchar(1),
	hidden_by_default_yn varchar(1),
	tags varchar(4000),
	image bytea,
	image_name varchar(512),
	image_mimetype varchar(512),
	image_last_updated timestamp(0),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_areas_i1 ON sp_areas (owner_id);
CREATE INDEX sp_areas_u1 ON sp_areas (area);
ALTER TABLE sp_areas ADD UNIQUE (id);
ALTER TABLE sp_areas ADD CONSTRAINT o2pc_status_scale_status_scale CHECK (status_scale in ('A','B','C','D','E','F','G'));


CREATE TABLE sp_project_scales (
	scale_letter varchar(1) NOT NULL,
	scale_name varchar(50) NOT NULL,
	is_active_yn varchar(1) NOT NULL,
	min_pc_for_status numeric,
	pc0_label varchar(60),
	pc0_desc varchar(4000),
	pc10_label varchar(60),
	pc10_desc varchar(4000),
	pc20_label varchar(60),
	pc20_desc varchar(4000),
	pc30_label varchar(60),
	pc30_desc varchar(4000),
	pc40_label varchar(60),
	pc40_desc varchar(4000),
	pc50_label varchar(60),
	pc50_desc varchar(4000),
	pc60_label varchar(60),
	pc60_desc varchar(4000),
	pc70_label varchar(60),
	pc70_desc varchar(4000),
	pc80_label varchar(60),
	pc80_desc varchar(4000),
	pc90_label varchar(60),
	pc90_desc varchar(4000),
	pc100_label varchar(60),
	pc100_desc varchar(4000),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_project_scale_uk ON sp_project_scales (scale_name);
ALTER TABLE sp_project_scales ADD UNIQUE (scale_letter);
ALTER TABLE sp_project_scales ADD CONSTRAINT o2pc_is_active_yn_is_active_yn CHECK (is_active_yn in ('Y','N');

ALTER TABLE sp_project_scales ADD CONSTRAINT sp_project_scale_ck CHECK (scale_letter in ('A','B','C','D','E'));


CREATE TABLE sp_initiatives (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_initiatives_id_pk,
	area_id numeric NOT NULL,
	initiative varchar(255) NOT NULL,
	objective varchar(4000),
	sponsor_id numeric,
	friendly_identifier varchar(30),
	initiative_url_name varchar(255),
	status_scale varchar(1),
	tags varchar(4000),
	hidden_by_default_yn varchar(1),
	image bytea,
	image_name varchar(512),
	image_mimetype varchar(512),
	image_last_updated timestamp(0),
	archived_yn varchar(1),
	archived_date timestamp(0),
	archived_by varchar(255),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_initiatives_i1 ON sp_initiatives (area_id);
CREATE INDEX sp_initiatives_i2 ON sp_initiatives (sponsor_id);
CREATE INDEX sp_initiatives_i3 ON sp_initiatives (status_scale);
CREATE INDEX sp_initiatives_u1 ON sp_initiatives (area_id, initiative);
ALTER TABLE sp_initiatives ADD UNIQUE (id);
ALTER TABLE sp_initiatives ADD CONSTRAINT o2pc_archived_yn_archived_yn CHECK (archived_yn in ('Y','N');
ALTER TABLE sp_initiatives ADD CONSTRAINT o2pc_status_scale_status_scale CHECK (status_scale in ('A','B','C','D','E');


CREATE TABLE sp_initiative_history (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_initiative_history_pk,
	initiative_id numeric NOT NULL,
	attribute_column varchar(255) NOT NULL,
	change_type varchar(30) NOT NULL,
	old_value varchar(4000),
	new_value varchar(4000),
	old_value_clob text,
	new_value_clob text,
	changed_on timestamp(0) NOT NULL,
	changed_by varchar(255)
) ;
CREATE INDEX sp_initiative_history_i1 ON sp_initiative_history (initiative_id);
CREATE INDEX sp_initiative_history_i2 ON sp_initiative_history (changed_by);
ALTER TABLE sp_initiative_history ADD UNIQUE (id);
ALTER TABLE sp_initiative_history ADD CONSTRAINT o2pc_change_type_change_type CHECK (change_type in ('CREATE','UPDATE','DELETE');


CREATE TABLE sp_project_priorities (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_project_priority_id_pk,
	priority numeric NOT NULL,
	description varchar(40) NOT NULL,
	is_default_yn varchar(1),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_project_priorities_u1 ON sp_project_priorities (priority);
ALTER TABLE sp_project_priorities ADD UNIQUE (id);
ALTER TABLE sp_project_priorities ADD CONSTRAINT o2pc_is_default_yn_is_default_yn CHECK (is_default_yn in ('Y','N');


CREATE TABLE sp_project_sizes (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_project_size_id_pk,
	project_size varchar(30) NOT NULL,
	size_description varchar(100) NOT NULL,
	effort_days numeric NOT NULL,
	include_yn varchar(1) NOT NULL,
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_project_sizes_u1 ON sp_project_sizes (project_size);
CREATE INDEX sp_project_sizes_u2 ON sp_project_sizes (effort_days);
ALTER TABLE sp_project_sizes ADD UNIQUE (id);


CREATE TABLE sp_project_statuses (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_project_statuses_pk,
	status varchar(100) NOT NULL,
	static_id varchar(30) NOT NULL,
	display_seq numeric,
	include_yn varchar(1) DEFAULT on null 'Y'
                                   constraint sp_project_statuses_include_cc
                                   ),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_project_statuses_u1 ON sp_project_statuses (status);
CREATE INDEX sp_project_statuses_u2 ON sp_project_statuses (static_id);
ALTER TABLE sp_project_statuses ADD UNIQUE (id);
ALTER TABLE sp_project_statuses ADD CONSTRAINT o2pc_include_yn_include_yn CHECK (include_yn in ('Y','N');


CREATE TABLE sp_project_groups (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                      constraint sp_project_groups_pk,
	group_name varchar(255) NOT NULL,
	group_description varchar(4000),
	is_active_yn varchar(1) DEFAULT on null 'Y'
                      constraint sp_project_groups_active_yn
                      ),
	created timestamp(0),
	created_by varchar(255),
	updated timestamp(0),
	updated_by varchar(255)
) ;
CREATE INDEX sp_project_groups_i1 ON sp_project_groups (upper(group_name));
ALTER TABLE sp_project_groups ADD UNIQUE (id);
ALTER TABLE sp_project_groups ADD CONSTRAINT o2pc_is_active_yn_is_active_yn CHECK (is_active_yn in ('Y','N');


CREATE TABLE sp_initiative_focus_areas (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_initiative_focus_area_pk,
	initiative_id numeric NOT NULL,
	focus_area varchar(60) NOT NULL,
	active_yn varchar(1) DEFAULT on null 'Y'
                                   constraint sp_initiative_fa_active_cc
                                   ),
	display_sequence numeric,
	development_owner_id numeric,
	description varchar(4000),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_initiative_focus_areas_u1 ON sp_initiative_focus_areas (initiative_id, focus_area);
ALTER TABLE sp_initiative_focus_areas ADD UNIQUE (id);
ALTER TABLE sp_initiative_focus_areas ADD CONSTRAINT o2pc_active_yn_active_yn CHECK (active_yn in ('Y','N');


CREATE TABLE sp_init_focus_area_links (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_init_focus_area_links_pk,
	init_focus_area_id numeric NOT NULL,
	link_name varchar(255) NOT NULL,
	link_url varchar(4000) NOT NULL,
	important_yn varchar(1) DEFAULT on null 'N'
                                   constraint sp_init_focus_area_link_imp_cc
                                   ),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_init_focus_area_links_i1 ON sp_init_focus_area_links (init_focus_area_id);
CREATE INDEX sp_init_focus_area_links_i2 ON sp_init_focus_area_links (updated);
ALTER TABLE sp_init_focus_area_links ADD UNIQUE (id);
ALTER TABLE sp_init_focus_area_links ADD CONSTRAINT o2pc_important_yn_important_yn CHECK (important_yn in ('Y','N');


CREATE TABLE sp_init_focus_area_documents (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_init_focus_area_documents_pk,
	init_focus_area_id numeric NOT NULL,
	document_blob bytea,
	document_filename varchar(512),
	document_mimetype varchar(512),
	document_charset varchar(512),
	document_lastupd timestamp(0),
	important_yn varchar(1) DEFAULT on null 'N'
                                   constraint sp_init_focus_area_doc_imp_cc
                                   ),
	doc_description varchar(4000),
	tags varchar(4000),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_init_focus_area_documents_i1 ON sp_init_focus_area_documents (init_focus_area_id);
CREATE INDEX sp_init_focus_area_documents_i2 ON sp_init_focus_area_documents (updated);
ALTER TABLE sp_init_focus_area_documents ADD UNIQUE (id);
ALTER TABLE sp_init_focus_area_documents ADD CONSTRAINT o2pc_important_yn_important_yn CHECK (important_yn in ('Y','N');


CREATE TABLE sp_init_focus_area_comments (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_init_focus_area_comments_pk,
	init_focus_area_id numeric NOT NULL,
	body text,
	body_html text,
	body_no_images text,
	image_ref_id numeric,
	author_id numeric,
	private_yn varchar(1) DEFAULT on null 'N'
                                   constraint sp_init_focus_area_comment_private_cc
                                   ),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_init_focus_area_comments_i1 ON sp_init_focus_area_comments (init_focus_area_id);
CREATE INDEX sp_init_focus_area_comments_i2 ON sp_init_focus_area_comments (author_id);
CREATE INDEX sp_init_focus_area_comments_i3 ON sp_init_focus_area_comments (image_ref_id);
ALTER TABLE sp_init_focus_area_comments ADD UNIQUE (id);
ALTER TABLE sp_init_focus_area_comments ADD CONSTRAINT o2pc_private_yn_private_yn CHECK (private_yn in ('Y','N');


CREATE TABLE sp_init_focus_area_history (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_init_focus_area_history_pk,
	init_focus_area_id numeric NOT NULL,
	attribute_column varchar(255) NOT NULL,
	change_type varchar(30) NOT NULL,
	old_value varchar(4000),
	new_value varchar(4000),
	old_value_clob text,
	new_value_clob text,
	changed_on timestamp(0) NOT NULL,
	changed_by varchar(255)
) ;
CREATE INDEX sp_init_focus_area_history_i1 ON sp_init_focus_area_history (init_focus_area_id);
CREATE INDEX sp_init_focus_area_history_i2 ON sp_init_focus_area_history (changed_by);
ALTER TABLE sp_init_focus_area_history ADD UNIQUE (id);
ALTER TABLE sp_init_focus_area_history ADD CONSTRAINT o2pc_change_type_change_type CHECK (change_type in ('CREATE','UPDATE','DELETE');


CREATE TABLE sp_projects (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_projects_id_pk,
	friendly_identifier varchar(30),
	project_url_name varchar(255),
	initiative_id numeric,
	project varchar(255) NOT NULL,
	upper_project_name varchar(255),
	owner_id numeric,
	active_yn varchar(1) DEFAULT on null 'Y'
                                   constraint sp_projects_active_ck
                                   ),
	priority_id numeric DEFAULT 4
                                   constraint sp_projects_priority_fk
                                   references sp_project_priorities,
	release_id numeric,
	project_group_id numeric,
	release varchar(30),
	target_complete timestamp(0),
	pct_complete numeric DEFAULT 10
                                   constraint sp_projects_pct_complete_ck
                                   ),
	status_id numeric,
	project_size varchar(10),
	status_scale varchar(1) NOT NULL,
	requires_reviews_yn varchar(1) DEFAULT on null 'Y'
                                   constraint sp_projects_req_rev_ck
                                   ),
	doc_impact_yn varchar(1) DEFAULT on null 'N'
                                   constraint sp_projects_doc_impact_cc
                                   ),
	description text,
	kb_stack_rank numeric DEFAULT on null nextval('sp_kb_stack_rank_seq'),
	comments numeric DEFAULT 0,
	links numeric DEFAULT 0,
	documents numeric DEFAULT 0,
	tags varchar(4000),
	focus_area_id numeric,
	display_external_link_yn varchar(1),
	external_ticket_identifier varchar(128),
	external_ticket_system varchar(30),
	external_system_link varchar(4000),
	duplicate_of_project_id numeric,
	archived_yn varchar(1),
	archived_date timestamp(0),
	archived_by varchar(255),
	blocked_by_yn varchar(1),
	blocked_by_project_id numeric,
	blocked_by_comment varchar(4000),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_projects_i1 ON sp_projects (owner_id);
CREATE INDEX sp_projects_i2 ON sp_projects (initiative_id);
CREATE INDEX sp_projects_i3 ON sp_projects (status_scale);
CREATE INDEX sp_projects_i4 ON sp_projects (priority_id);
CREATE INDEX sp_projects_i5 ON sp_projects (updated);
CREATE INDEX sp_projects_i6 ON sp_projects (release_id);
CREATE INDEX sp_projects_i7 ON sp_projects (duplicate_of_project_id);
CREATE INDEX sp_projects_i8 ON sp_projects (pct_complete);
CREATE INDEX sp_projects_u1 ON sp_projects (upper_project_name);
CREATE INDEX sp_projects_u2 ON sp_projects (friendly_identifier);
ALTER TABLE sp_projects ADD UNIQUE (id);
ALTER TABLE sp_projects ADD CONSTRAINT o2pc_active_yn_active_yn CHECK (active_yn in ('Y','N');
ALTER TABLE sp_projects ADD CONSTRAINT o2pc_archived_yn_archived_yn CHECK (archived_yn in ('Y','N');
ALTER TABLE sp_projects ADD CONSTRAINT o2pc_blocked_by_yn_blocked_by_yn CHECK (blocked_by_yn in ('Y','N');
ALTER TABLE sp_projects ADD CONSTRAINT o2pc_display_external_link_yn_display_external_link_yn CHECK (display_external_link_yn in ('Y','N');
ALTER TABLE sp_projects ADD CONSTRAINT o2pc_doc_impact_yn_doc_impact_yn CHECK (doc_impact_yn in ('Y','N');
ALTER TABLE sp_projects ADD CONSTRAINT o2pc_pct_complete_pct_complete CHECK (pct_complete in (0,10,20,30,40,50,60,70,80,90,100);
ALTER TABLE sp_projects ADD CONSTRAINT o2pc_project_size_project_size CHECK (project_size in ('S','M','L','XL','2XL','3XL','4XL','8XL');
ALTER TABLE sp_projects ADD CONSTRAINT o2pc_requires_reviews_yn_requires_reviews_yn CHECK (requires_reviews_yn in ('Y','N');


CREATE TABLE sp_project_related (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_project_related_id_pk,
	project_id numeric NOT NULL,
	related_project_id numeric NOT NULL,
	project_relation varchar(4000),
	relation_type varchar(30),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_project_related_i1 ON sp_project_related (project_id);
CREATE INDEX sp_project_related_i2 ON sp_project_related (related_project_id);
ALTER TABLE sp_project_related ADD UNIQUE (id);
ALTER TABLE sp_project_related ADD CONSTRAINT o2pc_relation_type_relation_type CHECK (relation_type in ('DUPLICATE_OF','RELATED','SUBPROJECT');


CREATE TABLE sp_project_contributors (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_project_contrib_id_pk,
	project_id numeric,
	team_member_id numeric,
	responsibility_id numeric,
	responsibility varchar(4000),
	tags varchar(4000),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_project_contrib_i1 ON sp_project_contributors (project_id);
CREATE INDEX sp_project_contrib_i2 ON sp_project_contributors (team_member_id);
CREATE INDEX sp_project_contrib_i3 ON sp_project_contributors (responsibility_id);
ALTER TABLE sp_project_contributors ADD UNIQUE (id);

CREATE INDEX sp_project_contributors_i4 ON sp_project_contributors (updated);
CREATE INDEX sp_project_contributors_u1 ON sp_project_contributors (team_member_id, project_id);


CREATE TABLE sp_project_documents (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_project_documents_id_pk,
	project_id numeric,
	document_blob bytea,
	document_filename varchar(512),
	document_mimetype varchar(512),
	document_charset varchar(512),
	document_lastupd timestamp(0),
	important_yn varchar(1),
	doc_description varchar(4000),
	tags varchar(4000),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_project_documents_i1 ON sp_project_documents (project_id);
CREATE INDEX sp_project_documents_i2 ON sp_project_documents (updated);
ALTER TABLE sp_project_documents ADD UNIQUE (id);


CREATE TABLE sp_project_history (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_project_history_pk,
	project_id numeric,
	attribute_column varchar(255) NOT NULL,
	change_type varchar(30) NOT NULL,
	old_value varchar(4000),
	new_value varchar(4000),
	old_value_clob text,
	new_value_clob text,
	changed_on timestamp(0) NOT NULL,
	changed_by varchar(255)
) ;
CREATE INDEX sp_project_history_i1 ON sp_project_history (project_id);
CREATE INDEX sp_project_history_i2 ON sp_project_history (changed_by);
ALTER TABLE sp_project_history ADD UNIQUE (id);
ALTER TABLE sp_project_history ADD CONSTRAINT o2pc_change_type_change_type CHECK (change_type in ('CREATE','UPDATE','DELETE');


CREATE TABLE sp_project_links (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_project_links_pk,
	project_id numeric,
	link_name varchar(255) NOT NULL,
	link_url varchar(4000) NOT NULL,
	important_yn varchar(1) DEFAULT on null 'N'
                                   constraint sp_project_links_imp_ck
                                   ),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_project_links_i1 ON sp_project_links (project_id);
CREATE INDEX sp_project_links_i2 ON sp_project_links (updated);
ALTER TABLE sp_project_links ADD UNIQUE (id);
ALTER TABLE sp_project_links ADD CONSTRAINT o2pc_important_yn_important_yn CHECK (important_yn in ('Y','N');


CREATE TABLE sp_project_comments (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_project_comments_id_pk,
	project_id numeric,
	body text,
	body_html text,
	body_no_images text,
	image_ref_id numeric,
	private_yn varchar(1) DEFAULT on null 'Y'
                                   constraint sp_project_comm_private_ck
                                   ),
	author_id numeric,
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_project_comments_i1 ON sp_project_comments (project_id);
CREATE INDEX sp_project_comments_i2 ON sp_project_comments (author_id);
CREATE INDEX sp_project_comments_i3 ON sp_project_comments (updated);
CREATE INDEX sp_project_comments_i4 ON sp_project_comments (image_ref_id);
ALTER TABLE sp_project_comments ADD UNIQUE (id);
ALTER TABLE sp_project_comments ADD CONSTRAINT o2pc_private_yn_private_yn CHECK (private_yn in ('Y','N');


CREATE TABLE sp_project_comments_emails (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_proj_comment_em_id_pk,
	comment_id numeric,
	email varchar(255)
) ;
CREATE INDEX sp_project_comm_emails_i1 ON sp_project_comments_emails (comment_id);
CREATE INDEX sp_project_comm_emails_i2 ON sp_project_comments_emails (email);
ALTER TABLE sp_project_comments_emails ADD UNIQUE (id);


CREATE TABLE sp_release_comments (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_release_comments_id_pk,
	release_id numeric,
	body text,
	body_html text,
	body_no_images text,
	image_ref_id numeric,
	author_id numeric,
	private_yn varchar(1),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_release_comments_i1 ON sp_release_comments (release_id);
CREATE INDEX sp_release_comments_i2 ON sp_release_comments (author_id);
CREATE INDEX sp_release_comments_i3 ON sp_release_comments (image_ref_id);
ALTER TABLE sp_release_comments ADD UNIQUE (id);


CREATE TABLE sp_comment_images (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                           constraint sp_comment_images_pk,
	file_blob bytea NOT NULL,
	filename varchar(512),
	mimetype varchar(512),
	blob_size numeric,
	image_ref_id numeric NOT NULL,
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_comment_images_i1 ON sp_comment_images (image_ref_id);
ALTER TABLE sp_comment_images ADD UNIQUE (id);


CREATE TABLE sp_release_milestone_types (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_release_milestone_types_pk,
	milestone_type varchar(60) NOT NULL,
	include_yn varchar(1) DEFAULT on null 'Y',
	display_seq numeric,
	calendar_event_color varchar(30),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
ALTER TABLE sp_release_milestone_types ADD UNIQUE (id);

ALTER TABLE sp_release_milestone_types ADD CONSTRAINT sp_release_milestone_types_include_cc CHECK (include_yn in ('Y','N'));


CREATE TABLE sp_release_milestones (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_release_milestone_pk,
	release_id numeric NOT NULL,
	milestone_name varchar(255) NOT NULL,
	upper_milestone_name varchar(255) NOT NULL,
	milestone_type_id numeric,
	milestone_start_date timestamp(0),
	milestone_date timestamp(0) NOT NULL,
	original_milestone_date timestamp(0),
	milestone_completed_yn varchar(1) DEFAULT on null 'N',
	milestone_description varchar(4000),
	tags varchar(4000),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_release_milestones_i1 ON sp_release_milestones (upper_milestone_name, release_id, milestone_type_id);
ALTER TABLE sp_release_milestones ADD UNIQUE (id);


CREATE TABLE sp_release_milestone_default_tags (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_release_milestone_default_tags_pk,
	display_sequence numeric NOT NULL,
	tag varchar(30) NOT NULL,
	description varchar(512),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
ALTER TABLE sp_release_milestone_default_tags ADD UNIQUE (id);


CREATE TABLE sp_release_documents (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_release_documents_pk,
	release_id numeric,
	document_blob bytea,
	document_filename varchar(512),
	document_mimetype varchar(512),
	document_charset varchar(512),
	document_lastupd timestamp(0),
	important_yn varchar(1),
	doc_description varchar(4000),
	tags varchar(4000),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_release_documents_i1 ON sp_release_documents (release_id);
CREATE INDEX sp_release_documents_i2 ON sp_release_documents (updated);
ALTER TABLE sp_release_documents ADD UNIQUE (id);


CREATE TABLE sp_countries (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                      constraint sp_countries_pk,
	country_code varchar(2) NOT NULL,
	country_code3 varchar(3),
	country_name varchar(255) NOT NULL,
	region varchar(30) NOT NULL,
	display_yn varchar(1) NOT NULL,
	quick_pick_yn varchar(1) NOT NULL,
	lat numeric,
	lon numeric,
	created timestamp(0),
	created_by varchar(255),
	updated timestamp(0),
	updated_by varchar(255)
) ;
CREATE INDEX sp_countries_i1 ON sp_countries (country_code);
CREATE INDEX sp_countries_i2 ON sp_countries (country_name);
ALTER TABLE sp_countries ADD UNIQUE (id);


CREATE TABLE sp_external_ticketing_systems (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint SP_EXTERNAL_TICKETING_SYS_PK,
	external_system_name varchar(30) NOT NULL,
	description varchar(4000),
	is_active_yn varchar(1) NOT NULL,
	link_pattern varchar(4000) NOT NULL,
	min_id_length numeric,
	max_id_length numeric,
	must_contain varchar(255),
	ticket_id_regex varchar(255) NOT NULL,
	evaulation_sequence numeric,
	required_initiative_id numeric,
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
ALTER TABLE sp_external_ticketing_systems ADD UNIQUE (id);


CREATE TABLE sp_notifications (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_notifications_id_pk,
	name varchar(150) NOT NULL,
	static_id varchar(30) NOT NULL,
	description varchar(4000) NOT NULL,
	is_active_yn varchar(1) NOT NULL,
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
ALTER TABLE sp_notifications ADD UNIQUE (id);


CREATE TABLE sp_notifications (
) ;
CREATE INDEX sp_notifications_u1 ON sp_notifications (name);


CREATE TABLE sp_notification_subscriptions (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_notification_subscriptions_pk,
	team_member_id numeric NOT NULL,
	notification_id numeric NOT NULL,
	release_id numeric,
	opted_in_yn varchar(1) NOT NULL,
	frequency varchar(30) NOT NULL,
	last_sent timestamp(0),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_notification_subscriptions_i1 ON sp_notification_subscriptions (notification_id);
CREATE INDEX sp_notification_subscriptions_i2 ON sp_notification_subscriptions (release_id);
CREATE INDEX sp_notification_subscriptions_u1 ON sp_notification_subscriptions (team_member_id, notification_id, nullif(release_id, 1));
ALTER TABLE sp_notification_subscriptions ADD UNIQUE (id);
ALTER TABLE sp_notification_subscriptions ADD CONSTRAINT o2pc_frequency_frequency CHECK (frequency in ('WEEKDAYS','WEEKLY');
ALTER TABLE sp_notification_subscriptions ADD CONSTRAINT o2pc_opted_in_yn_opted_in_yn CHECK (opted_in_yn in ('Y','N');


CREATE TABLE sp_proj_interactions_log (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_proj_interactions_log_pk,
	project_id numeric,
	app_page numeric NOT NULL,
	app_user varchar(255) NOT NULL,
	action varchar(50) NOT NULL,
	page_rendered timestamp(0)
) ;
CREATE INDEX sp_proj_interactions_log_i1 ON sp_proj_interactions_log (project_id);
CREATE INDEX sp_proj_interactions_log_i2 ON sp_proj_interactions_log (app_user);
ALTER TABLE sp_proj_interactions_log ADD UNIQUE (id);


CREATE TABLE sp_activity_types (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_activity_types_pk,
	display_sequence numeric NOT NULL,
	activity_type varchar(50) NOT NULL,
	activity_type_description varchar(4000),
	is_project_yn varchar(1),
	static_id varchar(30),
	is_default_yn varchar(1),
	is_active_yn varchar(1),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
ALTER TABLE sp_activity_types ADD UNIQUE (id);


CREATE TABLE sp_activities (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_activities_pk,
	activity_type_id numeric,
	project_id numeric,
	team_member_id numeric,
	initiative_id numeric,
	start_date timestamp(0) NOT NULL,
	end_date timestamp(0) NOT NULL,
	comments varchar(4000),
	ticket_number varchar(50),
	url varchar(500),
	activity_status varchar(30),
	tags varchar(4000),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_activities_i1 ON sp_activities (activity_type_id);
CREATE INDEX sp_activities_i2 ON sp_activities (project_id);
CREATE INDEX sp_activities_i3 ON sp_activities (team_member_id);
CREATE INDEX sp_activities_i4 ON sp_activities (end_date);
CREATE INDEX sp_activities_i5 ON sp_activities (start_date);
CREATE INDEX sp_activities_i6 ON sp_activities (initiative_id);
ALTER TABLE sp_activities ADD UNIQUE (id);


CREATE TABLE sp_favorites (
	id numeric NOT NULL DEFAULT on null to_number(uuid_generate_v4(), 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'),
	project_id numeric,
	team_member_id numeric,
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_favorites_i1 ON sp_favorites (project_id, team_member_id);


CREATE TABLE sp_configurable_text (
	id numeric NOT NULL DEFAULT on null to_number(uuid_generate_v4(), 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'),
	config_id varchar(50) NOT NULL,
	description varchar(4000) NOT NULL,
	configurable_content text,
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;


CREATE TABLE sp_default_people_tags (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint SP_DEFAULT_PEOPLE_TAGS_pk,
	display_sequence numeric NOT NULL,
	tag varchar(30) NOT NULL,
	description varchar(512),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_default_people_tags_u1 ON sp_default_people_tags (tag);
ALTER TABLE sp_default_people_tags ADD UNIQUE (id);


CREATE TABLE sp_application_notifications (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint SP_APPLICATION_NOTIFICATIONS_PK,
	notification_name varchar(128) NOT NULL,
	notification_description varchar(4000),
	is_active_yn varchar(1) NOT NULL,
	required_user_tag varchar(30),
	from_date timestamp(0),
	to_date timestamp(0),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_application_notifications_u1 ON sp_application_notifications (notification_name);
ALTER TABLE sp_application_notifications ADD UNIQUE (id);


CREATE TABLE sp_initiative_comments (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_initiative_comments_pk,
	initiative_id numeric,
	body text,
	body_html text,
	body_no_images text,
	image_ref_id numeric,
	author_id numeric,
	private_yn varchar(1),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_initiative_comments_i1 ON sp_initiative_comments (initiative_id);
CREATE INDEX sp_initiative_comments_i2 ON sp_initiative_comments (author_id);
CREATE INDEX sp_initiative_comments_i3 ON sp_initiative_comments (image_ref_id);
ALTER TABLE sp_initiative_comments ADD UNIQUE (id);


CREATE TABLE sp_release_links (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint SP_release_links_PK,
	release_id numeric,
	link_name varchar(255) NOT NULL,
	link_url varchar(4000),
	important_yn varchar(1) DEFAULT on null 'N'
                                   constraint sp_release_links_imp_cc
                                   ),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_release_links_u1 ON sp_release_links (release_id, link_name);
CREATE INDEX sp_release_links_i1 ON sp_release_links (release_id);
ALTER TABLE sp_release_links ADD UNIQUE (id);
ALTER TABLE sp_release_links ADD CONSTRAINT o2pc_important_yn_important_yn CHECK (important_yn in ('Y','N');


CREATE TABLE sp_initiative_links (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint SP_initiative_links_PK,
	initiative_id numeric,
	link_name varchar(255) NOT NULL,
	link_url varchar(4000),
	important_yn varchar(1) DEFAULT on null 'N'
                                   constraint sp_initiative_links_imp_ck
                                   ),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_initiative_links_u1 ON sp_initiative_links (initiative_id, link_name);
CREATE INDEX sp_initiative_links_u2 ON sp_initiative_links (initiative_id, link_url);
CREATE INDEX sp_initiative_links_i1 ON sp_initiative_links (initiative_id);
ALTER TABLE sp_initiative_links ADD UNIQUE (id);
ALTER TABLE sp_initiative_links ADD CONSTRAINT o2pc_important_yn_important_yn CHECK (important_yn in ('Y','N');


CREATE TABLE sp_initiative_documents (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_initiative_documents_pk,
	initiative_id numeric,
	document_blob bytea,
	document_filename varchar(512),
	document_mimetype varchar(512),
	document_charset varchar(512),
	document_lastupd timestamp(0),
	important_yn varchar(1),
	doc_description varchar(4000),
	tags varchar(4000),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_initiative_documents_i1 ON sp_initiative_documents (initiative_id);
CREATE INDEX sp_initiative_documents_i2 ON sp_initiative_documents (updated);
ALTER TABLE sp_initiative_documents ADD UNIQUE (id);


CREATE TABLE sp_task_types (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_task_types_pk,
	task_type varchar(100) NOT NULL,
	static_id varchar(30),
	description varchar(4000),
	display_seq numeric,
	include_yn varchar(1) DEFAULT on null 'Y'
                                   constraint sp_task_types_include_ck
                                   ),
	task_name_req_yn varchar(1) DEFAULT on null 'N'
                                   constraint sp_task_types_task_name_req_ck
                                   ),
	parent_type_id numeric,
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_task_types_u1 ON sp_task_types (parent_type_id, task_type);
CREATE INDEX sp_task_types_u2 ON sp_task_types (static_id);
ALTER TABLE sp_task_types ADD UNIQUE (id);
ALTER TABLE sp_task_types ADD CONSTRAINT o2pc_include_yn_include_yn CHECK (include_yn in ('Y','N');
ALTER TABLE sp_task_types ADD CONSTRAINT o2pc_task_name_req_yn_task_name_req_yn CHECK (task_name_req_yn in ('Y','N');


CREATE TABLE sp_initiative_default_tasks (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_ini_def_tasks_pk,
	initiative_id numeric NOT NULL,
	type_id numeric NOT NULL,
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_initiative_default_tasks_u1 ON sp_initiative_default_tasks (initiative_id, type_id);
ALTER TABLE sp_initiative_default_tasks ADD UNIQUE (id);


CREATE TABLE sp_task_statuses (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_task_statuses_pk,
	task_type_id numeric NOT NULL,
	status varchar(100) NOT NULL,
	static_id varchar(30) NOT NULL,
	display_seq numeric,
	include_yn varchar(1) DEFAULT on null 'Y'
                                   constraint sp_task_statuses_include_ck
                                   ),
	is_default_yn varchar(1) DEFAULT on null 'N'
                                   constraint sp_task_statuses_default_ck
                                   ),
	indicates_complete_yn varchar(1) DEFAULT on null 'N'
                                   constraint sp_task_statuses_ind_complete_ck
                                   ),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_task_statuses_u1 ON sp_task_statuses (task_type_id, status);
CREATE INDEX sp_task_statuses_u2 ON sp_task_statuses (task_type_id, static_id);
ALTER TABLE sp_task_statuses ADD UNIQUE (id);
ALTER TABLE sp_task_statuses ADD CONSTRAINT o2pc_include_yn_include_yn CHECK (include_yn in ('Y','N');
ALTER TABLE sp_task_statuses ADD CONSTRAINT o2pc_indicates_complete_yn_indicates_complete_yn CHECK (indicates_complete_yn in ('Y','N');
ALTER TABLE sp_task_statuses ADD CONSTRAINT o2pc_is_default_yn_is_default_yn CHECK (is_default_yn in ('Y','N');


CREATE TABLE sp_tasks (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_tasks_id_pk,
	project_id numeric NOT NULL,
	task varchar(255),
	task_type_id numeric NOT NULL,
	task_sub_type_id numeric,
	owner_id numeric,
	start_date timestamp(0),
	target_complete timestamp(0),
	status_id numeric NOT NULL,
	status_last_changed_on timestamp(0),
	description varchar(4000),
	tags varchar(4000),
	impact varchar(30),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_tasks_i1 ON sp_tasks (project_id);
CREATE INDEX sp_tasks_i2 ON sp_tasks (task_type_id);
CREATE INDEX sp_tasks_i3 ON sp_tasks (task_sub_type_id);
CREATE INDEX sp_tasks_i4 ON sp_tasks (owner_id);
ALTER TABLE sp_tasks ADD UNIQUE (id);
ALTER TABLE sp_tasks ADD CONSTRAINT o2pc_impact_impact CHECK (impact in ('Not Identified','None','Low','Medium','High');


CREATE TABLE sp_task_history (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_task_history_pk,
	task_id numeric NOT NULL,
	attribute_column varchar(255) NOT NULL,
	change_type varchar(30) NOT NULL,
	old_value varchar(4000),
	new_value varchar(4000),
	old_value_clob text,
	new_value_clob text,
	changed_on timestamp(0) NOT NULL,
	changed_by varchar(255)
) ;
CREATE INDEX sp_task_history_i1 ON sp_task_history (task_id);
CREATE INDEX sp_task_history_i2 ON sp_task_history (changed_by);
ALTER TABLE sp_task_history ADD UNIQUE (id);
ALTER TABLE sp_task_history ADD CONSTRAINT o2pc_change_type_change_type CHECK (change_type in ('CREATE','UPDATE','DELETE');


CREATE TABLE sp_task_links (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_task_links_pk,
	task_id numeric NOT NULL,
	link_name varchar(255) NOT NULL,
	link_url varchar(4000) NOT NULL,
	important_yn varchar(1) DEFAULT on null 'N'
                                   constraint sp_task_links_imp_ck
                                   ),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_task_links_i1 ON sp_task_links (task_id);
CREATE INDEX sp_task_links_i2 ON sp_task_links (updated);
ALTER TABLE sp_task_links ADD UNIQUE (id);
ALTER TABLE sp_task_links ADD CONSTRAINT o2pc_important_yn_important_yn CHECK (important_yn in ('Y','N');


CREATE TABLE sp_task_documents (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_task_documents_pk,
	task_id numeric NOT NULL,
	document_blob bytea,
	document_filename varchar(512),
	document_mimetype varchar(512),
	document_charset varchar(512),
	document_lastupd timestamp(0),
	important_yn varchar(1),
	doc_description varchar(4000),
	tags varchar(4000),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_task_documents_i1 ON sp_task_documents (task_id);
CREATE INDEX sp_task_documents_i2 ON sp_task_documents (updated);
ALTER TABLE sp_task_documents ADD UNIQUE (id);


CREATE TABLE sp_task_comments (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_task_comments_pk,
	task_id numeric NOT NULL,
	body text,
	body_html text,
	body_no_images text,
	image_ref_id numeric,
	author_id numeric,
	private_yn varchar(1),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_task_comments_i1 ON sp_task_comments (task_id);
CREATE INDEX sp_task_comments_i2 ON sp_task_comments (author_id);
CREATE INDEX sp_task_comments_i3 ON sp_task_comments (image_ref_id);
ALTER TABLE sp_task_comments ADD UNIQUE (id);


CREATE TABLE sp_team_member_notifications (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_team_member_notifications_pk,
	team_member_id numeric NOT NULL,
	notification_pref varchar(255),
	title varchar(255) NOT NULL,
	email_contents varchar(4000),
	notification_type varchar(30),
	project_id numeric,
	task_id numeric,
	release_id numeric,
	initiative_id numeric,
	dismissed_yn varchar(1) DEFAULT on null 'N'
                                   constraint sp_team_member_notifications_dismissed_cc
                                   ),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_team_member_notifications_i1 ON sp_team_member_notifications (team_member_id);
CREATE INDEX sp_team_member_notifications_i2 ON sp_team_member_notifications (project_id);
CREATE INDEX sp_team_member_notifications_i3 ON sp_team_member_notifications (created);
ALTER TABLE sp_team_member_notifications ADD UNIQUE (id);
ALTER TABLE sp_team_member_notifications ADD CONSTRAINT o2pc_dismissed_yn_dismissed_yn CHECK (dismissed_yn in ('Y','N');


CREATE TABLE sp_approval_types (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_approval_types_pk,
	display_seq numeric NOT NULL,
	approval_type varchar(30) NOT NULL,
	description varchar(4000),
	active_yn varchar(1) DEFAULT on null 'Y'
                                   constraint sp_approval_types_active_cc
                                   ),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
ALTER TABLE sp_approval_types ADD UNIQUE (id);
ALTER TABLE sp_approval_types ADD CONSTRAINT o2pc_active_yn_active_yn CHECK (active_yn in ('Y','N');


CREATE TABLE sp_initiative_approvals (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_initiative_approvals_pk,
	initiative_id numeric,
	approval_type_id numeric NOT NULL,
	active_yn varchar(1) DEFAULT on null 'Y'
                                   constraint sp_initiative_approvals_active_cc
                                   ),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_initiative_approvals_i1 ON sp_initiative_approvals (approval_type_id);
ALTER TABLE sp_initiative_approvals ADD UNIQUE (id);
ALTER TABLE sp_initiative_approvals ADD CONSTRAINT o2pc_active_yn_active_yn CHECK (active_yn in ('Y','N');


CREATE TABLE sp_initiative_approval_chain (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_initiative_approval_chain_pk,
	initiative_approval_id numeric NOT NULL,
	team_member_id numeric,
	approval_seq numeric NOT NULL,
	active_yn varchar(1) DEFAULT on null 'Y'
                                   constraint sp_initiative_approval_chain_active_cc
                                   ),
	alternate_team_member_id numeric,
	alternate_start_date timestamp(0),
	alternate_end_date timestamp(0),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_initiative_approval_chain_i1 ON sp_initiative_approval_chain (team_member_id);
ALTER TABLE sp_initiative_approval_chain ADD UNIQUE (id);
ALTER TABLE sp_initiative_approval_chain ADD CONSTRAINT o2pc_active_yn_active_yn CHECK (active_yn in ('Y','N');


CREATE TABLE sp_project_approvals (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_project_approvals_pk,
	approval_type_id numeric NOT NULL,
	project_id numeric NOT NULL,
	submitted_by_team_member_id numeric NOT NULL,
	justification varchar(4000) NOT NULL,
	submitted timestamp(0) NOT NULL,
	initiative_approval_id numeric,
	status varchar(30) DEFAULT on null 'PENDING',
	withdrawn_by_team_member_id numeric,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_project_approvals_i1 ON sp_project_approvals (approval_type_id);
CREATE INDEX sp_project_approvals_i2 ON sp_project_approvals (project_id);
CREATE INDEX sp_project_approvals_i3 ON sp_project_approvals (submitted_by_team_member_id);
CREATE INDEX sp_project_approvals_i4 ON sp_project_approvals (initiative_approval_id);
ALTER TABLE sp_project_approvals ADD UNIQUE (id);


CREATE TABLE sp_project_approval_chain (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                                   constraint sp_project_approval_chain_pk,
	project_approval_id numeric NOT NULL,
	initiative_approval_chain_id numeric,
	team_member_id numeric NOT NULL,
	status varchar(30) DEFAULT on null 'PENDING',
	last_status_on timestamp(0) DEFAULT on null statement_timestamp(),
	comments varchar(4000),
	response varchar(4000),
	response_by_team_member_id numeric,
	responded_on timestamp(0),
	final_yn varchar(1) DEFAULT on null 'Y'
                                      constraint sp_project_approval_chain_final_cc
                                      ),
	created timestamp(0) NOT NULL,
	created_by varchar(255) NOT NULL,
	updated timestamp(0) NOT NULL,
	updated_by varchar(255) NOT NULL
) ;
CREATE INDEX sp_project_approval_chain_i1 ON sp_project_approval_chain (project_approval_id);
CREATE INDEX sp_project_approval_chain_i2 ON sp_project_approval_chain (initiative_approval_chain_id);
CREATE INDEX sp_project_approval_chain_i3 ON sp_project_approval_chain (team_member_id);
CREATE INDEX sp_project_approval_chain_i4 ON sp_project_approval_chain (response_by_team_member_id);
ALTER TABLE sp_project_approval_chain ADD UNIQUE (id);
ALTER TABLE sp_project_approval_chain ADD CONSTRAINT o2pc_final_yn_final_yn CHECK (final_yn in ('Y','N');


CREATE TABLE sp_project_ai_summaries (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                          constraint sp_project_ai_summaries_pk,
	project_id numeric,
	summary_type varchar(30),
	prompt_sent text,
	details_sent text,
	data_received text,
	summary text,
	risk varchar(100),
	highlights varchar(4000),
	created timestamp(0) DEFAULT on null statement_timestamp()
) ;
CREATE INDEX sp_project_ai_summaries_i1 ON sp_project_ai_summaries (project_id);
CREATE INDEX sp_project_ai_summaries_i2 ON sp_project_ai_summaries (created);
ALTER TABLE sp_project_ai_summaries ADD UNIQUE (id);


CREATE TABLE sp_release_ai_summaries (
	id numeric DEFAULT on null to_number(uuid_generate_v4(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
                          constraint sp_release_ai_summaries_pk,
	release_id numeric,
	prompt_sent text,
	details_sent text,
	data_received text,
	summary text,
	highlights varchar(4000),
	created timestamp(0) DEFAULT on null statement_timestamp()
) ;
CREATE INDEX sp_release_ai_summaries_i1 ON sp_release_ai_summaries (release_id);
CREATE INDEX sp_release_ai_summaries_i2 ON sp_release_ai_summaries (created);
ALTER TABLE sp_release_ai_summaries ADD UNIQUE (id);
ALTER TABLE sp_external_ticketing_systems ADD CONSTRAINT o2pf_required_initiative_id FOREIGN KEY (required_initiative_id) REFERENCES sp_initiatives(id) ON DELETE NO ACTION INITIALLY IMMEDIATE;
ALTER TABLE sp_group_members ADD CONSTRAINT o2pf_group_id FOREIGN KEY (group_id) REFERENCES sp_groups(id) ON DELETE NO ACTION INITIALLY IMMEDIATE;

ALTER TABLE sp_group_members ADD CONSTRAINT o2pf_team_member_id FOREIGN KEY (team_member_id) REFERENCES sp_team_members(id) ON DELETE NO ACTION INITIALLY IMMEDIATE;
ALTER TABLE sp_initiative_links ADD CONSTRAINT o2pf_initiative_id FOREIGN KEY (initiative_id) REFERENCES sp_initiatives(id) ON DELETE NO ACTION INITIALLY IMMEDIATE;
ALTER TABLE sp_release_links ADD CONSTRAINT o2pf_release_id FOREIGN KEY (release_id) REFERENCES sp_release_trains(id) ON DELETE NO ACTION INITIALLY IMMEDIATE;
ALTER TABLE sp_activities ADD CONSTRAINT o2pf_activity_type_id FOREIGN KEY (activity_type_id) REFERENCES sp_activity_types(id) ON DELETE NO ACTION INITIALLY IMMEDIATE;

ALTER TABLE sp_activities ADD CONSTRAINT o2pf_initiative_id FOREIGN KEY (initiative_id) REFERENCES sp_initiatives(id) ON DELETE NO ACTION INITIALLY IMMEDIATE;

ALTER TABLE sp_activities ADD CONSTRAINT o2pf_project_id FOREIGN KEY (project_id) REFERENCES sp_projects(id) ON DELETE NO ACTION INITIALLY IMMEDIATE;

ALTER TABLE sp_activities ADD CONSTRAINT o2pf_team_member_id FOREIGN KEY (team_member_id) REFERENCES sp_team_members(id) ON DELETE NO ACTION INITIALLY IMMEDIATE;
ALTER TABLE sp_favorites ADD CONSTRAINT o2pf_project_id FOREIGN KEY (project_id) REFERENCES sp_projects(id) ON DELETE NO ACTION INITIALLY IMMEDIATE;

ALTER TABLE sp_favorites ADD CONSTRAINT o2pf_team_member_id FOREIGN KEY (team_member_id) REFERENCES sp_team_members(id) ON DELETE NO ACTION INITIALLY IMMEDIATE;
ALTER TABLE sp_initiative_comments ADD CONSTRAINT o2pf_initiative_id FOREIGN KEY (initiative_id) REFERENCES sp_initiatives(id) ON DELETE NO ACTION INITIALLY IMMEDIATE;
ALTER TABLE sp_initiative_focus_areas ADD CONSTRAINT o2pf_development_owner_id FOREIGN KEY (development_owner_id) REFERENCES sp_team_members(id) ON DELETE NO ACTION INITIALLY IMMEDIATE;
ALTER TABLE sp_notification_subscriptions ADD CONSTRAINT o2pf_notification_id FOREIGN KEY (notification_id) REFERENCES sp_notifications(id) ON DELETE NO ACTION INITIALLY IMMEDIATE;

ALTER TABLE sp_notification_subscriptions ADD CONSTRAINT o2pf_release_id FOREIGN KEY (release_id) REFERENCES sp_release_trains(id) ON DELETE NO ACTION INITIALLY IMMEDIATE;

ALTER TABLE sp_notification_subscriptions ADD CONSTRAINT o2pf_team_member_id FOREIGN KEY (team_member_id) REFERENCES sp_team_members(id) ON DELETE NO ACTION INITIALLY IMMEDIATE;
ALTER TABLE sp_proj_interactions_log ADD CONSTRAINT o2pf_project_id FOREIGN KEY (project_id) REFERENCES sp_projects(id) ON DELETE NO ACTION INITIALLY IMMEDIATE;
ALTER TABLE sp_project_comments_emails ADD CONSTRAINT o2pf_comment_id FOREIGN KEY (comment_id) REFERENCES sp_project_comments(id) ON DELETE NO ACTION INITIALLY IMMEDIATE;
ALTER TABLE sp_release_milestones ADD CONSTRAINT o2pf_milestone_type_id FOREIGN KEY (milestone_type_id) REFERENCES sp_release_milestone_types(id) ON DELETE NO ACTION INITIALLY IMMEDIATE;

ALTER TABLE sp_release_milestones ADD CONSTRAINT o2pf_release_id FOREIGN KEY (release_id) REFERENCES sp_release_trains(id) ON DELETE NO ACTION INITIALLY IMMEDIATE;
