prompt --application/deployment/install/install_sp_comment_util_spec
begin
--   Manifest
--     INSTALL: INSTALL-sp_comment_util spec
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.15'
,p_default_workspace_id=>20
,p_default_application_id=>7150
,p_default_id_offset=>1539581868058128
,p_default_owner=>'ORACLE'
);
wwv_flow_imp_shared.create_install_script(
 p_id=>wwv_flow_imp.id(22991757595204877552)
,p_install_id=>wwv_flow_imp.id(176222573236493322734)
,p_name=>'sp_comment_util spec'
,p_sequence=>35
,p_script_type=>'INSTALL'
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'create or replace package sp_comment_util as',
'',
'-- used in the views to swap in current user''s session id',
'function replace_session_on_display (',
'    p_body        in  clob,',
'    p_session_id  in  number )',
'    return clob;',
'',
'-------------------------------',
'',
'procedure add_initiative_comment (',
'    p_app_user_id     in  number,',
'    p_comment         in  varchar2,',
'    p_private_yn      in  varchar2 default ''N'',',
'    p_initiative_id   in  number,',
'    p_image_ref_id    in  number   default null );',
'',
'procedure update_initiative_comment (',
'    p_comment_id      in  number,',
'    p_comment         in  varchar2,',
'    p_private_yn      in  varchar2 default ''N'',',
'    p_image_ref_id    in  number   default null );',
'',
'procedure delete_initiative_comment (',
'    p_comment_id      in  number );',
'',
'',
'procedure add_project_comment (',
'    p_app_user_id     in  number,',
'    p_app_user        in  varchar2,',
'    p_comment         in  varchar2,',
'    p_private_yn      in  varchar2 default ''N'',',
'    p_project_id      in  number,',
'    p_system_gen_yn   in  varchar2 default ''N'',',
'    p_app_id          in  number   default null,',
'    p_permalink_pre   in  varchar2 default null,',
'    p_nomen_sp        in  varchar2 default null,',
'    p_nomen_project   in  varchar2 default null,',
'    p_image_ref_id    in  number   default null );',
'',
'procedure update_project_comment (',
'    p_comment_id      in  number,',
'    p_comment         in  varchar2,',
'    p_private_yn      in  varchar2 default ''N'',',
'    p_image_ref_id    in  number   default null );',
'',
'procedure delete_project_comment (',
'    p_comment_id      in  number );',
'',
'',
'procedure add_task_comment (',
'    p_app_user_id     in  number,',
'    p_app_user        in  varchar2,',
'    p_comment         in  varchar2,',
'    p_private_yn      in  varchar2 default ''N'',',
'    p_project_id      in  number,',
'    p_task_id         in  number,',
'    p_app_id          in  number,',
'    p_link            in  varchar2,',
'    p_nomen_sp        in  varchar2,',
'    p_image_ref_id    in  number   default null );',
'',
'procedure update_task_comment (',
'    p_comment_id      in  number,',
'    p_comment         in  varchar2,',
'    p_private_yn      in  varchar2 default ''N'',',
'    p_image_ref_id    in  number   default null );',
'',
'procedure delete_task_comment (',
'    p_comment_id      in  number );',
'',
'',
'procedure add_release_comment (',
'    p_app_user_id     in  number,',
'    p_comment         in varchar2,',
'    p_release_id      in number,',
'    p_private_yn      in varchar2 default ''N'',',
'    p_image_ref_id    in  number   default null );',
'',
'procedure update_release_comment (',
'    p_comment_id      in  number,',
'    p_comment         in  varchar2,',
'    p_private_yn      in  varchar2 default ''N'',',
'    p_image_ref_id    in  number   default null );',
'',
'procedure delete_release_comment (',
'    p_comment_id      in  number );',
'',
'',
' procedure add_init_focus_area_comment (',
'    p_app_user_id         in  number,',
'    p_comment             in  varchar2,',
'    p_init_focus_area_id  in  number,',
'    p_private_yn          in  varchar2 default ''N'',',
'    p_image_ref_id        in  number   default null );',
'',
'procedure update_init_focus_area_comment (',
'    p_comment_id      in  number,',
'    p_comment         in  varchar2,',
'    p_private_yn      in  varchar2 default ''N'',',
'    p_image_ref_id    in  number   default null );',
'',
'procedure delete_init_focus_area_comment (',
'    p_comment_id      in  number );',
'',
'----------------------',
'',
'procedure upload_image (',
'    p_file_base64           in  clob,',
'    p_filename              in  varchar2,',
'    p_mimetype              in  varchar2,',
'    p_image_ref_id          in  number );',
'',
'procedure display_image (',
'    p_unique_filename  in  varchar2 );',
'',
'end sp_comment_util;',
'/'))
);
wwv_flow_imp.component_end;
end;
/
