import { useEffect, useId, useState, type ComponentProps, type ComponentType } from "react";
import { Icon, Tooltip } from "@trussworks/react-uswds";
import type { AsOf, Freshness } from "../hooks/useApi";
import { formatDateTime, formatRelative } from "../lib/format";

export interface AsOfBadgeProps {
  asOf: AsOf | null | undefined;
  /** Optional override of the freshness label shown, e.g. for a feed-level summary. */
  prefix?: string;
  /** Re-render interval for the relative time in ms, 0 to disable. */
  tickMs?: number;
  className?: string;
}

interface FreshnessMeta {
  label: string;
  Icon: ComponentType<ComponentProps<typeof Icon.Info>>;
  hint: string;
}

const FRESHNESS: Record<Freshness, FreshnessMeta> = {
  fresh: { label: "Fresh", Icon: Icon.CheckCircle, hint: "Updated within the expected interval" },
  aging: { label: "Aging", Icon: Icon.Schedule, hint: "Older than expected, still shown" },
  stale: { label: "Stale", Icon: Icon.Warning, hint: "Beyond the stale threshold, treat with caution" },
  simulated: { label: "Simulated", Icon: Icon.Science, hint: "Generated by the demo feed simulator, not a live source" },
};

const SOURCE_LABEL: Record<string, string> = {
  lpms: "USACE Lock Performance Monitoring System (public)",
  synthetic: "Synthetic demo data",
  simulated: "Simulated feed",
  fixtures: "Repository fixtures",
  "cited-public": "Cited public documents",
  "axe-core": "axe-core scan",
};

function sourceLabel(source: string | null | undefined): string {
  if (!source) return "Unknown source";
  return SOURCE_LABEL[source] ?? source;
}

/** Relative + absolute source time, freshness with icon + text, polite live region, tooltip with fetched_at and source. */
export function AsOfBadge({ asOf, prefix = "Data as of", tickMs = 30000, className }: AsOfBadgeProps) {
  const [now, setNow] = useState(() => new Date());
  const tipId = useId();
  useEffect(() => {
    if (!tickMs) return;
    const t = setInterval(() => setNow(new Date()), tickMs);
    return () => clearInterval(t);
  }, [tickMs]);

  const freshness: Freshness = asOf?.freshness ?? "stale";
  const meta = FRESHNESS[freshness] ?? FRESHNESS.stale;
  const FreshIcon = meta.Icon;
  const sourceAt = asOf?.source_as_of ?? null;
  const relative = formatRelative(sourceAt, now);
  const absolute = formatDateTime(sourceAt);
  const tooltip = `Fetched ${formatDateTime(asOf?.fetched_at)}. Source: ${sourceLabel(asOf?.source)}. ${meta.hint}.`;
  const classes = ["evs-asof", `evs-asof--${freshness}`, className].filter(Boolean).join(" ");

  return (
    <div className={classes} aria-live="polite" aria-atomic="true" data-testid="as-of-badge">
      <span className="evs-asof__fresh">
        <FreshIcon aria-hidden="true" focusable={false} />
        {meta.label}
      </span>
      <span className="evs-asof__time">
        {prefix} <time dateTime={sourceAt ?? undefined}>{relative}</time> <span className="evs-as-of__absolute">({absolute})</span>
      </span>
      <Tooltip label={tooltip} position="top" className="usa-button usa-button--unstyled evs-asof__info" aria-describedby={tipId} type="button">
        <Icon.Info aria-hidden="true" focusable={false} />
        <span className="evs-sr-only">About this timestamp</span>
      </Tooltip>
      <span id={tipId} className="evs-sr-only">{tooltip}</span>
    </div>
  );
}
