prompt --application/deployment/install/install_tables
begin
wwv_flow_imp_shared.create_install_script(
 p_id=>wwv_flow_imp.id(701)
,p_install_id=>wwv_flow_imp.id(700)
,p_name=>'tables'
,p_sequence=>10
,p_script_type=>'INSTALL'
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'create table sp_projects (',
'  id number generated by default on null as identity primary key,',
'  name varchar2(255) not null',
');',
''))
);
wwv_flow_imp_shared.append_to_install_script(
 p_id=>wwv_flow_imp.id(701)
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'create or replace view sp_projects_v as select id, name from sp_projects;',
''))
);
end;
/
