"""Turn raw ora2pg output (output/*.sql) into runnable migrations.

ora2pg converts the bulk of the DDL mechanically. The rules below cover the Oracle 12c+ and
APEX-specific constructs it leaves behind; each rule is named so the assessment can list them.
Writes:
  ../migrations/0002_legacy_sp_schema.sql  sequences, tables, indexes, constraints, views, triggers
  ../migrations/0003_legacy_sp_data.sql    seed + sample rows shipped with the APEX app
  ASSESSMENT.md                            cost summary assembled from the per-type ora2pg output
"""

from __future__ import annotations

import re
from collections.abc import Callable
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE / "output"
MIGRATIONS = HERE.parent / "migrations"
ORACLE = HERE / "oracle"

APEX_USER = "coalesce(current_setting('evs.app_user', true), current_user)"


def strip_ora2pg_header(sql: str) -> str:
    lines = []
    for ln in sql.splitlines():
        if ln.startswith(
            (
                "-- Generated by Ora2Pg",
                "-- Copyright",
                "-- DATASOURCE",
                "SET client_encoding",
                "\\set ON_ERROR_STOP",
                "SET check_function_bodies",
                "CREATE SCHEMA IF NOT EXISTS legacy",
                "ALTER SCHEMA legacy OWNER",
                "SET search_path",
            )
        ):
            continue
        lines.append(ln)
    return "\n".join(lines).strip() + "\n"


def _identity(m: re.Match[str]) -> str:
    col, pk = m.group(1), m.group(3)
    base = f"{col} bigint GENERATED BY DEFAULT AS IDENTITY"
    return f"{base} CONSTRAINT {pk} PRIMARY KEY" if pk else base


RULES: list[tuple[str, re.Pattern[str], str | Callable[[re.Match[str]], str]]] = [
    # Oracle 12c "number default on null to_number(sys_guid(),'X..') constraint x_pk primary key" surrogate keys
    # come out of ora2pg as a dangling DEFAULT; use a bigint identity column and keep the original PK name.
    (
        "identity_pk",
        re.compile(
            r"(\w+) numeric( NOT NULL)? DEFAULT on null to_number\(uuid_generate_v4\(\), '[xX]+'\)(?:\s+constraint (\w+))?",
            re.I,
        ),
        _identity,
    ),
    # surrogate and foreign key columns are NUMBER without precision in Oracle; bigint keeps FK types aligned
    ("id_bigint", re.compile(r"^(\t\w*id) numeric\b", re.M | re.I), r"\1 bigint"),
    # inline "constraint x_ck check (...)" is moved to ALTER TABLE by ora2pg, leaving "constraint x_ck )" behind
    ("dangling_check_name", re.compile(r"(\n\t\w+ [^\n,]*?)\s+constraint \w+\s*\)(,?)", re.I), r"\1\2"),
    # "create index ... on sp_notifications(name)" (no space) makes ora2pg emit a phantom empty table
    ("drop_empty_table", re.compile(r"^CREATE TABLE \w+ \(\n\) ;\n", re.M), ""),
    # redundant UNIQUE(id) emitted next to the lost primary key
    ("drop_unique_id", re.compile(r"^ALTER TABLE \w+ ADD UNIQUE \(id\);\n", re.M), ""),
    # file-input SEQUENCE export has no START value
    ("sequence_start", re.compile(r"START ;"), "START 1;"),
    # DEFAULT ON NULL 'x' (Oracle 12c) -> plain DEFAULT; the before-insert triggers keep the on-null semantics
    ("default_on_null", re.compile(r"DEFAULT on null\s+", re.I), "DEFAULT "),
    # ora2pg drops the closing parenthesis of inline CHECK (col in ('Y','N'))
    ("check_paren", re.compile(r"(CHECK \([^;\n]*\bin \([^)]*\))(;)", re.I), r"\1)\2"),
    # sys_context('APEX$SESSION','APP_USER') -> session GUC set by the API (evs.app_user)
    ("apex_session_user", re.compile(r"sys_context\('APEX\$SESSION',\s*'APP_USER'\)", re.I), APEX_USER),
    (
        "apex_session_id",
        re.compile(r"sys_context\('APEX\$SESSION',\s*'APP_SESSION'\)", re.I),
        "current_setting('evs.app_session', true)",
    ),
    # "null release_id" in the first branch of a UNION ALL view types the column as text; keys are bigint
    ("union_null_id", re.compile(r"\bnull (\w+_id)\b(?=,|\s)", re.I), r"null::bigint \1"),
    # audit columns are filled by the Oracle *_biu triggers; give them defaults so inserts work whether or not
    # a trigger converted (the app user is read from the evs.app_user setting the API sets per request)
    (
        "audit_ts_default",
        re.compile(r"^(\s+(?:created|updated) timestamp\(0\) NOT NULL)(,?)$", re.M),
        r"\1 DEFAULT statement_timestamp()\2",
    ),
    (
        "audit_user_default",
        re.compile(r"^(\s+(?:created_by|updated_by) varchar\(255\) NOT NULL)(,?)$", re.M),
        r"\1 DEFAULT coalesce(current_setting('evs.app_user', true), 'system')\2",
    ),
    ("wwv_flow_user", re.compile(r"wwv_flow\.g_user\b", re.I), "current_setting('evs.app_user', true)"),
    # package global sp_globals.g_audit_this (boolean := TRUE) becomes a session setting
    (
        "sp_globals_audit",
        re.compile(r"sp_globals\.g_audit_this\b", re.I),
        "coalesce(current_setting('evs.audit_this', true), 'true')::boolean",
    ),
    ("language", re.compile(r"LANGUAGE 'plpgsql'"), "LANGUAGE plpgsql"),
    ("execute_function", re.compile(r"EXECUTE PROCEDURE legacy\."), "EXECUTE FUNCTION legacy."),
]


def apply_rules(sql: str, counts: dict[str, int]) -> str:
    for name, pat, repl in RULES:
        sql, n = pat.subn(repl, sql)
        counts[name] = counts.get(name, 0) + n
    return sql


# Defects in the upstream APEX export itself (install_seed_countries.sql truncates the Portugal row).
UPSTREAM_FIXES = {}


def convert_oracle_dml(sql: str) -> str:
    """Oracle INSERT statements shipped with the app -> PostgreSQL."""
    for bad, good in UPSTREAM_FIXES.items():
        sql = sql.replace(bad, good)

    # Oracle alternative quoting q'[...]' / q'{...}' / q'(...)' / q'<...>' -> standard single quotes
    def unq(m: re.Match[str]) -> str:
        return "'" + m.group(2).replace("'", "''") + "'"

    for open_, close in (("[", "]"), ("{", "}"), ("(", ")"), ("<", ">")):
        sql = re.sub(r"\bq'(" + re.escape(open_) + r")(.*?)" + re.escape(close) + "'", unq, sql, flags=re.S | re.I)
    sql = re.sub(r"\bsysdate\s*([+-])\s*(\d+)", r"(now() \1 interval '\2 days')", sql, flags=re.I)
    sql = re.sub(r"\bsysdate\b", "now()", sql, flags=re.I)
    sql = re.sub(r"\bto_date\(\s*'([^']*)'\s*,\s*'([^']*)'\s*\)", r"to_timestamp('\1', '\2')", sql, flags=re.I)
    return sql


def header(title: str) -> str:
    return (
        f"-- {title}\n"
        "-- Source: Oracle APEX 24.2 Strategic Planner starter app (MIT), converted with ora2pg 25.0 in\n"
        "-- file-input mode plus the named post-processing rules in db/ora2pg/postprocess.py.\n"
        "-- Regenerate with db/ora2pg/run.sh. Hand edits belong in postprocess.py, not here.\n"
        "SET search_path = legacy, public;\n\n"
    )


def build_schema(counts: dict[str, int]) -> str:
    parts = [header("0002: legacy SP_ schema (ora2pg output, post-processed)")]
    parts.append(
        "-- APEX runtime shims: the six views call apex_page.get_url and sp_comment_util.replace_session_on_display.\n"
        "-- These stand-ins keep the views compilable; the React routes replace the generated APEX links.\n"
        "CREATE SCHEMA IF NOT EXISTS apex_page;\n"
        "CREATE OR REPLACE FUNCTION apex_page.get_url(p_page integer, p_items text DEFAULT NULL, p_values text DEFAULT NULL)\n"
        "RETURNS text LANGUAGE sql IMMUTABLE AS $$ SELECT format('/legacy/f?p=%s:%s:%s', p_page, p_items, p_values) $$;\n"
        "-- Oracle instr(str, sub, start) used by the document views (ora2pg ships the same helper in its orafce notes).\n"
        "CREATE OR REPLACE FUNCTION legacy.instr(str text, sub text, start_pos integer DEFAULT 1)\n"
        "RETURNS integer LANGUAGE plpgsql IMMUTABLE AS $$\n"
        "DECLARE pos integer; len integer; BEGIN\n"
        "  IF start_pos > 0 THEN\n"
        "    pos := position(sub IN substr(str, start_pos)); RETURN CASE WHEN pos = 0 THEN 0 ELSE pos + start_pos - 1 END;\n"
        "  ELSIF start_pos < 0 THEN\n"
        "    len := length(str);\n"
        "    FOR i IN REVERSE (len + start_pos + 1)..1 LOOP\n"
        "      IF substr(str, i, length(sub)) = sub THEN RETURN i; END IF;\n"
        "    END LOOP;\n"
        "    RETURN 0;\n"
        "  END IF;\n"
        "  RETURN 0;\n"
        "END $$;\n"
        "-- Oracle NUMBER locals arrive as numeric; PostgreSQL will not implicitly cast them for substr/instr\n"
        "CREATE OR REPLACE FUNCTION legacy.substr(str text, start_pos numeric) RETURNS text\n"
        "LANGUAGE sql IMMUTABLE AS $$ SELECT substr(str, start_pos::integer) $$;\n"
        "CREATE OR REPLACE FUNCTION legacy.substr(str text, start_pos numeric, len numeric) RETURNS text\n"
        "LANGUAGE sql IMMUTABLE AS $$ SELECT substr(str, start_pos::integer, len::integer) $$;\n"
        "CREATE OR REPLACE FUNCTION legacy.instr(str text, sub text, start_pos numeric) RETURNS integer\n"
        "LANGUAGE sql IMMUTABLE AS $$ SELECT legacy.instr(str, sub, start_pos::integer) $$;\n"
        "-- Package functions the triggers call (bodies hand-ported from output/PACKAGE.sql)\n"
        "CREATE SCHEMA IF NOT EXISTS sp_value_compare;\n"
        "CREATE OR REPLACE FUNCTION sp_value_compare.is_equal(p_value1 anyelement, p_value2 anyelement) RETURNS boolean\n"
        "LANGUAGE sql IMMUTABLE AS $$ SELECT p_value1 IS NOT DISTINCT FROM p_value2 $$;\n"
        "CREATE SCHEMA IF NOT EXISTS sp_util;\n"
        "CREATE OR REPLACE FUNCTION sp_util.compress_int(n bigint) RETURNS text LANGUAGE plpgsql IMMUTABLE AS $$\n"
        "DECLARE ret text := ''; quotient bigint := n; remainder integer;\n"
        "BEGIN\n"
        "  WHILE quotient > 0 LOOP\n"
        "    remainder := quotient % 36; quotient := quotient / 36;\n"
        "    ret := CASE WHEN remainder < 26 THEN chr(ascii('A') + remainder) ELSE chr(ascii('0') + remainder - 26) END || ret;\n"
        "  END LOOP;\n"
        "  IF length(ret) < 5 THEN ret := lpad(ret, 4, 'A'); END IF;\n"
        "  RETURN upper(ret);\n"
        "END $$;\n"
        "CREATE SCHEMA IF NOT EXISTS sp_comment_util;\n"
        "CREATE OR REPLACE FUNCTION sp_comment_util.replace_session_on_display(p_body text, p_session text)\n"
        "RETURNS text LANGUAGE sql IMMUTABLE AS $$ SELECT p_body $$;\n"
    )
    for name in ("SEQUENCE", "TABLE", "VIEW", "TRIGGER"):
        body = strip_ora2pg_header((OUT / f"{name}.sql").read_text())
        body = apply_rules(body, counts)
        parts.append(f"-- ---- ora2pg -t {name} ----\n{body}")
    return "\n".join(parts)


def build_data(counts: dict[str, int]) -> str:
    parts = [header("0003: seed and sample rows shipped with the Strategic Planner app")]
    parts.append("SELECT set_config('evs.app_user', 'apex_install', false);\n")
    for fname in ("07_seed_data.sql", "08_sample_data.sql"):
        body = (ORACLE / fname).read_text()
        body = "\n".join(
            ln
            for ln in body.splitlines()
            if not ln.startswith("-- source:") and not ln.startswith("-- Oracle DDL") and not ln.startswith("-- Generated")
        )
        body = re.sub(r"\n{3,}", "\n\n", body)
        parts.append(f"-- ---- {fname} ----\n{convert_oracle_dml(body).strip()}\n")
    parts.append(
        "-- Rows above carry explicit ids; move every identity sequence past them.\n"
        "DO $$\nDECLARE r record;\nBEGIN\n"
        "  FOR r IN SELECT table_name, column_name FROM information_schema.columns\n"
        "           WHERE table_schema = 'legacy' AND is_identity = 'YES' LOOP\n"
        "    EXECUTE format('SELECT setval(pg_get_serial_sequence(%L, %L), coalesce((SELECT max(%I) FROM legacy.%I), 0) + 1, false)',\n"  # noqa: E501
        "                   'legacy.' || r.table_name, r.column_name, r.column_name, r.table_name);\n"
        "  END LOOP;\nEND $$;\n"
    )
    return "\n".join(parts)


def cost_summary() -> list[tuple[str, int, str]]:
    """(object type, object count, ora2pg total cost line) per export type."""
    rows = []
    for name in ("SEQUENCE", "TABLE", "VIEW", "TRIGGER", "PACKAGE", "FUNCTION", "PROCEDURE"):
        text = (OUT / f"{name}.sql").read_text()
        total = re.findall(r"-- Total estimated cost(?: for \w+ \w+)?: ([\d.]+) units, (\d+) person-day", text)
        n = {
            "SEQUENCE": len(re.findall(r"^CREATE SEQUENCE", text, re.M)),
            "TABLE": len(re.findall(r"^CREATE TABLE", text, re.M)),
            "VIEW": len(re.findall(r"^CREATE OR REPLACE VIEW", text, re.M)),
            "TRIGGER": len(re.findall(r"^CREATE TRIGGER", text, re.M)),
            "PACKAGE": len(re.findall(r"^-- Total estimated cost for package", text, re.M)),
            "FUNCTION": len(re.findall(r"^CREATE OR REPLACE FUNCTION", text, re.M)),
            "PROCEDURE": len(re.findall(r"^CREATE OR REPLACE PROCEDURE", text, re.M)),
        }[name]
        units = sum(float(u) for u, _ in total)
        days = sum(int(d) for _, d in total)
        rows.append((name, n, f"{units:g} units, {days} person-day(s)" if total else "n/a (DDL only)"))
    return rows


def build_assessment(counts: dict[str, int]) -> str:
    rows = cost_summary()
    pkg_text = (OUT / "PACKAGE.sql").read_text()
    pkg_lines = re.findall(r"^-- Total estimated cost for package (\w+): ([\d.]+) units, (\d+) person-day", pkg_text, re.M)
    md = [
        "# ora2pg assessment: Strategic Planner SP_ schema\n",
        "Generated by `db/ora2pg/run.sh` (ora2pg 25.0, `--estimate_cost`, `COST_UNIT_VALUE 5` minutes).",
        "`ora2pg -t SHOW_REPORT` needs a live Oracle connection and is not available in file-input mode,",
        "so this report is assembled from the per-type exports in `db/ora2pg/output/`.\n",
        "| Export type | Objects | ora2pg estimate | Disposition |",
        "|---|---|---|---|",
    ]
    disposition = {
        "SEQUENCE": "applied in 0002",
        "TABLE": "applied in 0002 after post-processing",
        "VIEW": "applied in 0002 with APEX shims (apex_page.get_url, sp_comment_util.replace_session_on_display)",
        "TRIGGER": "applied in 0002 (sys_context APEX$SESSION -> current_setting('evs.app_user'))",
        "PACKAGE": "converted for reference only (output/PACKAGE.sql); business logic moves to FastAPI services",
        "FUNCTION": "converted for reference only (output/FUNCTION.sql)",
        "PROCEDURE": "converted for reference only (output/PROCEDURE.sql)",
    }
    for name, n, cost in rows:
        md.append(f"| {name} | {n} | {cost} | {disposition[name]} |")
    md += [
        "",
        "## Package detail (ora2pg --estimate_cost)",
        "",
        "| Package | Units | Person-days |",
        "|---|---|---|",
    ]
    for p, u, d in pkg_lines:
        md.append(f"| {p} | {u} | {d} |")
    md += [
        "",
        "## Post-processing rules applied (db/ora2pg/postprocess.py)",
        "",
        "| Rule | Occurrences |",
        "|---|---|",
    ]
    for k, v in counts.items():
        md.append(f"| {k} | {v} |")
    md += [
        "",
        "## Limitations and hand conversions",
        "",
        "- File-input mode cannot read `wwv_flow_imp_shared.create_install_script` wrappers; `extract_apex_install_scripts.py` unwraps them first.",  # noqa: E501
        "- `SHOW_REPORT` and `INSERT`/`COPY` data export require an Oracle connection. Shipped seed and sample rows are converted by regex (`sysdate`, `to_date`) in `postprocess.convert_oracle_dml` into 0003.",  # noqa: E501
        "- `sp_util.add_setting` / `sp_util.add_ai_prompt` seed calls and the two `dbms_scheduler` jobs (`oracle/09_other_plsql.sql`) are not loaded; settings and prompts are APEX runtime configuration with no EVS equivalent, and the jobs are replaced by the ingestion worker.",  # noqa: E501
        "- Packages call `apex_util`, `apex_mail`, `apex_string`, `dbms_lob` and `apex_json`; ora2pg converts syntax but the APEX PL/SQL API has no PostgreSQL equivalent. Each package's responsibilities are re-implemented in `apps/api/evs` (approvals, comments, summaries, notifications).",  # noqa: E501
        "- Oracle `default on null` becomes a plain `DEFAULT`; the before-insert triggers (`*_biu`) still populate audit columns.",  # noqa: E501
        "- APEX splits long scripts into `append_to_install_script` chunks, sometimes mid line (the Portugal row in `install_seed_countries.sql`); the extractor concatenates chunks byte for byte.",  # noqa: E501
        "",
    ]
    return "\n".join(md)


def main() -> None:
    counts: dict[str, int] = {}
    MIGRATIONS.mkdir(parents=True, exist_ok=True)
    (MIGRATIONS / "0002_legacy_sp_schema.sql").write_text(build_schema(counts))
    (MIGRATIONS / "0003_legacy_sp_data.sql").write_text(build_data(counts))
    (HERE / "ASSESSMENT.md").write_text(build_assessment(counts))
    for k, v in counts.items():
        print(f"{k:20s} {v}")


if __name__ == "__main__":
    main()
