-- Oracle DDL/DML rebuilt from the APEX 24.2 Strategic Planner starter app export (f7150, MIT licence).
-- Generated by db/ora2pg/extract_apex_install_scripts.py; input to ora2pg. Do not edit by hand.

-- source: install_sp_app_log_table.sql (p_sequence 60, sp_app_log table)
create or replace trigger sp_app_log_bi
   before insert on sp_app_log
   for each row
begin
   :new.created       := sysdate;
   :new.created_trunc := trunc(sysdate);
   :new.created_by    := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end sp_app_log_bi;
/
