-- Runs every supporting-object script in APEX install order (SQL*Plus / SQLcl syntax).
@@001_sequences.sql
@@002_sp_globals_spec.sql
@@003_sp_util_spec.sql
@@004_sp_comment_util_spec.sql
@@005_sp_contributor_summary_spec.sql
@@006_sp_release_timeline_package_spec.sql
@@007_sp_approvals_spec.sql
@@008_sp_summary_util_spec.sql
@@009_sp_app_log_table.sql
@@010_sp_error_log_table_and_trigger.sql
@@011_sp_app_settings.sql
@@012_ai_prompts_table_and_trigger.sql
@@013_sp_report_questions_table_and_trigger.sql
@@014_sp_default_tags_table.sql
@@015_sp_app_nomenclature_table.sql
@@016_sp_resource_types_table.sql
@@017_sp_competencies_table.sql
@@018_sp_groups_table.sql
@@019_sp_team_members_table.sql
@@020_sp_group_members_table.sql
@@021_sp_release_trains_table.sql
@@022_sp_release_history_table.sql
@@023_sp_areas_table.sql
@@024_sp_project_scales_table.sql
@@025_sp_initiatives_tables.sql
@@026_sp_project_priorities_table.sql
@@027_sp_project_sizes_table.sql
@@028_sp_project_statuses_table.sql
@@029_sp_project_groups_table.sql
@@030_sp_initiative_focus_areas_tables.sql
@@031_sp_projects_tables.sql
@@032_sp_project_history_table.sql
@@033_sp_project_links_table.sql
@@034_sp_project_comments_table.sql
@@035_sp_release_comments_table.sql
@@036_sp_comment_images_table_and_trigger.sql
@@037_sp_release_milestone_types_table_and_trigger.sql
@@038_release_milestones_table.sql
@@039_release_milestone_default_tags_table_and_trigger.sql
@@040_release_documents_table_and_triggr.sql
@@041_package_sp_value_compare.sql
@@042_countries_table.sql
@@043_external_system_names.sql
@@044_triggers.sql
@@045_sp_notifications_table.sql
@@046_sp_notification_subscriptions.sql
@@047_create_sp_areas_trigger.sql
@@048_release_trains_triggers.sql
@@049_create_sp_team_members_trigger.sql
@@050_sp_group_members_trigger.sql
@@051_sp_competencies_trigger.sql
@@052_sp_groups_trigger.sql
@@053_initiatives_triggers.sql
@@054_initiative_focus_area_triggers.sql
@@055_project_comments_triggers.sql
@@056_project_contributors_triggers.sql
@@057_release_comments_triggers.sql
@@058_project_documents_triggers.sql
@@059_project_links_triggers.sql
@@060_related_projects_trigger.sql
@@061_projects_triggers.sql
@@062_release_milestone_triggers.sql
@@063_proj_interactions_log_table.sql
@@064_activity_types_table.sql
@@065_activity_types_triggers.sql
@@066_sp_activities_table.sql
@@067_sp_activities_trigger.sql
@@068_sp_date_range_pct_comp_function.sql
@@069_sp_tag_diff_function.sql
@@070_favorites_table.sql
@@071_favorite_toggle_procedure.sql
@@072_configurable_text_table.sql
@@073_sp_default_people_tags_table.sql
@@074_sp_default_people_tags_trigger.sql
@@075_create_sp_application_notifications.sql
@@076_initiative_comments_table_and_trigger.sql
@@077_create_table_sp_release_links.sql
@@078_initiative_links_table_and_trigger.sql
@@079_initiative_documents_table_and_trigger.sql
@@080_project_task_tables.sql
@@081_project_task_triggers.sql
@@082_team_member_notifications.sql
@@083_approval_tables_and_triggers.sql
@@084_ai_summary_tables.sql
@@085_comment_views.sql
@@086_sp_documents_v_view.sql
@@087_sp_contributor_summary_body.sql
@@088_sp_release_timeline_package_body.sql
@@089_sp_util_body.sql
@@090_sp_approvals_body.sql
@@091_sp_comment_util_body.sql
@@092_sp_summary_util_body.sql
@@093_seed_countries.sql
@@094_seed_nomenclature.sql
@@095_seed_external_ticketing_systems.sql
@@096_seed_resource_types.sql
@@097_seed_project_scales.sql
@@098_seed_project_statuses.sql
@@099_seed_default_tags.sql
@@100_seed_project_priorities.sql
@@101_seed_project_sizes.sql
@@102_seed_activity_types.sql
@@103_seed_release_milestone_types.sql
@@104_seed_settings_and_prompts.sql
@@105_seed_notifications.sql
@@106_seed_competencies.sql
@@107_seed_task_types_and_statuses.sql
@@108_create_sample_data.sql
@@109_notifications_job.sql
@@110_sp_generate_ai_project_summaries_job.sql
@@111_seed_first_user.sql
