/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Programs */
        get: operations["list_programs_api_v1_programs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{p2_project_no}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_v1_projects__p2_project_no__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/financial/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Financial Summary */
        get: operations["financial_summary_api_v1_financial_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workforce/labor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Labor */
        get: operations["labor_api_v1_workforce_labor_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/facilities/condition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Condition */
        get: operations["condition_api_v1_facilities_condition_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/locks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Locks
         * @description All locks in evs.lock_current. `reporting_only` drops locks absent from the LPMS status feed.
         */
        get: operations["list_locks_api_v1_public_locks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/locks/{lock_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lock */
        get: operations["get_lock_api_v1_public_locks__lock_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/locks/stream/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream */
        get: operations["stream_api_v1_public_locks_stream_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/srp/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coverage */
        get: operations["coverage_api_v1_public_srp_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accessibility/readout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readout */
        get: operations["readout_api_v1_accessibility_readout_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/feeds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Feeds */
        get: operations["feeds_api_v1_admin_feeds_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/thresholds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Thresholds */
        get: operations["thresholds_api_v1_admin_thresholds_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccessibilityReadout */
        AccessibilityReadout: {
            /** Target */
            target: string;
            /** Routes */
            routes: components["schemas"]["AxeRouteResult"][];
            /** Criteria */
            criteria: components["schemas"]["CriterionStatus"][];
            /** Acr Download Url */
            acr_download_url: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /** AppropriationRow */
        AppropriationRow: {
            /** Appropriation */
            appropriation: string;
            /** Title */
            title: string;
            /** Allotted */
            allotted: number;
            /** Committed */
            committed: number;
            /** Obligated */
            obligated: number;
            /** Expended */
            expended: number;
            /** Expiring Fy */
            expiring_fy?: number | null;
        };
        /**
         * AsOf
         * @description Every dataset carries both the source timestamp and when EVS fetched it.
         */
        AsOf: {
            /**
             * Source As Of
             * @description Newest timestamp inside the source payload
             */
            source_as_of?: string | null;
            /**
             * Fetched At
             * @description When the EVS ingestion worker stored it
             */
            fetched_at?: string | null;
            /**
             * Freshness
             * @default fresh
             * @enum {string}
             */
            freshness: "fresh" | "aging" | "stale" | "simulated";
            /**
             * Source
             * @description live | fixtures | simulated | synthetic
             * @default fixtures
             */
            source: string;
        };
        /** AxeRouteResult */
        AxeRouteResult: {
            /** Route */
            route: string;
            /** Viewport */
            viewport: string;
            /** Theme */
            theme: string;
            /**
             * Reduced Motion
             * @default false
             */
            reduced_motion: boolean;
            /** Violations */
            violations: number;
            /** Passes */
            passes: number;
            /** Incomplete */
            incomplete: number;
            /**
             * Run At
             * Format: date-time
             */
            run_at: string;
        };
        /** CriterionStatus */
        CriterionStatus: {
            /** Criterion */
            criterion: string;
            /** Name */
            name: string;
            /**
             * Level
             * @enum {string}
             */
            level: "A" | "AA";
            /**
             * Method
             * @enum {string}
             */
            method: "automated" | "manual" | "not_applicable";
            /**
             * Status
             * @enum {string}
             */
            status: "supports" | "partially-supports" | "does-not-support" | "not-applicable" | "not-evaluated";
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /** ExecutionPoint */
        ExecutionPoint: {
            /**
             * Period
             * Format: date
             */
            period: string;
            /** Plan Cumulative */
            plan_cumulative: number;
            /** Obligated Cumulative */
            obligated_cumulative: number;
            /** Expended Cumulative */
            expended_cumulative: number;
        };
        /** FacilityRow */
        FacilityRow: {
            /** Building Id */
            building_id: string;
            /** Installation */
            installation: string;
            /** District */
            district: string;
            /** Uniformat Section */
            uniformat_section: string;
            /** Component Type */
            component_type: string;
            /** Ci */
            ci: number;
            /** Bci */
            bci: number;
            /** Deficiency Cost */
            deficiency_cost: number;
            /** Work Plan Year */
            work_plan_year: number;
        };
        /** FacilitySummary */
        FacilitySummary: {
            /** Rows */
            rows: components["schemas"]["FacilityRow"][];
            as_of: components["schemas"]["AsOf"];
        };
        /** FeedHealth */
        FeedHealth: {
            /** Source */
            source: string;
            /** Endpoint */
            endpoint: string;
            /** Cadence Minutes */
            cadence_minutes: number;
            /** Last Success At */
            last_success_at: string | null;
            /** Last Error */
            last_error: string | null;
            /** Latency Ms */
            latency_ms: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "healthy" | "degraded" | "down" | "simulated" | "fixtures";
            /** Mode */
            mode?: ("live" | "fixtures" | "simulated") | null;
            /** Last Attempt At */
            last_attempt_at?: string | null;
            /** Http Status */
            http_status?: number | null;
            /** Rows Parsed */
            rows_parsed?: number | null;
            /**
             * Consecutive Failures
             * @default 0
             */
            consecutive_failures: number;
            /** Updated At */
            updated_at?: string | null;
        };
        /** FeedHealthList */
        FeedHealthList: {
            /** Feeds */
            feeds: components["schemas"]["FeedHealth"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /** FinancialSummary */
        FinancialSummary: {
            /** Fiscal Year */
            fiscal_year: number;
            /** Execution Curve */
            execution_curve: components["schemas"]["ExecutionPoint"][];
            /** By Appropriation */
            by_appropriation: components["schemas"]["AppropriationRow"][];
            as_of: components["schemas"]["AsOf"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LaborRow */
        LaborRow: {
            /** District */
            district: string;
            /** Pay Period */
            pay_period: string;
            /** Hours Plan */
            hours_plan: number;
            /** Hours Regular */
            hours_regular: number;
            /** Hours Overtime */
            hours_overtime: number;
            /** Labor Cost */
            labor_cost: number;
        };
        /** LaborSummary */
        LaborSummary: {
            /** Fiscal Year */
            fiscal_year: number;
            /** Rows */
            rows: components["schemas"]["LaborRow"][];
            as_of: components["schemas"]["AsOf"];
        };
        /** LockDetail */
        LockDetail: {
            /**
             * Lock Id
             * @description riverCode + '-' + lockNo, e.g. OH-79
             */
            lock_id: string;
            /** River Code */
            river_code: string;
            /** River Name */
            river_name: string;
            /** Lock Name */
            lock_name: string;
            /** Lock No */
            lock_no: string;
            /** River Mile */
            river_mile: number | null;
            /** District */
            district: string | null;
            /**
             * Division
             * @description USACE division code, e.g. LRD
             */
            division?: string | null;
            /** State */
            state?: string | null;
            /** Chambers */
            chambers: number | null;
            /** Latitude */
            latitude: number | null;
            /** Longitude */
            longitude: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "operating" | "delayed" | "closed" | "stale" | "unknown";
            /** Status Reason */
            status_reason: string;
            /** Vessels Queued */
            vessels_queued: number | null;
            /** Avg Delay 4H Min */
            avg_delay_4h_min: number | null;
            /** Avg Delay 24H Min */
            avg_delay_24h_min: number | null;
            /** Last Lockage At */
            last_lockage_at: string | null;
            /** Gauge Stage Ft */
            gauge_stage_ft?: number | null;
            /** Flood Category */
            flood_category?: string | null;
            /**
             * Active Stoppages
             * @default 0
             */
            active_stoppages: number;
            as_of: components["schemas"]["AsOf"];
            /** Lift Ft */
            lift_ft?: number | null;
            /** Chamber Dimensions */
            chamber_dimensions?: string | null;
            /** Year Opened */
            year_opened?: number | null;
            /** Owner */
            owner?: string | null;
            /** Operator */
            operator?: string | null;
            /**
             * Queue
             * @default []
             */
            queue: {
                [key: string]: unknown;
            }[];
            /**
             * Stoppages
             * @default []
             */
            stoppages: {
                [key: string]: unknown;
            }[];
            /**
             * Recent Lockages
             * @default []
             */
            recent_lockages: {
                [key: string]: unknown;
            }[];
            /**
             * Gauges
             * @description Latest NOAA NWPS and USGS NWIS readings for the lock
             */
            gauges?: {
                [key: string]: unknown;
            }[];
            /**
             * Status Inputs
             * @description inputs_used by the status engine
             */
            status_inputs?: {
                [key: string]: unknown;
            };
            /**
             * History
             * @description Status evaluations from the last 24 hours, oldest first
             */
            history?: components["schemas"]["StatusHistoryPoint"][];
            /**
             * Ntni Notices
             * @description Notices to Navigation Interests that name this lock
             */
            ntni_notices?: {
                [key: string]: unknown;
            }[];
        };
        /** LockList */
        LockList: {
            /** Items */
            items: components["schemas"]["LockSummary"][];
            /** Rivers */
            rivers: {
                [key: string]: string;
            }[];
            /** Counts */
            counts: {
                [key: string]: number;
            };
            as_of: components["schemas"]["AsOf"];
        };
        /**
         * LockSummary
         * @description One row of the live lock table. Geometry comes from the NDC GIS layer, status from LPMS.
         */
        LockSummary: {
            /**
             * Lock Id
             * @description riverCode + '-' + lockNo, e.g. OH-79
             */
            lock_id: string;
            /** River Code */
            river_code: string;
            /** River Name */
            river_name: string;
            /** Lock Name */
            lock_name: string;
            /** Lock No */
            lock_no: string;
            /** River Mile */
            river_mile: number | null;
            /** District */
            district: string | null;
            /**
             * Division
             * @description USACE division code, e.g. LRD
             */
            division?: string | null;
            /** State */
            state?: string | null;
            /** Chambers */
            chambers: number | null;
            /** Latitude */
            latitude: number | null;
            /** Longitude */
            longitude: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "operating" | "delayed" | "closed" | "stale" | "unknown";
            /** Status Reason */
            status_reason: string;
            /** Vessels Queued */
            vessels_queued: number | null;
            /** Avg Delay 4H Min */
            avg_delay_4h_min: number | null;
            /** Avg Delay 24H Min */
            avg_delay_24h_min: number | null;
            /** Last Lockage At */
            last_lockage_at: string | null;
            /** Gauge Stage Ft */
            gauge_stage_ft?: number | null;
            /** Flood Category */
            flood_category?: string | null;
            /**
             * Active Stoppages
             * @default 0
             */
            active_stoppages: number;
            as_of: components["schemas"]["AsOf"];
        };
        /** Milestone */
        Milestone: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Baseline Date */
            baseline_date: string | null;
            /** Current Date */
            current_date: string | null;
            /** Actual Date */
            actual_date: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "complete" | "scheduled" | "slipped";
        };
        /** Page */
        Page: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Program */
        Program: {
            /** Program Code */
            program_code: string;
            /** Name */
            name: string;
            /** Business Line */
            business_line: string;
            /** Division */
            division: string;
            /** Funded Amount */
            funded_amount: number;
            /** Obligated Amount */
            obligated_amount: number;
            /** Expended Amount */
            expended_amount: number;
            /** Variance Pct */
            variance_pct: number;
            /** Project Count */
            project_count: number;
            /**
             * Schedule Health
             * @enum {string}
             */
            schedule_health: "on_track" | "at_risk" | "late";
        };
        /** ProgramList */
        ProgramList: {
            /** Items */
            items: components["schemas"]["Program"][];
            page: components["schemas"]["Page"];
            as_of: components["schemas"]["AsOf"];
        };
        /** Project */
        Project: {
            /** P2 Project No */
            p2_project_no: string;
            /** Name */
            name: string;
            /** Program Code */
            program_code: string;
            /** District */
            district: string;
            /** Division */
            division: string;
            /** Business Line */
            business_line: string;
            /** Phase */
            phase: string;
            /** Pdt Lead */
            pdt_lead: string;
            /** Baseline Finish */
            baseline_finish: string | null;
            /** Current Finish */
            current_finish: string | null;
            /** Pct Complete */
            pct_complete: number;
            /** Funded Amount */
            funded_amount: number;
            /** Obligated Amount */
            obligated_amount: number;
            /** Expended Amount */
            expended_amount: number;
            /**
             * Schedule Health
             * @enum {string}
             */
            schedule_health: "on_track" | "at_risk" | "late";
            /**
             * Milestones
             * @default []
             */
            milestones: components["schemas"]["Milestone"][];
        };
        /** ProjectList */
        ProjectList: {
            /** Items */
            items: components["schemas"]["Project"][];
            page: components["schemas"]["Page"];
            as_of: components["schemas"]["AsOf"];
        };
        /**
         * SrpCitation
         * @description Provenance for one headline figure. The UI shows source and year next to every number.
         */
        SrpCitation: {
            /**
             * Figure
             * @description Key in `headline`, e.g. river_systems
             */
            figure: string;
            /** Label */
            label: string;
            /**
             * Value Text
             * @description The figure as the source states it, e.g. 'nearly 15,000 miles'
             */
            value_text: string;
            /** Source */
            source: string;
            /** Source Url */
            source_url: string;
            /** Year */
            year: number;
            /** Note */
            note?: string | null;
        };
        /** SrpCoverage */
        SrpCoverage: {
            /** Snapshots */
            snapshots: components["schemas"]["SrpSnapshot"][];
            /** Sites */
            sites: components["schemas"]["SrpSite"][];
            /** Headline */
            headline: {
                [key: string]: number | string;
            };
            /** Citations */
            citations?: components["schemas"]["SrpCitation"][];
            as_of: components["schemas"]["AsOf"];
        };
        /** SrpSite */
        SrpSite: {
            /** Name */
            name: string;
            /** River */
            river: string;
            /** State */
            state: string;
            /** District */
            district: string | null;
            /** Nid Id */
            nid_id: string | null;
            /** Latitude */
            latitude: number | null;
            /** Longitude */
            longitude: number | null;
            /** Year Joined */
            year_joined: number | null;
            /** Source Url */
            source_url: string;
        };
        /** SrpSnapshot */
        SrpSnapshot: {
            /** Year */
            year: number;
            /** River Systems */
            river_systems: number | null;
            /** Dams */
            dams: number | null;
            /** River Miles */
            river_miles: number | null;
            /** Floodplain Acres */
            floodplain_acres?: number | null;
            /** Source */
            source: string;
            /** Source Url */
            source_url: string;
        };
        /**
         * StatusHistoryPoint
         * @description One status engine evaluation, newest last; the detail panel draws the 24-hour history from these.
         */
        StatusHistoryPoint: {
            /**
             * Evaluated At
             * Format: date-time
             */
            evaluated_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "operating" | "delayed" | "closed" | "stale" | "unknown";
            /** Status Reason */
            status_reason: string;
            /** Rule No */
            rule_no?: number | null;
            /** Source */
            source: string;
            /** Freshness */
            freshness: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_programs_api_v1_programs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: {
                program_code?: string | null;
                district?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__p2_project_no__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                p2_project_no: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    financial_summary_api_v1_financial_summary_get: {
        parameters: {
            query?: {
                fiscal_year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinancialSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    labor_api_v1_workforce_labor_get: {
        parameters: {
            query?: {
                fiscal_year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LaborSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    condition_api_v1_facilities_condition_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacilitySummary"];
                };
            };
        };
    };
    list_locks_api_v1_public_locks_get: {
        parameters: {
            query?: {
                river_code?: string | null;
                reporting_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LockList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lock_api_v1_public_locks__lock_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lock_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LockDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_api_v1_public_locks_stream_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    coverage_api_v1_public_srp_coverage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SrpCoverage"];
                };
            };
        };
    };
    readout_api_v1_accessibility_readout_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessibilityReadout"];
                };
            };
        };
    };
    feeds_api_v1_admin_feeds_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedHealthList"];
                };
            };
        };
    };
    thresholds_api_v1_admin_thresholds_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
